### ISSUE TITLE
My frame got black screen again!

### ISSUE THREAD

**Issue by tarbucndge** [mrworf/photoframe#10]
Hello, 
I dont know why but my frame got black screen again.
I got the debug screen here, please take a look.
Thank you very much.
![log](https://user-images.githubusercontent.com/33946641/42483530-4558ea28-8418-11e8-91d8-f518faf6387b.png)

**Comment by tarbucndge** [comment]
I also tried to reauthorized but I got Internal Server Error.
![log1](https://user-images.githubusercontent.com/33946641/42483593-a17224a0-8418-11e8-98bc-4c063aa16dc9.png)

**Comment by mrworf** [comment]
You seem to run out of random numbers, try installing rng-tools like so
```
sudo apt install rng-tools
```
and then reboot (`sudo reboot`). Should resolve the lack of random. Let me know

**Comment by tarbucndge** [comment]
It works.
Thanks.
