### ISSUE TITLE
Simple URL

### ISSUE THREAD

**Issue by sboutros** [mrworf/photoframe#100]
I assumed "Simple URL" would be a URL that is called every x seconds per the config.
I've coded a page to serve a random image however I discovered that the frame only ever calls this URL once and not repeatedly as I was expecting.
Can you advise?

**Comment by sboutros** [comment]
anybody....?

**Comment by mrworf** [comment]
I think it might have been cached now, that was introduced with an earlier change. Hopefully I'll be able to get to that in the next week or so.

**Comment by sboutros** [comment]
Great thanks.
Can you explain the intended behavior of this feature? Just want to make sure I understand it correctly.

**Comment by mrworf** [comment]
The behavior is intended the way you thought it was, HOWEVER since we added caching, there needs to be an option to disable that as needed (some users prefer the image cached, other don't, etc).

**Comment by sboutros** [comment]
Is there an easy way for me to turn off caching in the existing code base?
I guess I have the Jan-2019 build.

**Comment by mrworf** [comment]
You should be able to change https://github.com/mrworf/photoframe/blob/master/modules/cachemanager.py#L57 to always return false. But this I haven't tested yet. Also, running with local changes will disable automatic updates (jfyi)

**Comment by sboutros** [comment]
Thanks, that did the trick!
I am occasionally seeing this exception:

Jul 27 22:08:58 photoframe photoframe[520]: 2019-07-27 22:08:58,051 - INFO - Simple URL is probably out of images!
Jul 27 22:08:58 photoframe photoframe[520]: 2019-07-27 22:08:58,052 - INFO - Photoframe's memory was reset. Already displayed images will be shown again!
Jul 27 22:09:46 photoframe photoframe[520]: 2019-07-27 22:09:46,096 - INFO - Simple URL is probably out of images!
Jul 27 22:09:46 photoframe photoframe[520]: 2019-07-27 22:09:46,097 - INFO - Photoframe's memory was reset. Already displayed images will be shown again!
Jul 27 22:10:34 photoframe photoframe[520]: 2019-07-27 22:10:34,020 - INFO - Simple URL is probably out of images!
Jul 27 22:10:34 photoframe photoframe[520]: 2019-07-27 22:10:34,021 - INFO - Photoframe's memory was reset. Already displayed images will be shown again!
Jul 27 22:11:21 photoframe photoframe[520]: 2019-07-27 22:11:21,445 - INFO - Simple URL is probably out of images!
Jul 27 22:11:21 photoframe photoframe[520]: 2019-07-27 22:11:21,446 - INFO - Photoframe's memory was reset. Already displayed images will be shown again!
Jul 27 22:12:09 photoframe photoframe[520]: 2019-07-27 22:12:09,699 - INFO - Simple URL is probably out of images!
Jul 27 22:12:09 photoframe photoframe[520]: 2019-07-27 22:12:09,700 - INFO - Photoframe's memory was reset. Already displayed images will be shown again!
Jul 27 22:12:57 photoframe photoframe[520]: 2019-07-27 22:12:57,096 - INFO - Simple URL is probably out of images!
Jul 27 22:12:57 photoframe photoframe[520]: 2019-07-27 22:12:57,097 - INFO - Photoframe's memory was reset. Already displayed images will be shown again!
Jul 27 22:12:57 photoframe photoframe[520]: Exception in thread Thread-4:
Jul 27 22:12:57 photoframe photoframe[520]: Traceback (most recent call last):
Jul 27 22:12:57 photoframe photoframe[520]:   File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
Jul 27 22:12:57 photoframe photoframe[520]:     self.run()
Jul 27 22:12:57 photoframe photoframe[520]:   File "/usr/lib/python2.7/threading.py", line 754, in run
Jul 27 22:12:57 photoframe photoframe[520]:     self.__target(*self.__args, **self.__kwargs)
Jul 27 22:12:57 photoframe photoframe[520]:   File "/root/photoframe/modules/slideshow.py", line 278, in presentation
Jul 27 22:12:57 photoframe photoframe[520]:     filenameProcessed = self.process(filenameOriginal)
Jul 27 22:12:57 photoframe photoframe[520]:   File "/root/photoframe/modules/slideshow.py", line 217, in process
Jul 27 22:12:57 photoframe photoframe[520]:     filenameProcessed = helper.makeFullframe(filename, self.settings.getUser('width'), self.settings.getUser('height'), autoChoose=True)
Jul 27 22:12:57 photoframe photoframe[520]:   File "/root/photoframe/modules/helper.py", line 159, in makeFullframe
Jul 27 22:12:57 photoframe photoframe[520]:     width = imageSize["width"]
Jul 27 22:12:57 photoframe photoframe[520]: TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by sboutros** [comment]
Hello, I had just modified per your last comment and all seemed to be working fine. Had to rebuild the image (starting from your distro image/Jan2019). That part is fine and upon logging in I did:
 git fetch origin
 git checkout master
 git merge origin/master

Then I ensured that useCachedImage always returns False.
However - I do see the frame hitting the server on an ongoing basis but also see this in the logs:
Simple URL is probably out of images!
Photoframe's memory was reset. Already displayed images will be shown again!

Any idea what I did wrong?

**Comment by mrworf** [comment]
Nothing, the debug messages simply indicate that is has shown 1 image and there are no others to show. I guess the message is a bit cryptic 😄

**Comment by mrworf** [comment]
Newest version (just pushed) will allow you to disable caching (globally) from web ui. Please update and let me know 😸

**Comment by sboutros** [comment]
Thx. Just did a git pull and have the new UI. No images displayed. Seeing this in the logs:


Sep 21 16:00:44 photoframe photoframe[563]: 2019-09-21 16:00:44,248 - INFO - Registering URL /control/ to RouteControl
Sep 21 16:00:55 photoframe photoframe[563]: 2019-09-21 16:00:55,635 - INFO - Starting presentation
Sep 21 16:01:06 photoframe photoframe[563]: Exception in thread Thread-5:
Sep 21 16:01:06 photoframe photoframe[563]: Traceback (most recent call last):
Sep 21 16:01:06 photoframe photoframe[563]:   File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
Sep 21 16:01:06 photoframe photoframe[563]:     self.run()
Sep 21 16:01:06 photoframe photoframe[563]:   File "/usr/lib/python2.7/threading.py", line 754, in run
Sep 21 16:01:06 photoframe photoframe[563]:     self.__target(*self.__args, **self.__kwargs)
Sep 21 16:01:06 photoframe photoframe[563]:   File "/root/photoframe/modules/slideshow.py", line 305, in presentation
Sep 21 16:01:06 photoframe photoframe[563]:     result = self.services.servicePrepareNextItem(self.settings.get('tempfolder'), self.supportedFormats, displaySize, randomize)
Sep 21 16:01:06 photoframe photoframe[563]:   File "/root/photoframe/modules/servicemanager.py", line 409, in servicePrepareNextItem
Sep 21 16:01:06 photoframe photoframe[563]:     result = svc.prepareNextItem(destinationDir, supportedMimeTypes, displaySize, randomize)
Sep 21 16:01:06 photoframe photoframe[563]:   File "/root/photoframe/services/base.py", line 410, in prepareNextItem
Sep 21 16:01:06 photoframe photoframe[563]:     result = self.selectImageFromAlbum(destinationFile, supportedMimeTypes, displaySize, randomize)
Sep 21 16:01:06 photoframe photoframe[563]:   File "/root/photoframe/services/svc_simpleurl.py", line 65, in selectImageFromAlbum
Sep 21 16:01:06 photoframe photoframe[563]:     result = BaseService.selectImageFromAlbum(self, destinationDir, supportedMimeTypes, displaySize, randomize)
Sep 21 16:01:06 photoframe photoframe[563]:   File "/root/photoframe/services/base.py", line 495, in selectImageFromAlbum
Sep 21 16:01:06 photoframe photoframe[563]:     cacheFile = self._CACHEMGR.getCachedImage(image.getCacheId(), filename)
Sep 21 16:01:06 photoframe photoframe[563]: AttributeError: 'NoneType' object has no attribute 'getCachedImage'
Sep 21 16:02:19 photoframe photoframe[540]: 2019-09-21 16:02:19,051 - INFO - Loading service USB_Photos from svc_usb.py
Sep 21 16:02:19 photoframe photoframe[540]: 2019-09-21 16:02:19,056 - INFO - Loading service PicasaWeb from svc_picasaweb.py

**Comment by mrworf** [comment]
I had missed a corner case for the cache manager, it should work now if you update. But I also added an error message should this happen again, just in case 🙂 so keep an eye out for `CacheManager is not available` in your log, this would indicate that for some reason the fix isn't working for you (I could no longer replicate here, but you never know...)

**Comment by sboutros** [comment]
Awesome, thank you! All working well now!
