### ISSUE TITLE
Support RPi4

### ISSUE THREAD

**Issue by mrworf** [mrworf/photoframe#105]
New raspberry pi, make sure it works on that one. Specifically, if possible, make the SD Card image file support RPi4 as well as the older models.

**Comment by lmarino05** [comment]
I have an RPI4 and was able to get the software working after following your manual installation instructions. I'm running into the issue that others have reported when the photos stop changing after a short period of time -- probably less than 10 minutes. Thanks for all of the work you've put in. The app is quite user-friendly.

**Comment by mrworf** [comment]
Can you upload a log report from when that happens and I'll take a look. 

On December 31, 2019 11:23:28 AM PST, lmarino05 <notifications@github.com> wrote:
>I have an RPI4 and was able to get the software working after following
>your manual installation instructions. I'm running into the issue that
>others have reported when the photos stop changing after a short period
>of time -- probably less than 10 minutes. Thanks for all of the work
>you've put in. The app is quite user-friendly.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/mrworf/photoframe/issues/105#issuecomment-569978269

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by mrworf** [comment]
Closing this since I have no RPi4 to try on at the moment.
