### ISSUE TITLE
Turn off overscan?

### ISSUE THREAD

**Issue by fishfilet** [mrworf/photoframe#106]
Photos are showing up with a border or space between the photo and TV frame. There needs to be some way to turn off overscan.

**Comment by mrworf** [comment]
Yes, you can fix this, but you need to edit the `config.txt` file and try changing the following setting `disable_overscan` to 1 (so the line reads `disable_overscan=1`)

If you plug in the SD card in the computer, the `config.txt` file should be right there 😃 

Let me know how it works

**Comment by mrworf** [comment]
Should be solved by latest update which will automatically install within 24hrs, new options in web ui will allow changing of this setting

**Comment by mrworf** [comment]
Fixed, please reopen if not working for you after update
