### ISSUE TITLE
The photoframe is not working since a few days.

### ISSUE THREAD

**Issue by dancat** [mrworf/photoframe#107]
Since 2 or 3 days I have a problem with the photoframe. It continually shows the message that the internet connection is not available.
However, I can login via ssh (via wifi) to it and I can access with no problem sites from internet.
If I try to start the web interface I get the 'Problems loading /service/list from backend, please reload' message.
Restarting it did not helped, running 'update.sh' over ssh says 'No new version'.

Any hints what I can do to make it work again?

All the best,
Daniel

**Comment by mrworf** [comment]
Do you have a 2.5A power supply? I've experienced that the rpi will trash the SD card over time if not given enough power.

Also, if you can ssh in, please go to the /root/photoframe folder and issue git log and send me the first entry and we'll go from there. 

On August 3, 2019 10:42:49 AM PDT, Daniel Catalina <notifications@github.com> wrote:
>Since 2 or 3 days I have a problem with the photoframe. It continually
>shows the message that the internet connection is not available.
>However, I can login via ssh (via wifi) to it and I can access with no
>problem sites from internet.
>If I try to start the web interface I get the 'Problems loading
>/service/list from backend, please reload' message.
>Restarting it did not helped, running 'update.sh' over ssh says 'No new
>version'.
>
>Any hints what I can do to make it work again?
>
>All the best,
>Daniel
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/mrworf/photoframe/issues/107

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by dancat** [comment]
The power supply should be fine, it worked with no issues for almost one year already.

git log: commit 9dcea99c4b8230fbc61c290ca3b881adef5709a1

It could be that there is something fishy with the keywords used for google photos. If I am trying to run by hand the frame I get: 
root@photoframe:~/photoframe# /bin/bash /root/photoframe/photoframe.sh
Importing svc_usb.py
Importing svc_simpleurl.py
Importing svc_googlephotos.py
2019-08-03 20:51:54,881 - INFO - ColorSensor not available
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/root/photoframe/modules/slideshow.py", line 250, in presentation
    self.services.getServices(readyOnly=True)
  File "/root/photoframe/modules/servicemanager.py", line 330, in getServices
    'messages' : svc['service'].getMessages(),
  File "/root/photoframe/services/base.py", line 194, in getMessages
    'message': 'At least one keyword does not appear to provide any images! Please remove keyword(s) %s' % str([str(keyword) for keyword in self._STATE["_KEYWORDS"] if self._STATE["_NUM_IMAGES"][keyword] == 0]),
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf6' in position 14: ordinal not in range(128)

Where do I find the keywords to delete some of them?
Or this will not help?

**Comment by dancat** [comment]
Ok, so I found and deleted the configured services. After reconfiguration seems to work now. I still do not know what went wrong...

**Comment by mrworf** [comment]
Did you have any non a-z characters in the keyword? 

On August 3, 2019 1:43:21 PM PDT, Daniel Catalina <notifications@github.com> wrote:
>Ok, so I found and deleted the configured services. After
>reconfiguration seems to work now. I still do not know what went
>wrong...
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/mrworf/photoframe/issues/107#issuecomment-517953398

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by dancat** [comment]
I am not sure ... looking at the error message I would say there was something, it corresponds to a german 'o umlaut'

**Comment by dancat** [comment]
Since now it works, I say we can close the issue. If you want to check more let me know.
