### ISSUE TITLE
Frame does not display image when powering back on

### ISSUE THREAD

**Issue by chrisredrich** [mrworf/photoframe#110]
Thank you so much for this project. It's created a visually stunning statement piece in our living room. I have had many conversations with friends/family who visit.

My use case may be a little different than others. Instead of rotating images constantly throughout the day, I have configured photoframe to show a new image every day. So each morning we wake up to a new image from our album that we get to enjoy all day. As if someone came in and changed the family photo on our wall every night.

The issue I am having is that I have configured for the frame to turn on at 6am and turn off at 10pm. Every morning I have to login to the interface and click 'Next Image' to begin displaying an image that day. 

Any help would be greatly appreciated!

[debug.txt](https://github.com/mrworf/photoframe/files/3487203/debug.txt)

**Comment by mrworf** [comment]
That's a really cool way to use it.

But not good that you have to do that manually. What's the time limit 
for changing photos set to? And have you tried leaving it for two day or 
so to see if it changes?

**Comment by chrisredrich** [comment]
I’ve experimented with different settings, and have left it for a few days while away from home and it didn’t come back on. 

I have it set to come on at 6am and turn off at 10pm. That’s 16 hours, so I originally had it set to 57600 seconds. Then I tried 57601 wondering if having it set to the exact amount of time would create a conflict. Most recently I’ve set it to change 14400 to see if a shorter amount of time would help. When set to 14400, it rotates fine throughout the day but doesn’t seem to come back on in the morning.

**Comment by chrisredrich** [comment]
The last 2 days I did not login and manually click next image. At some point in the morning it turned back on. I am wondering if the first image is blank and on the next time it is set to rotate it fetches a new image.

**Comment by mrworf** [comment]
Good point. I'll have to look into that

**Comment by chrisredrich** [comment]
Things had been working fairly well by setting the image rotate time to 86,400 (24 hours). It seems that the “powered off” time is counted. By setting it to 24 hours, it rotates to a new image shortly after powering back on and thus displaying a new photo.

**Comment by mrworf** [comment]
Small update, whenever the frame turns back on, it always grabs a new photo, so by placing a timeout of 24hrs simply makes sure no new photo is shown during the time it's on. It should be blanking the screen on power off to support displays which cannot be power controlled (such as GPIO or SPI based ones).

I have seen the occasional glitch with the power off/on timekeeper which sometimes means it doesn't power on, so I'm working on figuring that one out, which is most likely the culprit that caused your display to remain blank.

**Comment by chrisredrich** [comment]
Thanks for the update. It’s odd, sometimes it works fine and comes back on for several days in a row. Then it stops and I have to login to hit next image. 

Thankful for your work. We get so many compliments on our photo frame.

**Comment by mrworf** [comment]
I might have found the reason which could relate to this, so in the coming days I should have an update on this issue. Glad to hear you're enjoying the frame. 

If you haven't already, feel free to add your frame to the [hall of fame](https://github.com/mrworf/photoframe/wiki) (see the side panel)

**Comment by mrworf** [comment]
I've done some more thinking and I believe I know what happens in your use-case (in particular). Long story short, long timers and no graceful handling of power causes problems. 

Currently running a 24hr test to make sure things still work for the more common use-case, when that has been confirmed, I'll merge and then we'll see if I'm right. This error is unfortunately not something I've been able to reproduce in "the lab" which is why I'm going about it in this fashion. 

I'll ping here as soon as the new version is out and we'll see if it solves your issue. 

Thanks for your patience

**Comment by chrisredrich** [comment]
Thank you for the update. I completely understand the need to isolate the variables. 

If it helps any, I’ve been doing some of the same thing. I’ve let the frame do its thing for the last week or so without manually advancing the image. It seems to come on every other day or so.

**Comment by mrworf** [comment]
I have news! I was able to reproduce the issue and since two nights ago I squished it. Merging change tonight 😸

**Comment by chrisredrich** [comment]
I can confirm this has been working the last two days. Thank you so much for continuing to track this down even though it is not the primary use case. It is much appreciated.

I will be sure to add to the hall of fame.
