### ISSUE TITLE
USB-Photos only works for filesystem in slice 1 of drive

### ISSUE THREAD

**Issue by dadr** [mrworf/photoframe#111]
USB-Photos works well when there is only one partition on the USB drive.  However, if the drive is partitioned on a Mac, then the Apple partition map occupies slice1 (e.g. SDA1) and the large partition with the filesystem is in partition 2 (e.g. SDA2).   It's fairly easy to work around this by avoiding apple partition maps, but other software doesn't seem to have the problem with mounting the correct partition.  For example, I tried installing usbmount.  (I know it is old and hasn't seen updates in years)  usbmount is an auto mounter, and works well to put the proper partition in /media/usbx.

**Comment by mrworf** [comment]
Should be solved by latest update which will automatically install within 24hrs

**Comment by mrworf** [comment]
Closing this issue. Please reopen if still an issue

**Comment by dadr** [comment]
I agee that this issue is resolved.   All the USB sticks are working fine now.
