### ISSUE TITLE
Images are not rotated according to EXIF data

### ISSUE THREAD

**Issue by dadr** [mrworf/photoframe#112]
(Sorry to identify so many issues, I hope I'm not being a pest)
When JPG files are sent to the photo frame that use EXIF with something other than normal orientation, they are not shown correctly.   I've attached an example.  This file, when shown from a USB drive, appears upside down.  There's more info on this, including some clues on how to use image magick to read the EXIF information here: https://sirv.com/help/resources/rotate-photos-to-be-upright/
(no endorsement on Sirv, I just thought they did a good job explaining.)
Thanks!
![IMG_4044](https://user-images.githubusercontent.com/6684314/62813008-7f1ebf80-bad6-11e9-869b-cee488ed1bd0.JPG)

**Comment by mrworf** [comment]
What's the source for this image? Meaning, is it located on Google Photos or USB stick? If it's google photos, can you make sure it shows OK on google photos website?

**Comment by dadr** [comment]
Hi Henric,  It's on a USB stick.  If I upload this to Google Photos, it shows upside down in the upload preview, but after uploading completes, it shows correctly both in the web browser and also in the photoframe.     I realize that just using Google Photos is a workaround, but my goal is to host the photos from a linux server on my home network.

**Comment by mrworf** [comment]
It should most certainly work from USB stick too, I just wanted to confirm that this was the method from which you're showing images :)

**Comment by dadr** [comment]
Thanks!  I've attached another example.  Both images are taken on iPhone, FWIW.
![IMG_2063](https://user-images.githubusercontent.com/6684314/62877905-09913a00-bcf6-11e9-8367-05f6cd66c539.JPG)

**Comment by dadr** [comment]
Pull Request #115 should fix this.  However,  I have not exhaustively tested - especially not with the Google Photos service.

**Comment by dadr** [comment]
I notice you have not incorporated pull request #117.   Are you thinking I applied the fix too broadly?   I could see an opinion that this fix (and the unicode file name fix) only apply to 
filesystems, and ought to be put into those individual services rather than slideshow.py.

**Comment by mrworf** [comment]
Honestly, I saw you comment about testing and figured I'd do that, but life and work came inbetween so I got delayed. You're right though, Image magick does get called a lot which isn't as efficient as one would like. I don't mind a broad generic solution as long as it doesn't affect anything else. Duplicating this in every service makes little sense.

**Comment by mrworf** [comment]
Should be solved by latest update which will automatically install within 24hrs. Uses another method to rotate which should be quicker

**Comment by mrworf** [comment]
Please let me know if this solves your issue

**Comment by dadr** [comment]
Got back from vacation last week.  Have been able to update my units to 9/30 version and am running through tests.   This is not an issue in the current version.

**Comment by dadr** [comment]
I think we can close this one again.
