### ISSUE TITLE
Inquiry:  Intended functions of Blur/Zoom pulldown

### ISSUE THREAD

**Issue by dadr** [mrworf/photoframe#113]
I'm trying to better understand the intended behavior of the image fitting options.   As near as a I can tell, the functions are as follows:

1) Do nothing: resizes image up or down to fit entire image within the display - leaving unused display space black.
2) Zoom to fill: resizes image up or down to fill the entire display - cropping the part of the image that would have extended beyond the display.
3) Show blurred image: resizes image up or down as in 1 - but adds border and blurred background.
4) Blur/Zoom as necessary: AFAIKT this does the same as 3.

The reason I'm asking, is that I see some images that fail to include the blur effect, even though I would have expected to see it.  I've attached an example of that.  (When shown on a 1920x1200 display)  ;-)

Secondly, I am wondering if the original intent for 3 was to avoid scaling up small images and creating blur on all 4 sides.  The attached image should do that too on that same large display.  If this was the originally intended function, then I could better understand the difference between 3 and 4.

After thinking about this last point, it made me wonder if 1 was also intended not to fill the screen, but that would then seem to leave a missing option to zoom without cropping.

Thanks and regards!
![crows](https://user-images.githubusercontent.com/6684314/63453716-4ad0ca80-c417-11e9-82e5-457b9bd1341b.jpg)

**Comment by dadr** [comment]
I made a suggestion that fixes the blur effect when the above is shown with option 3.  See pull request #98.  I'm still curious, however, about the other points.

**Comment by dadr** [comment]
After reading through the code - it seems like item 4 is intended to show a blurred image, unless the blurred portions would be really small (< 60px), and in that case, Do nothing.  

Seems there was not an intent to leave small pictures blurred on all 4 sides.

Let me know if I've skulled it out correctly.   Thanks!

**Comment by mrworf** [comment]
Yes, you're right. It didn't make sense to do it for small images. I know I was working on an improvement for this since the threshold really depends on the size of the frame and resolution.

Merged #98

**Comment by dadr** [comment]
Yep, agreed, rather than 60px, it might be better to use a percent of the screen resolution.

**Comment by mrworf** [comment]
Yes, but it still needs to be configurable due to differences in pixel density

**Comment by dadr** [comment]
Also, sorry, but #98 needed to be fixed, it was not my pull request to begin with, and I didn't want to steal it away from the other guy.  So my suggested fix was in my comments.   I can try to do a new pull request if you like.

**Comment by mrworf** [comment]
Ah, too quick on the draw, I was sure that was you. That's what I get for reading it on my phone. yes, if you don't mind doing a new PR with that fix, that would be great.

**Comment by dadr** [comment]
#114 fixed it.  Closing Issue
