### ISSUE TITLE
Non English letters in album name does not work.

### ISSUE THREAD

**Issue by Snille** [mrworf/photoframe#119]
Again, thank you for creating, maintaining and developing this!
It's really appreciated, not only by me but by my wife as well! :)

After last update I think the frame crashes if the (google) album name contains "åäöÅÄÖ" characters. Both my frames using "Fotoram Bibliotek och Kök" is not working any more.
I have tried a complete reinstall to start fresh. Still the same issue... 

Here is the service error message:
```
Sep 22 11:23:49 photoframe05 photoframe[536]:     state = svc.updateState()
Sep 22 11:23:49 photoframe05 photoframe[536]:   File "/root/photoframe/services/base.py", line 141, in updateState
Sep 22 11:23:49 photoframe05 photoframe[536]:     elif self.getNumImages() == 0:
Sep 22 11:23:49 photoframe05 photoframe[536]:   File "/root/photoframe/services/base.py", line 185, in getNumImages
Sep 22 11:23:49 photoframe05 photoframe[536]:     images = self.getImagesFor(keyword)
Sep 22 11:23:49 photoframe05 photoframe[536]:   File "/root/photoframe/services/svc_googlephotos.py", line 249, in getImagesFor
Sep 22 11:23:49 photoframe05 photoframe[536]:     filename = os.path.join(self.getStoragePath(), self.hashString(keyword) + '.json')
Sep 22 11:23:49 photoframe05 photoframe[536]:   File "/root/photoframe/services/base.py", line 630, in hashString
Sep 22 11:23:49 photoframe05 photoframe[536]:     return hashlib.sha1(text).hexdigest()
Sep 22 11:23:49 photoframe05 photoframe[536]: UnicodeEncodeError: 'ascii' codec can't encode character u'\xf6' in position 23: ordinal not in range(128)
```
My other two frames are working fine, album names being: "Fotoram Hall" and "Fotoram Louise". So I do think it's a character problem. :)

**Comment by mrworf** [comment]
Yes, you're right. Solved usb and broke Google. Thanks for letting me know. Next update will fix this.

Thanks for your patience 

On September 22, 2019 2:43:39 AM PDT, Erik Pettersson <notifications@github.com> wrote:
>Again, thank you for creating, maintaining and developing this!>
>It's really appreciated, not only by me but by my wife as well! :)>
>>
>After last update I think the frame crashes if the (google) album name
>contains "åäöÅÄÖ" characters. Both my frames using "Fotoram Bibliotek
>och Kök" is not working any more.>
>I have tried a complete reinstall to start fresh. Still the same
>issue... >
>>
>Here is the service error message:>
>```>
>Sep 22 11:23:49 photoframe05 photoframe[536]:     state =
>svc.updateState()>
>Sep 22 11:23:49 photoframe05 photoframe[536]:   File
>"/root/photoframe/services/base.py", line 141, in updateState>
>Sep 22 11:23:49 photoframe05 photoframe[536]:     elif
>self.getNumImages() == 0:>
>Sep 22 11:23:49 photoframe05 photoframe[536]:   File
>"/root/photoframe/services/base.py", line 185, in getNumImages>
>Sep 22 11:23:49 photoframe05 photoframe[536]:     images =
>self.getImagesFor(keyword)>
>Sep 22 11:23:49 photoframe05 photoframe[536]:   File
>"/root/photoframe/services/svc_googlephotos.py", line 249, in
>getImagesFor>
>Sep 22 11:23:49 photoframe05 photoframe[536]:     filename =
>os.path.join(self.getStoragePath(), self.hashString(keyword) +
>'.json')>
>Sep 22 11:23:49 photoframe05 photoframe[536]:   File
>"/root/photoframe/services/base.py", line 630, in hashString>
>Sep 22 11:23:49 photoframe05 photoframe[536]:     return
>hashlib.sha1(text).hexdigest()>
>Sep 22 11:23:49 photoframe05 photoframe[536]: UnicodeEncodeError:
>'ascii' codec can't encode character u'\xf6' in position 23: ordinal
>not in range(128)>
>```>
>My other two frames are working fine, album names being: "Fotoram Hall"
>and "Fotoram Louise". So I do think it's a character problem. :)>
>>
>>
>-- >
>You are receiving this because you are subscribed to this thread.>
>Reply to this email directly or view it on GitHub:>
>https://github.com/mrworf/photoframe/issues/119

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by mrworf** [comment]
Should work now, both USB and Google, please close issue if true 😄

**Comment by Snille** [comment]
Yepp, it's working again (with Google at least). Thank you! :)
