### ISSUE TITLE
Redirect to None:7777

### ISSUE THREAD

**Issue by nicdal15** [mrworf/photoframe#120]
My photoframe has been set up for around 10 months, but it stopped working a few days ago.  I think it might have gotten broken at the same time as your last update, but it might also be a coincidence.

The screen was showing a black screen and no way to log in from the former webbrowser address.  Tried switching screen, Raspberry PI, wires and SD card indivually, which pinpointed me to the issue being the program itself.  I tried reinstalling with the latest version of the photoframe program, and now the displayed instruction is to direct the webbrowser to http://None:7777/

Any idea what I can do to fix it?

Thanks

Nicolas

**Comment by mrworf** [comment]
None would indicate it's unable to deduce it's local IP. Is there any way for you to find out what IP it was assigned (checking your router or similar) ? Because I'd love to see the logs for this. The web server should still be running even if the software doesn't know the IP.

Until then, how is your Pi connected to the network? Maybe I could replicate the issue locally too.

**Comment by mrworf** [comment]
Also, if you could post an image of the message shown, trying to pinpoint where it might be stuck.

**Comment by nicdal15** [comment]
Your questions did lead me to interesting areas.  I did find the IP through my router, the number had changed and so I was able to access the Photoframe config.  

Considering I had reinstalled, I went through the GooglePhotos certification process again by uploading the json file from the API Dashboard, and updated the config with the right photoalbums.

However it seems to be back to square one, as the screen doesn't show the "None:7777' message anymore, but it's back to a black screen.  Tell me if you still require the image, considering we are not stuck at the same place anymore and that it is just a black screen for now after the initial boot countdown (this is also what we see through the config).

**Comment by mrworf** [comment]
No, image wouldn't be useful at this time 🙂 ... Can you use the "Log Report" button and attach the output from that to this issue. It will hopefully tell me what's wrong 😄

**Comment by nicdal15** [comment]
[debug.pdf](https://github.com/mrworf/photoframe/files/3643963/debug.pdf)

**Comment by mrworf** [comment]
Awesome, I know what's wrong now. You're missing a tool which should have been installed upon first run. 

Are you using the ready made image or did you install this manually?

To fix this issue, if you have SSH access, you can install the tool yourself by running
```
apt update
apt install -y libjpeg-turbo-progs
```
Otherwise, let me know and we'll figure it out.

**Comment by nicdal15** [comment]
Great news that you found the reason.

I ran the ready made image using Etcher.

We might have to figure out another way as I don't have access for command lines.

**Comment by mrworf** [comment]
Here's the neat thing with the latest version, you should be able to do the following,

tell you webbrowser to go to http://&lt;ip of frame&gt;:7777/maintenance/ssh ... This should yield a response saying something about ssh: true

Now, I don't know if you've ever used ssh before, if not, I'd recommend getting "PuTTY", it's a free and small ssh client. Use that to connect to the IP of your frame

Once connected, it will ask for username and password. These are the default ones used by all rasbian images, so it's "pi" and "raspberry" (this is why SSH isn't on by default)

When you have logged in, you should be able to run those 3 commands.  After they have executed without errors, type `reboot` and the frame will reboot (this also disables ssh again).

Let me know how it goes or if you get stuck or get errors.

**Comment by nicdal15** [comment]
Awesome, it worked out perfectly!

Thanks for being so helpful, this is the second time you've fixed one of my issues the same day I posted it, and this is really appreciated.

**Comment by mrworf** [comment]
No worries, thanks for letting me know what went wrong. Now I have homework to figure out how this happened 🐱

**Comment by rafik24** [comment]
This is a neat feature,

Really need to be documented!

Regards,
Rafik
