### ISSUE TITLE
Schedule does not seem to turn screen on at specified time

### ISSUE THREAD

**Issue by sboutros** [mrworf/photoframe#122]
It's 10:23AM here

![Screen Shot 2019-09-25 at 10 22 59 AM](https://user-images.githubusercontent.com/1707254/65609895-857dd380-df7e-11e9-859f-7bd4f57b6bfd.png)

**Comment by mrworf** [comment]
If you force an update, you'll get a fix for this. Otherwise it will roll out as usual with the daily update.
