### ISSUE TITLE
Simple URL Exception

### ISSUE THREAD

**Issue by sboutros** [mrworf/photoframe#124]
Latest commit and seeing this:

Sep 28 19:19:02 CybelePhotoframe photoframe[580]: 2019-09-28 19:19:02,429 - INFO - Registering URL /control/ to RouteControl
Sep 28 19:19:13 CybelePhotoframe photoframe[580]: 2019-09-28 19:19:13,732 - INFO - Starting presentation
Sep 28 19:19:15 CybelePhotoframe photoframe[580]: 2019-09-28 19:19:15,190 - INFO - Processing https://stage.inthrma.com/frame/?id=2
Sep 28 19:19:15 CybelePhotoframe photoframe[580]: Exception in thread Thread-5:
Sep 28 19:19:15 CybelePhotoframe photoframe[580]: Traceback (most recent call last):
Sep 28 19:19:15 CybelePhotoframe photoframe[580]:   File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
Sep 28 19:19:15 CybelePhotoframe photoframe[580]:     self.run()
Sep 28 19:19:15 CybelePhotoframe photoframe[580]:   File "/usr/lib/python2.7/threading.py", line 754, in run
Sep 28 19:19:15 CybelePhotoframe photoframe[580]:     self.__target(*self.__args, **self.__kwargs)
Sep 28 19:19:15 CybelePhotoframe photoframe[580]:   File "/root/photoframe/modules/slideshow.py", line 316, in presentation
Sep 28 19:19:15 CybelePhotoframe photoframe[580]:     filenameProcessed = self.process(result)
Sep 28 19:19:15 CybelePhotoframe photoframe[580]:   File "/root/photoframe/modules/slideshow.py", line 234, in process
Sep 28 19:19:15 CybelePhotoframe photoframe[580]:     filename = helper.autoRotate(filename)
Sep 28 19:19:15 CybelePhotoframe photoframe[580]:   File "/root/photoframe/modules/helper.py", line 344, in autoRotate
Sep 28 19:19:15 CybelePhotoframe photoframe[580]:     result = subprocess.check_output(['/usr/bin/jpegexiforient', ifile]) #, stderr=void)
Sep 28 19:19:15 CybelePhotoframe photoframe[580]:   File "/usr/lib/python2.7/subprocess.py", line 212, in check_output
Sep 28 19:19:15 CybelePhotoframe photoframe[580]:     process = Popen(stdout=PIPE, *popenargs, **kwargs)
Sep 28 19:19:15 CybelePhotoframe photoframe[580]:   File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
Sep 28 19:19:15 CybelePhotoframe photoframe[580]:     errread, errwrite)
Sep 28 19:19:15 CybelePhotoframe photoframe[580]:   File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child
Sep 28 19:19:15 CybelePhotoframe photoframe[580]:     raise child_exception
Sep 28 19:19:15 CybelePhotoframe photoframe[580]: OSError: [Errno 2] No such file or directory

**Comment by mrworf** [comment]
Sorry, will check tomorrow morning.

Thanks 

On September 28, 2019 4:22:13 PM PDT, sboutros <notifications@github.com> wrote:
>Latest commit and seeing this:
>
>Sep 28 19:19:02 CybelePhotoframe photoframe[580]: 2019-09-28
>19:19:02,429 - INFO - Registering URL /control/ to RouteControl
>Sep 28 19:19:13 CybelePhotoframe photoframe[580]: 2019-09-28
>19:19:13,732 - INFO - Starting presentation
>Sep 28 19:19:15 CybelePhotoframe photoframe[580]: 2019-09-28
>19:19:15,190 - INFO - Processing https://stage.inthrma.com/frame/?id=2
>Sep 28 19:19:15 CybelePhotoframe photoframe[580]: Exception in thread
>Thread-5:
>Sep 28 19:19:15 CybelePhotoframe photoframe[580]: Traceback (most
>recent call last):
>Sep 28 19:19:15 CybelePhotoframe photoframe[580]:   File
>"/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
>Sep 28 19:19:15 CybelePhotoframe photoframe[580]:     self.run()
>Sep 28 19:19:15 CybelePhotoframe photoframe[580]:   File
>"/usr/lib/python2.7/threading.py", line 754, in run
>Sep 28 19:19:15 CybelePhotoframe photoframe[580]:    
>self.__target(*self.__args, **self.__kwargs)
>Sep 28 19:19:15 CybelePhotoframe photoframe[580]:   File
>"/root/photoframe/modules/slideshow.py", line 316, in presentation
>Sep 28 19:19:15 CybelePhotoframe photoframe[580]:     filenameProcessed
>= self.process(result)
>Sep 28 19:19:15 CybelePhotoframe photoframe[580]:   File
>"/root/photoframe/modules/slideshow.py", line 234, in process
>Sep 28 19:19:15 CybelePhotoframe photoframe[580]:     filename =
>helper.autoRotate(filename)
>Sep 28 19:19:15 CybelePhotoframe photoframe[580]:   File
>"/root/photoframe/modules/helper.py", line 344, in autoRotate
>Sep 28 19:19:15 CybelePhotoframe photoframe[580]:     result =
>subprocess.check_output(['/usr/bin/jpegexiforient', ifile]) #,
>stderr=void)
>Sep 28 19:19:15 CybelePhotoframe photoframe[580]:   File
>"/usr/lib/python2.7/subprocess.py", line 212, in check_output
>Sep 28 19:19:15 CybelePhotoframe photoframe[580]:     process =
>Popen(stdout=PIPE, *popenargs, **kwargs)
>Sep 28 19:19:15 CybelePhotoframe photoframe[580]:   File
>"/usr/lib/python2.7/subprocess.py", line 390, in __init__
>Sep 28 19:19:15 CybelePhotoframe photoframe[580]:     errread,
>errwrite)
>Sep 28 19:19:15 CybelePhotoframe photoframe[580]:   File
>"/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child
>Sep 28 19:19:15 CybelePhotoframe photoframe[580]:     raise
>child_exception
>Sep 28 19:19:15 CybelePhotoframe photoframe[580]: OSError: [Errno 2] No
>such file or directory
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/mrworf/photoframe/issues/124

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by mrworf** [comment]
The update should solve it. BUT!

I have two questions:
1. Are you using the SD Card image (which allows auto update)
2. Can you check the log output for `jpegexiforient is missing` once you've updated?

I've noticed a couple of users having an issue where the tool needed to auto rotate wasn't installed during update and I'd like to see if that's the case for you too. 

If this error shows up, EXIF auto rotate won't work, but it's easy to fix. Let me know if that's the case and you need assistance.

**Comment by mrworf** [comment]
Closing this issue, please reopen if still a problem
