### ISSUE TITLE
URL for management shows wrong IP address

### ISSUE THREAD

**Issue by dadr** [mrworf/photoframe#126]
When there is an error (or initial unconfigured state) condition, the screen shows a message to please direct your browser to http://IPadddress:7777/    On both a 0w and 1B the IPaddress shown is not valid.   It shows an address that was correct in the past, but not anymore.  This holds true over reboots, where the pi keeps the new address, but the help screen shows the old one.  

The following is in the log.  And except for the first line that block is repeated 4 times

Oct  4 13:54:33 photopi0 photoframe[596]: 2019-10-04 13:54:33,755 - INFO - Starting presentation
Oct  4 13:58:53 photopi0 photoframe[596]: Traceback (most recent call last):
Oct  4 13:58:53 photopi0 photoframe[596]:   File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
Oct  4 13:58:53 photopi0 photoframe[596]:     self.process_request(request, client_address)
Oct  4 13:58:53 photopi0 photoframe[596]:   File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
Oct  4 13:58:53 photopi0 photoframe[596]:     self.finish_request(request, client_address)
Oct  4 13:58:53 photopi0 photoframe[596]:   File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
Oct  4 13:58:53 photopi0 photoframe[596]:     self.RequestHandlerClass(request, client_address, self)
Oct  4 13:58:53 photopi0 photoframe[596]:   File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
Oct  4 13:58:53 photopi0 photoframe[596]:     self.finish()
Oct  4 13:58:53 photopi0 photoframe[596]:   File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
Oct  4 13:58:53 photopi0 photoframe[596]:     self.wfile.close()
Oct  4 13:58:53 photopi0 photoframe[596]:   File "/usr/lib/python2.7/socket.py", line 283, in close
Oct  4 13:58:53 photopi0 photoframe[596]:     self.flush()
Oct  4 13:58:53 photopi0 photoframe[596]:   File "/usr/lib/python2.7/socket.py", line 307, in flush
Oct  4 13:58:53 photopi0 photoframe[596]:     self._sock.sendall(view[write_offset:write_offset+buffer_size])
Oct  4 13:58:53 photopi0 photoframe[596]: error: [Errno 32] Broken pipe

**Comment by mrworf** [comment]
Any chance you are comfortable with SSH ? Would love to see what `ifconfig` says on your system

**Comment by mrworf** [comment]
The way I detect your IP is by preparing a connection to photoframe.sensenet.nu since it will show the real IP used for network connections (in case you have multiple network devices). It doesn't sound like it works reliably on your device so I'll go back to the drawing board and see if there are other means.

**Comment by dadr** [comment]
The URL on the screen is for http://192.168.1.33:7777/   
if config is:
pi@photopi0:~ $ ifconfig
lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wlan0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.12  netmask 255.255.255.0  broadcast 192.168.1.255
        inet6 2600:1700:8750:6530:632b:9aa7:70c4:d603  prefixlen 64  scopeid 0x0<global>
        inet6 fe80::9261:1cfa:922b:1017  prefixlen 64  scopeid 0x20<link>
        ether b8:27:eb:18:b3:ce  txqueuelen 1000  (Ethernet)
        RX packets 12102  bytes 1531197 (1.4 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 3686  bytes 2230702 (2.1 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

This is not about the public, external IP address - rather the local private address for the management web server.   How would sensenet.nu come into play when no services have been added, or only USB has been added?

**Comment by mrworf** [comment]
https://github.com/mrworf/photoframe/blob/master/modules/helper.py#L65

By connecting, the linux host has to resolve routing and provide the IP used for network connectivity. It was an easy way to deal with both WiFi and LAN, but obviously not foolproof 😅

**Comment by dadr** [comment]
OK, I had a look at your code and as long as photoframe.sensenet.nu is reachable, that should provide the local IP.   However if I try to ping photoframe.sensenet.nu I'm not getting replies. Tried both on the Pi and on my PC.   Maybe the service is down today?  Maybe it filters pings?

**Comment by mrworf** [comment]
It filters ping :) http://photoframe.sensenet.nu  will take you to the default site (slack registration) and https:// version takes you to the redirect service (and without the right arguments, redirects to github project).

But! I have been digging a bit, and I found a better way of doing things which I will try when I get home. If it works, it will utilize avahi and not only work better for IP detection but it should also support using the .local TLD (so photoframe.local should work, or whatever you change the hostname to).

So stay tuned! 😄

**Comment by mrworf** [comment]
this also avoids the need for an internet connection for configuration page to work, which is great for USB based frames.

**Comment by dadr** [comment]
I use avahi and photopi0.local works for me.  But beware, /etc/default/avahi-daemon needs to be edited to set AVAHI_DAEMON_DETECT_LOCAL=0 for me and many home users.   Long story, but typical avahi does a unicast lookup on .local and if that responds it shuts down.  IF you have a home router with DNS cache or other goodies, they very often return the upstream DNS server for all domains, including .local.   That wrecks avahi.

**Comment by mrworf** [comment]
That's really good to know. Thanks :)

**Comment by mrworf** [comment]
Any drawbacks by ignoring that behavior?

**Comment by dadr** [comment]
It was put in (I think) to handle small business that use Microsoft Small Business Server.   It's a cookie-cutter small biz product that breaks the RFC and uses .local as the unicast DNS domain.  In general, if you are using .local as a unicast DNS, then mDNS with that same domain will cause all sorts of strange behavior.

**Comment by mrworf** [comment]
I'm just curious since you had to make that change

**Comment by dadr** [comment]
If you do not zero that flag, then the avahi daemon will exit after an address refresh, and will stop responding to photoframe.local.    The behavior I saw was that it worked initially, but eventually stopped working - I think because of race between interface coming up and the daemon starting.  Works rock solid with the flag zeroed out.

**Comment by mrworf** [comment]
Awesome, thx for the info. Will be experimenting with that tonight. Should hopefully have it working fairly soon.

**Comment by dadr** [comment]
One last comment.  If `dig local` returns an authority (or anything) then you need the flag zeroed.  If it does not, then leaving the flag alone is OK.   dig is not on the Pi by default.

**Comment by mrworf** [comment]
Turns out this was a bigger issue than I thought. I now properly distinguish between network availability and device ip. I also restart the avahi daemon on hostname change since it makes sense.

I decided not to mess with avahi anymore than that. IP should show now as expected.

**Comment by dadr** [comment]
I'm wondering if something else is going on?   My Pi 0 updated to the new version, but the behavior did not change.  With no photo providers, it shows an IP address, and it's the wrong one.  Could it be that some stored state data never updated from the big software update last week?   I've attached the logs again.  They show an initial boot up and update, and then a reboot (in case that was needed).   

[Untitled.pdf](https://github.com/mrworf/photoframe/files/3702368/Untitled.pdf)

**Comment by mrworf** [comment]
Two things, this rpi hasn't updated to the latest version yet (it's showing the commit from before last night's update) which has the ip detection fix. It might have missed that depending on when it checked. The other thing is that it seems to be clearing out old items in the cache. 

On October 8, 2019 5:40:42 AM PDT, Tom Anschutz <notifications@github.com> wrote:
>I'm wondering if something else is going on?   My Pi 0 updated to the
>new version, but the behavior did not change.  With no photo providers,
>it shows an IP address, and it's the wrong one.  Could it be that some
>stored state data never updated from the big software update last week?
>I've attached the logs again.  They show an initial boot up and update,
>and then a reboot (in case that was needed).   
>
>[Untitled.pdf](https://github.com/mrworf/photoframe/files/3702368/Untitled.pdf)
>
>
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/mrworf/photoframe/issues/126#issuecomment-539493585

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by dadr** [comment]
Oops, with red face.   That was my bad.  Force update did it.  I see the proper IP at the bottom of the screen (again) as well as on the not ready yet screen.   Thanks!
