### ISSUE TITLE
frame.py needs to set it's "home" directory once started

### ISSUE THREAD

**Issue by dadr** [mrworf/photoframe#127]
Following instructions to get more debug details from the README.md

> What if I want more logs?
> 
> If you're having issues and you want more details, do the following as root:
> 
> `service frame stop`
>` /root/photoframe/frame.py --debug`
> This will cause photoframe to run in the foreground and provide tons of debug information

using `sudo /root/photoframe/frame.py --debug`  does not run, with results as shown below   

```
pi@photopi0:~ $ sudo /root/photoframe/frame.py --debug
Traceback (most recent call last):
  File "/root/photoframe/frame.py", line 168, in <module>
    frame = Photoframe(cmdline)
  File "/root/photoframe/frame.py", line 72, in __init__
    self.serviceMgr = ServiceManager(self.settingsMgr, self.cacheMgr)
  File "/root/photoframe/modules/servicemanager.py", line 56, in __init__
    self._detectServices()
  File "/root/photoframe/modules/servicemanager.py", line 69, in _detectServices
    for item in os.listdir('services'):
OSError: [Errno 2] No such file or directory: 'services'
```

A workaround is to sudo sh (because only root can cd to /root)
then cd /root/photoframe
then ./frame.py --debug

**Comment by mrworf** [comment]
Changes working directory as of next update
