### ISSUE TITLE
IP not showing, only http://NULL:7777 on screen at first boot...

### ISSUE THREAD

**Issue by Snille** [mrworf/photoframe#128]
Hi, it's me again...
I'v just installed two new frames. :) However, I noticed that the IP does not show up on the "First screen" after start. It's not a huge problem. It's easy enough to find the IP in the DHCP... :)
![image](https://user-images.githubusercontent.com/1011699/66341028-b4188880-e946-11e9-8df0-5667dbf16d28.png)
But it has clearly got the IP,  as you can see from the webui... :)
![image](https://user-images.githubusercontent.com/1011699/66341138-ed50f880-e946-11e9-83e2-08281518d288.png)

Again, thank you for your work on this!

Best regards Erik

**Comment by mrworf** [comment]
So I have a new version ready, I just need to verify the fix tonight on my own RPi before pushing it out.

It uses netifaces (which will be installed by the update script), and looks like this:
```
        @staticmethod
        def getIP():
                try:
                        import netifaces
                        if 'default' in netifaces.gateways() and netifaces.AF_INET in netifaces.gateways()['default']:
                                dev = netifaces.gateways()['default'][netifaces.AF_INET][1]
                                if netifaces.ifaddresses(dev) and netifaces.AF_INET in netifaces.ifaddresses(dev):
                                        net = netifaces.ifaddresses(dev)[netifaces.AF_INET]
                                        if len(net) > 0 and 'addr' in net[0]:
                                                return net[0]['addr']
                except ImportError:
                        logging.error('User has not installed python-netifaces, reverting to old getIP()')
                        return helper._old_getIP()
                except:
                        logging.exception('netifaces call failed, reverting to old getIP()')
                        return helper._old_getIP()
```

**Comment by mrworf** [comment]
Also, if you want to share anything from your new build, that's always appreciated as inspiration for others 😄

**Comment by mrworf** [comment]
Fixed, if you update now, it will work

**Comment by Snille** [comment]
> Also, if you want to share anything from your new build, that's always appreciated as inspiration for others 😄

Gladly, where do you "want" it? It's the least I can do. :)

**Comment by mrworf** [comment]
Please create a new page on the wiki here on git hub and add it to the sidebar amongst the others 😁

Thanks 

On October 7, 2019 10:18:38 PM PDT, Erik Pettersson <notifications@github.com> wrote:
>> Also, if you want to share anything from your new build, that's
>always appreciated as inspiration for others 😄>
>>
>Gladly, where do you "want" it? It's the least I can do. :)>
>>
>-- >
>You are receiving this because you modified the open/close state.>
>Reply to this email directly or view it on GitHub:>
>https://github.com/mrworf/photoframe/issues/128#issuecomment-539330282

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Snille** [comment]
> Please create a new page on the wiki here on git hub and add it to the sidebar amongst the others 😁 Thanks
> […](#)
> On October 7, 2019 10:18:38 PM PDT, Erik Pettersson ***@***.***> wrote: > Also, if you want to share anything from your new build, that's always appreciated as inspiration for others 😄> > Gladly, where do you "want" it? It's the least I can do. :)> > -- > You are receiving this because you modified the open/close state.> Reply to this email directly or view it on GitHub:> [#128 (comment)](https://github.com/mrworf/photoframe/issues/128#issuecomment-539330282)
> -- Sent from my Android device with K-9 Mail. Please excuse my brevity.

I have a page there already (Snilles DPF v2.0), but I can make another one if you want. I have taken pictures and made a Google Album anyway. :)

**Comment by mrworf** [comment]
Ahh, well, the more setups the better :)

**Comment by Snille** [comment]
Done. It's a simple on, But the pictures are pretty self explanatory. :)
https://github.com/mrworf/photoframe/wiki/Snilles-Digital-Photo-Frame-v2.0---X2-Remake

**Comment by aaron-saks** [comment]
Has a new build been released so I can download and install fresh, or do I need to use the update button to force a refresh?

**Comment by mrworf** [comment]
It will auto update every night so it should be running latest. Otherwise do the force update
