### ISSUE TITLE
Version number in Webui

### ISSUE THREAD

**Issue by Snille** [mrworf/photoframe#131]
A nice to have feature, would be a way to easily tell what "version" the frame code is at.
I know it updates by itself, but sometimes I find myself wondering if all my frames are at the same "version" of the code. So, I was thinking, why not just add a "version-string", can be anything (bild-number from git or whatever is unique) both from the current installed "code" and from git (latest version), then you could easily see that an update is needed and at the same time you can verify that the frames are indeed running the same version... :)

Best regards Erik

**Comment by mrworf** [comment]
Actually, there's already a way to do that, I just never found a good way to expose it in a way that makes sense.

Try surfing to `http://your.frame:7777/details/version`  and you'll see something like:

```
{
  "branch": "updatemsg", 
  "commit": "f4351ff1864908b2eb423cdeeda076b1e96b3638", 
  "date": "Tue Oct 8 09:16:33 2019 -0700"
}
```
This is the branch and the commit you're at. This will get you partially there, but not quite.

Will keep this issue open so I don't forget about this

**Comment by Snille** [comment]
Ah, good, that gives an easy way to compare the frames at least. :)

**Comment by mrworf** [comment]
The check for update button now lets you know if you're on latest or not and even shows version details when on latest. I was hoping this would be good enough to close this issue?

**Comment by Snille** [comment]
Yes! That's great! Thank you! I'm all happy! :)
