### ISSUE TITLE
Keywords don't provide any photos. No matter what.

### ISSUE THREAD

**Issue by Hariseldon2** [mrworf/photoframe#134]
I try _latest_ just like you suggest and all I get is 

> At least one keyword does not appear to provide any images! Please remove keyword(s): latest

I try album names and I get: 

> Failed to add keyword 

even though I have the right album name

I

**Comment by mrworf** [comment]
I assume you're using "GooglePhotos" as the photo provider? 

This sounds very strange, can you use the "Log Report" button and upload the output from that to this issue so I can see what's going on?

**Comment by Hariseldon2** [comment]
I ended up deleting the credentials and creating new ones and now it works. I must've messed the api somehow. Sorry for not providing an update earlier and wasting your time.

**Comment by mrworf** [comment]
No worries, glad it worked out :)
