### ISSUE TITLE
Crash dump on screen - frozen image

### ISSUE THREAD

**Issue by aaron-saks** [mrworf/photoframe#135]
I have a new display running on a Raspberry Pi Zero W.  I downloaded the pre-build image.  Within 1 day, it will lock up and display text on screen as shown.  If I reboot, it works fine for many more hours.

![image](https://user-images.githubusercontent.com/56736436/67114135-3572e500-f1a9-11e9-8109-cc97a5da38b6.png)

I was also having an issue where the IP address wasn't displayed correctly on the startup screen. I'll force an update and see if that is fixed.

**Comment by mrworf** [comment]
The image is a bit low res to see what's going on, but typically the software will not cause a kernel panic (ie, the crash you see). Any chance you can provide a hi-res version of that picture so it's easier to see what the crash was about?

**Comment by aaron-saks** [comment]
Here is a high resolution picture.
Attached is the logs from the web UI.
[Photoframe.PDF](https://github.com/mrworf/photoframe/files/3745171/Photoframe.PDF)

![image](https://user-images.githubusercontent.com/56736436/67117425-aa95e880-f1b0-11e9-9168-5961f80204d6.png)

**Comment by mrworf** [comment]
Looking at the screenshot, the memory seems to have been corrupted? Looking at the logs, the bluetooth driver crashed the kernel. Both of these seem unrelated to photoframe. I'd try reloading the SD Card and make sure you provide enough power to the RPi. This is especially important if anything else is plugged into the device.

**Comment by jmhammond** [comment]
I've had the same problem happen twice with mine (yesterday was the most recent). When it occurs, you can't connect to it, even via ssh. Next time it happens I'll try to find the logs after hard resetting it.

**Comment by mrworf** [comment]
It's a hardware or driver issue, your RPi is crashing hard which is unusual for Linux. How did you install the software, did you use Etcher? Do you have another SD Card to try with ?

**Comment by aaron-saks** [comment]
I used a different windows SD card utility. Not etcher but something
similar. I'll tried a known good high end power supply and it still
crashed. I'll re do the inage on another SD card and a different pi zero w
and let it run for another day..

**Comment by mrworf** [comment]
Any updates?

**Comment by aaron-saks** [comment]
I also changed the time to 60 seconds.  It was at 10 seconds to rotate
through the images....
Today it seemed to stop fetching new images, but I noticed there was an
update.  I performed the update and now let it run over the weekend and see
if it is stable.

**Comment by mrworf** [comment]
Stopping to fetch images would not be the same error since you were getting kernel panics, so that's actually a promising development. It's less than ideal that it froze, but at least it's something I can fix 😄

**Comment by mrworf** [comment]
@aaron-saks any updates?

**Comment by aaron-saks** [comment]
I have not had any more crash dumps. Thank you very much. I have had it
stop updating and cycling thorough old. Pics, but I see others have
mentioned this in another thread, so I'll keep and eye on that. The forget
memory button forces it to reconnect and then it is good..

**Comment by mrworf** [comment]
Can we close this crash issue for now and then if something bad happens you open a new one? (since the issue with updates is different than this original one) ?

**Comment by aaron-saks** [comment]
Yes, that is great.
