### ISSUE TITLE
If possible, give link to current image from Google Photos

### ISSUE THREAD

**Issue by mrworf** [mrworf/photoframe#14]
In some cases, the photo shown will be one which you might want to 

a) Download
b) Edit
c) Delete

Right now, there is no way of finding the photo shown on the frame, adding a link should be trivial

**Comment by mrworf** [comment]
Supported by new integration but UX doesn't implement this yet. Also, new Google photos API doesn't seem to have an obvious way to map it. Closing this issue for now.

**Comment by rafik24** [comment]
Hi Mrworf,

I noticed in the http json headers there is a filename which refers to the filename of the picture on google photo portal.

making a search on the name bring up the picture, so this might be the low hanging fruit to refer to a picture for now.

Could well have this at the bottom of the picture, the only issue is that some picture will have the same color as the overlayed filename text which might make it unusable in some few cases.

**Comment by mrworf** [comment]
The goal was actually to provide this via the web ui and not clutter the display with this. The new provider API already supports exposing this, I just haven't added the link needed.
