### ISSUE TITLE
Fatal Error/WARNING - unsupported mimetype 'inode/x-empty'

### ISSUE THREAD

**Issue by sboutros** [mrworf/photoframe#140]
Getting this on occasion - any way to make it less fatal?
Frame gets stuck on image and does not advance till reboot.

Nov  7 13:10:00 photoframe photoframe[608]: 2019-11-07 13:10:00,623 - INFO - Photoframe's memory was reset. Already displayed images will be shown again!
Nov  7 13:10:00 photoframe photoframe[608]: 2019-11-07 13:10:00,811 - WARNING - unsupported mimetype 'inode/x-empty'. You should remove '.../?id=1' from keywords
Nov  7 13:10:00 photoframe photoframe[608]: Exception in thread Thread-5:
Nov  7 13:10:00 photoframe photoframe[608]: Traceback (most recent call last):
Nov  7 13:10:00 photoframe photoframe[608]:   File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
Nov  7 13:10:00 photoframe photoframe[608]:     self.run()
Nov  7 13:10:00 photoframe photoframe[608]:   File "/usr/lib/python2.7/threading.py", line 754, in run
Nov  7 13:10:00 photoframe photoframe[608]:     self.__target(*self.__args, **self.__kwargs)
Nov  7 13:10:00 photoframe photoframe[608]:   File "/root/photoframe/modules/slideshow.py", line 310, in presentation
Nov  7 13:10:00 photoframe photoframe[608]:     result = self.services.servicePrepareNextItem(self.settings.get('tempfolder'), self.supportedFormats, displaySize, randomize)
Nov  7 13:10:00 photoframe photoframe[608]:   File "/root/photoframe/modules/servicemanager.py", line 427, in servicePrepareNextItem
Nov  7 13:10:00 photoframe photoframe[608]:     result = svc.prepareNextItem(destinationDir, supportedMimeTypes, displaySize, randomize)
Nov  7 13:10:00 photoframe photoframe[608]:   File "/root/photoframe/services/base.py", line 415, in prepareNextItem
Nov  7 13:10:00 photoframe photoframe[608]:     result = self.selectImageFromAlbum(destinationFile, supportedMimeTypes, displaySize, randomize)
Nov  7 13:10:00 photoframe photoframe[608]:   File "/root/photoframe/services/svc_simpleurl.py", line 78, in selectImageFromAlbum
Nov  7 13:10:00 photoframe photoframe[608]:     self.brokenUrls.append(result["source"])
Nov  7 13:10:00 photoframe photoframe[608]: AttributeError: ImageHolder instance has no attribute '__getitem__'

**Comment by mrworf** [comment]
This is clearly a bug, will fix.

**Comment by mrworf** [comment]
Fixed, next update will not cause a fatal crash

**Comment by sboutros** [comment]
Great, thanks!
Graceful logging and error message on the display.
Issue is that it gets stuck and does not try again. Any way to allow it to try again at the next interval?


Nov 11 11:54:30 photoframe photoframe[538]: 2019-11-11 11:54:30,357 - WARNING - unsupported mimetype 'inode/x-empty'. You should remove '.../?id=1' from keywords
Nov 11 11:54:30 photoframe photoframe[538]: 2019-11-11 11:54:30,358 - ERROR - Service returned: No (new) images could be found

**Comment by mrworf** [comment]
I see... hmm... I actually had a fix for this since you're able to get to this point when modifying a google photos album. I never merged that, but I could which would allow services to periodically refresh when no photos are found. 

The logic is fairly simple, whenever a provider has no photos, a refresh is scheduled for 1hr later, but we could set this one to hammer on simple url.

However, you may want to consider fixing your PHP script too 😉 see https://stackoverflow.com/questions/24015038/why-does-php-file-info-return-inode-x-empty-for-empty-text-files
