### ISSUE TITLE
open wifi configuration

### ISSUE THREAD

**Issue by dereckperkins** [mrworf/photoframe#144]
trying to connect to an open wifi for updating photos. need to know how to set up the wifi-config.txt

**Comment by mrworf** [comment]
Try replacing the `wpa-psk` line with the following:
```
wpa-auth-alg open
```

And see if that resolves the issue.

**Comment by dereckperkins** [comment]
thanks unfortunately  that didn't fix my issue.

**Comment by mrworf** [comment]
What's the content of your wifi-config.txt file at this point (you can blank out the name of your wifi) ?

**Comment by dereckperkins** [comment]
I've tried a few different configurations

iface wlan0 inet dhcp
  wpa-ssid "Impresson5"
  wpa-auth-alg open

iface wlan0 inet dhcp
  ssid "Impresson5"
  key_mgmt=NONE

I have managed to have it connected to a different router  with a
password but connection to that is spotty and nearly impossible  to edit
the settings

**Comment by raja130** [comment]
Any updates on this issue for how to setup for an open wifi connection.

**Comment by chewston** [comment]
I am trying to setup multiple wifi's in case I need to move the frame from one location to another but I may have messed up overwriting a specific line of code in /etc/network/interfaces:

http://www.geothread.net/multiple-wifi-networks-with-a-raspberry-pi/

What was the original line that points to the wifi-config.txt, in side of the interfaces file.

**Comment by P43082** [comment]
Here is the original interfaces file contents:
`auto lo
iface lo inet loopback

#auto eth0
#iface eth0 inet dhcp

allow-hotplug wlan0
auto wlan0

source /boot/wifi-config.txt`

**Comment by mrworf** [comment]
If you check out https://github.com/mrworf/photoframe/wiki/Frequently-Asked-Questions#you-want-to-setup-multiple-wifi-access-points-aka-setting-up-a-frame-to-surprise-your-in-laws but instead of setting up 2x wifi's, use the following network instead:

```
network={
	ssid="no-password-wifi"
	key_mgmt=NONE
}
```
Where `no-password-wifi` should be whatever the SSID is for your open wifi network.

**Comment by mrworf** [comment]
I'm assuming this was resolved and closing the ticket
