### ISSUE TITLE
JSON file wont upload, tried multiple browsers. for google photos.

### ISSUE THREAD

**Issue by rockrdr** [mrworf/photoframe#145]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/photoframe/routes/baseroute.py", line 62, in __call__
    return self.handle(self.app, **kwargs)
  File "/root/photoframe/routes/oauthlink.py", line 44, in handle
    return self.redirect(self.servicemgr.oauthStart(kwargs['service']))
  File "/root/photoframe/modules/servicemanager.py", line 190, in oauthStart
    return svc.startOAuth()
  File "/root/photoframe/services/base.py", line 262, in startOAuth
    return self._OAUTH.initiate()
  File "/root/photoframe/modules/oauth.py", line 119, in initiate
    self.rid = self.getRedirectId()
  File "/root/photoframe/modules/oauth.py", line 115, in getRedirectId
    r = requests.get('%s/?register' % self.ridURI)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 497, in send
    raise SSLError(e, request=request)
SSLError: ("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",)

**Comment by mrworf** [comment]
This would indicate that for some reason your RPi cannot verify the certificate for SSL. Did you install the SD image? Can you check if there's a newer version of the frame available?

**Comment by rockrdr** [comment]
I installed the newest version from the site yesterday, from image. I did do a update check once it came up, nothing found.

**Comment by rockrdr** [comment]
![image](https://user-images.githubusercontent.com/8731362/69740156-2bbc9580-10f6-11ea-9dcb-717b76cefe81.png)

**Comment by mrworf** [comment]
Can you try opening https://photoframe.sensenet.nu/?register=234234 from your web browser? Should give you a hash if it works

**Comment by rockrdr** [comment]
![image](https://user-images.githubusercontent.com/8731362/69741314-147ea780-10f8-11ea-81fc-1b7920ea45c7.png)

works..

**Comment by mrworf** [comment]
Hmm... okay, are you familiar with SSH? If you are, you can enable SSH by surfing to `/maintenance/ssh` and then logon using standard RPi login (pi / rasberry). From there on, please try the following commands:

Make sure we have the right time/date
```
date
```

Next, use wget to try the same URL again:
```
wget -O - https://photoframe.sensenet.nu/?register=234234
```
This should give a similar output as the webbrowser.

Please post all output here 😄

**Comment by rockrdr** [comment]
error im getting now..
Error: redirect_uri_mismatch

The redirect URI in the request, https://photoframe.sensenet.nu, does not match the ones authorized for the OAuth client. To update the authorized redirect URIs, visit: https://console.developers.google.com/apis/credentials/oauthclient/249509516012-ie59c0cf48imstarld4aab9u1nagk7b4.apps.googleusercontent.com?project=249509516012
 I'm getting output now to post.

**Comment by rockrdr** [comment]
Nov 27 14:48:59 photoframe bluetoothd[451]: Failed to set privacy: Rejected (0x0b)
Nov 27 14:48:59 photoframe dbus[344]: [system] Successfully activated service 'org.freedesktop.hostname1'
Nov 27 14:48:59 photoframe systemd[1]: Started Hostname Service.
Nov 27 14:49:01 photoframe dhclient[424]: DHCPDISCOVER on wlan0 to 255.255.255.255 port 67 interval 11
Nov 27 14:49:01 photoframe sh[271]: DHCPDISCOVER on wlan0 to 255.255.255.255 port 67 interval 11
Nov 27 14:49:01 photoframe dhclient[424]: DHCPREQUEST of 192.168.1.81 on wlan0 to 255.255.255.255 port 67
Nov 27 14:49:01 photoframe dhclient[424]: DHCPOFFER of 192.168.1.81 from 192.168.1.1
Nov 27 14:49:01 photoframe sh[271]: DHCPREQUEST of 192.168.1.81 on wlan0 to 255.255.255.255 port 67
Nov 27 14:49:01 photoframe sh[271]: DHCPOFFER of 192.168.1.81 from 192.168.1.1
Nov 27 14:49:01 photoframe sh[271]: DHCPACK of 192.168.1.81 from 192.168.1.1
Nov 27 14:49:01 photoframe dhclient[424]: DHCPACK of 192.168.1.81 from 192.168.1.1
Nov 27 14:49:01 photoframe avahi-daemon[339]: Joining mDNS multicast group on interface wlan0.IPv4 with address 192.168.1.81.
Nov 27 14:49:01 photoframe avahi-daemon[339]: New relevant interface wlan0.IPv4 for mDNS.
Nov 27 14:49:01 photoframe avahi-daemon[339]: Registering new address record for 192.168.1.81 on wlan0.IPv4.
Nov 27 14:49:02 photoframe dhcpcd[360]: wlan0: leased 192.168.1.81 for 86400 seconds
Nov 27 14:49:02 photoframe dhcpcd[360]: wlan0: adding route to 192.168.1.0/24
Nov 27 14:49:02 photoframe dhcpcd[360]: wlan0: adding default route via 192.168.1.1
Nov 27 14:49:02 photoframe dhclient[424]: bound to 192.168.1.81 -- renewal in 38557 seconds.
Nov 27 14:49:02 photoframe sh[271]: bound to 192.168.1.81 -- renewal in 38557 seconds.
Nov 27 14:49:02 photoframe sh[271]: wlan0=wlan0
Nov 27 14:49:02 photoframe systemd[1]: Started Raise network interfaces.
Nov 27 14:49:02 photoframe systemd[1]: Reached target Network.
Nov 27 14:49:02 photoframe systemd[1]: Starting OpenBSD Secure Shell server...
Nov 27 14:49:02 photoframe systemd[1]: Starting Permit User Sessions...
Nov 27 14:49:02 photoframe systemd[1]: Starting /etc/rc.local Compatibility...
Nov 27 14:49:02 photoframe systemd[1]: Started Photo Frame.
Nov 27 14:49:02 photoframe systemd[1]: Started Permit User Sessions.
Nov 27 14:49:02 photoframe systemd[1]: Started /etc/rc.local Compatibility.
Nov 27 14:49:02 photoframe systemd[1]: Starting Hold until boot process finishes up...
Nov 27 14:49:02 photoframe systemd[1]: Starting Terminate Plymouth Boot Screen...
Nov 27 14:49:02 photoframe systemd[1]: Started Hold until boot process finishes up.
Nov 27 14:49:02 photoframe systemd[1]: Started Terminate Plymouth Boot Screen.
Nov 27 14:49:03 photoframe systemd[1]: Started OpenBSD Secure Shell server.
Nov 27 14:49:03 photoframe systemd[1]: Reached target Multi-User System.
Nov 27 14:49:03 photoframe systemd[1]: Reached target Graphical Interface.
Nov 27 14:49:03 photoframe systemd[1]: Starting Update UTMP about System Runlevel Changes...
Nov 27 14:49:03 photoframe systemd[1]: Started Update UTMP about System Runlevel Changes.
Nov 27 14:49:03 photoframe systemd[1]: Startup finished in 1.833s (kernel) + 12.616s (userspace) = 14.450s.
Nov 27 14:49:06 photoframe photoframe[606]: 2019-11-27 14:49:06,157 - INFO - Loading service USB_Photos from svc_usb.py
Nov 27 14:49:06 photoframe photoframe[606]: 2019-11-27 14:49:06,164 - INFO - Loading service PicasaWeb from svc_picasaweb.py
Nov 27 14:49:06 photoframe photoframe[606]: 2019-11-27 14:49:06,188 - INFO - Loading service GooglePhotos from svc_googlephotos.py
Nov 27 14:49:06 photoframe photoframe[606]: 2019-11-27 14:49:06,194 - INFO - Loading service SimpleUrl from svc_simpleurl.py
Nov 27 14:49:06 photoframe photoframe[606]: 2019-11-27 14:49:06,202 - INFO - ColorSensor not available
Nov 27 14:49:06 photoframe photoframe[606]: 2019-11-27 14:49:06,206 - INFO - GPIO shutdown can be triggered by GPIO 3
Nov 27 14:49:06 photoframe photoframe[606]: 2019-11-27 14:49:06,213 - INFO - Cache is set to %sTrue
Nov 27 14:49:06 photoframe photoframe[606]: 2019-11-27 14:49:06,223 - INFO - No http-auth.json found, disabling http authentication
Nov 27 14:49:06 photoframe photoframe[606]: 2019-11-27 14:49:06,244 - INFO - Registering URL /options/ to RouteOptions (simple)
Nov 27 14:49:06 photoframe photoframe[606]: 2019-11-27 14:49:06,248 - INFO - Registering URL /options// to RouteOptions (simple)
Nov 27 14:49:06 photoframe photoframe[606]: 2019-11-27 14:49:06,260 - INFO - Registering URL / to RoutePages (simple)
Nov 27 14:49:06 photoframe photoframe[606]: 2019-11-27 14:49:06,262 - INFO - Registering URL / to RoutePages (simple)
Nov 27 14:49:06 photoframe photoframe[606]: 2019-11-27 14:49:06,269 - INFO - Registering URL /debug to RouteDebug (simple)
Nov 27 14:49:06 photoframe photoframe[606]: 2019-11-27 14:49:06,280 - INFO - Registering URL /setting to RouteSettings
Nov 27 14:49:06 photoframe photoframe[606]: 2019-11-27 14:49:06,283 - INFO - Registering URL /setting/ to RouteSettings
Nov 27 14:49:06 photoframe photoframe[606]: 2019-11-27 14:49:06,286 - INFO - Registering URL /setting// to RouteSettings
Nov 27 14:49:06 photoframe photoframe[606]: 2019-11-27 14:49:06,288 - INFO - Registering URL /keywords//help to RouteKeywords
Nov 27 14:49:06 photoframe photoframe[606]: 2019-11-27 14:49:06,291 - INFO - Registering URL /keywords/ to RouteKeywords
Nov 27 14:49:06 photoframe photoframe[606]: 2019-11-27 14:49:06,293 - INFO - Registering URL /keywords//add to RouteKeywords
Nov 27 14:49:06 photoframe photoframe[606]: 2019-11-27 14:49:06,295 - INFO - Registering URL /keywords//delete to RouteKeywords
Nov 27 14:49:06 photoframe photoframe[606]: 2019-11-27 14:49:06,298 - INFO - Registering URL /keywords//source/ to RouteKeywords
Nov 27 14:49:06 photoframe photoframe[606]: 2019-11-27 14:49:06,301 - INFO - Registering URL /rotation to RouteOrientation
Nov 27 14:49:06 photoframe photoframe[606]: 2019-11-27 14:49:06,304 - INFO - Registering URL /rotation/ to RouteOrientation
Nov 27 14:49:06 photoframe photoframe[606]: 2019-11-27 14:49:06,308 - INFO - Registering URL /overscan to RouteOverscan
Nov 27 14:49:06 photoframe photoframe[606]: 2019-11-27 14:49:06,311 - INFO - Registering URL /overscan/ to RouteOverscan
Nov 27 14:49:06 photoframe photoframe[606]: 2019-11-27 14:49:06,315 - INFO - Registering URL /maintenance/ to RouteMaintenance
Nov 27 14:49:06 photoframe photoframe[606]: 2019-11-27 14:49:06,319 - INFO - Registering URL /details/ to RouteDetails
Nov 27 14:49:06 photoframe photoframe[606]: 2019-11-27 14:49:06,321 - INFO - Registering URL /upload/ to RouteUpload
Nov 27 14:49:06 photoframe photoframe[606]: 2019-11-27 14:49:06,324 - INFO - Registering URL /callback to RouteOAuthLink
Nov 27 14:49:06 photoframe photoframe[606]: 2019-11-27 14:49:06,325 - INFO - Registering URL /service//link to RouteOAuthLink
Nov 27 14:49:06 photoframe photoframe[606]: 2019-11-27 14:49:06,328 - INFO - Registering URL /service//oauth to RouteOAuthLink
Nov 27 14:49:06 photoframe photoframe[606]: 2019-11-27 14:49:06,330 - INFO - Registering URL /service/ to RouteService
Nov 27 14:49:06 photoframe photoframe[606]: 2019-11-27 14:49:06,333 - INFO - Registering URL /control/ to RouteControl
Nov 27 14:49:09 photoframe dhcpcd[360]: wlan0: no IPv6 Routers available
Nov 27 14:49:23 photoframe photoframe[606]: 2019-11-27 14:49:23,918 - INFO - Starting presentation
Nov 27 14:49:34 photoframe systemd-timesyncd[265]: Timed out waiting for reply from 159.203.158.197:123 (2.debian.pool.ntp.org).
Nov 27 15:17:43 photoframe systemd[1]: Time has been changed
Nov 27 15:17:43 photoframe systemd-timesyncd[265]: Synchronized to time server 64.22.253.155:123 (2.debian.pool.ntp.org).
Nov 27 15:17:43 photoframe systemd[1]: apt-daily-upgrade.timer: Adding 16min 46.801407s random time.
Nov 27 15:17:43 photoframe systemd[1]: apt-daily.timer: Adding 11h 11min 43.475226s random time.
Nov 27 15:18:07 photoframe systemd[1]: plymouth-start.service: Cannot add dependency job, ignoring: Unit plymouth-start.service is masked.
Nov 27 15:18:07 photoframe systemd[1]: Stopping OpenBSD Secure Shell server...
Nov 27 15:18:07 photoframe systemd[1]: Stopped OpenBSD Secure Shell server.
Nov 27 15:18:07 photoframe systemd[1]: Starting OpenBSD Secure Shell server...
Nov 27 15:18:07 photoframe systemd[1]: Started OpenBSD Secure Shell server.
Nov 27 15:19:08 photoframe systemd[1]: Created slice User Slice of pi.
Nov 27 15:19:08 photoframe systemd[1]: plymouth-start.service: Cannot add dependency job, ignoring: Unit plymouth-start.service is masked.
Nov 27 15:19:08 photoframe systemd[1]: Starting User Manager for UID 1000...
Nov 27 15:19:08 photoframe systemd[1]: Started Session c1 of user pi.
Nov 27 15:19:08 photoframe systemd[749]: Listening on GnuPG cryptographic agent and passphrase cache.
Nov 27 15:19:08 photoframe systemd[749]: Reached target Paths.
Nov 27 15:19:08 photoframe systemd[749]: Listening on GnuPG cryptographic agent (access for web browsers).
Nov 27 15:19:08 photoframe systemd[749]: Listening on GnuPG cryptographic agent and passphrase cache (restricted).
Nov 27 15:19:08 photoframe systemd[749]: Listening on GnuPG cryptographic agent (ssh-agent emulation).
Nov 27 15:19:08 photoframe systemd[749]: Reached target Sockets.
Nov 27 15:19:08 photoframe systemd[749]: Reached target Timers.
Nov 27 15:19:08 photoframe systemd[749]: Reached target Basic System.
Nov 27 15:19:08 photoframe systemd[749]: Reached target Default.
Nov 27 15:19:08 photoframe systemd[749]: Startup finished in 76ms.
Nov 27 15:19:08 photoframe systemd[1]: Started User Manager for UID 1000.
Nov 27 15:32:14 photoframe systemd[1]: Starting Cleanup of Temporary Directories...
Nov 27 15:32:15 photoframe systemd[1]: Started Cleanup of Temporary Directories.
(size of logfile 4932969 bytes, created Wed Nov 27 15:32:14 2019)
Stacktrace of all running threads
# ThreadID: 1953494128
File: "/usr/lib/python2.7/os.py", line 278, in walk
  names = listdir(top)

# ThreadID: 1963979888
File: "/usr/lib/python2.7/threading.py", line 774, in __bootstrap
  self.__bootstrap_inner()
File: "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  self.run()
File: "/root/photoframe/modules/shutdown.py", line 59, in run
  i = poller.poll(None)

# ThreadID: 1995684032
File: "./frame.py", line 178, in 
  frame.start()
File: "./frame.py", line 175, in start
  self.webServer.start()
File: "/root/photoframe/modules/server.py", line 84, in start
  self.run()
File: "/root/photoframe/modules/server.py", line 101, in run
  self.app.run(debug=False, port=self.port, host=self.listen )
File: "/usr/lib/python2.7/dist-packages/flask/app.py", line 841, in run
  run_simple(host, port, self, **options)
File: "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 708, in run_simple
  inner()
File: "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 673, in inner
  srv.serve_forever()
File: "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 511, in serve_forever
  HTTPServer.serve_forever(self)
File: "/usr/lib/python2.7/SocketServer.py", line 233, in serve_forever
  self._handle_request_noblock()
File: "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
  self.process_request(request, client_address)
File: "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
  self.finish_request(request, client_address)
File: "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
  self.RequestHandlerClass(request, client_address, self)
File: "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
  self.handle()
File: "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 228, in handle
  rv = BaseHTTPRequestHandler.handle(self)
File: "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
  self.handle_one_request()
File: "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 263, in handle_one_request
  return self.run_wsgi()
File: "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 205, in run_wsgi
  execute(self.server.app)
File: "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 193, in execute
  application_iter = app(environ, start_response)
File: "/usr/lib/python2.7/dist-packages/flask/app.py", line 1997, in __call__
  return self.wsgi_app(environ, start_response)
File: "/usr/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
  response = self.full_dispatch_request()
File: "/usr/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
  rv = self.dispatch_request()
File: "/usr/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
  return self.view_functions[rule.endpoint](**req.view_args)
File: "/root/photoframe/routes/baseroute.py", line 62, in __call__
  return self.handle(self.app, **kwargs)
File: "/root/photoframe/routes/debug.py", line 34, in handle
  report.append(debug.stacktrace())
File: "/root/photoframe/modules/debug.py", line 48, in stacktrace
  for filename, lineno, name, line in traceback.extract_stack(stack):

# ThreadID: 1973724272
File: "/usr/lib/python2.7/threading.py", line 774, in __bootstrap
  self.__bootstrap_inner()
File: "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  self.run()
File: "/root/photoframe/modules/timekeeper.py", line 118, in run
  time.sleep(60) # every minute

**Comment by mrworf** [comment]
Double check the setup in Google console. Most likely something is misspelled or has an extra space 

On November 27, 2019 2:24:00 PM PST, rockrdr <notifications@github.com> wrote:
>error im getting now..
>Error: redirect_uri_mismatch
>
>The redirect URI in the request, https://photoframe.sensenet.nu, does
>not match the ones authorized for the OAuth client. To update the
>authorized redirect URIs, visit:
>https://console.developers.google.com/apis/credentials/oauthclient/249509516012-ie59c0cf48imstarld4aab9u1nagk7b4.apps.googleusercontent.com?project=249509516012
> I'm getting output now to post.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/mrworf/photoframe/issues/145#issuecomment-559271079

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by rockrdr** [comment]
that was it, thank you. had a space in it, I thought I checked that... 

appreciate your help.
