### ISSUE TITLE
No results for any keywords in Google Photos

### ISSUE THREAD

**Issue by y4utj4** [mrworf/photoframe#147]
**Issue:** I've been able to successfully validate my OAuth credentials for google photos. Any keywords I attempt to enter are prompted with a "No such album" response. 

**What I've Tried:**
- I've followed the guide [here](https://mrworf.github.io/photoframe/2018/02/26/setting-up-photoframe)
- I've removed and redid my credentials for the oath setup after the first round of attempts were unsuccessful at finding my albums
- I enabled SSH and debugging. The process is returning an 403 None status code. 
- I've disabled my home VPN thinking that's the issue (google is finicky like that) still no dice

Not sure where to go from there. I'm pretty good with python and troubleshooting but this one's got me stumped a bit. 

Thanks!!

**Comment by y4utj4** [comment]
Update: Adding the keyword 'latest' doesn't return any results but when I click 'open', it goes to the appropriate page on my google photos.

**Comment by y4utj4** [comment]
`Dec 19 18:24:12 photoframe photoframe[558]: 2019-12-19 18:24:12,335 - WARNING - Requesting photo failed with status code 403
Dec 19 18:24:12 photoframe photoframe[558]: 2019-12-19 18:24:12,344 - WARNING - More details: '{\n  "error": {\n    "code": 403,\n    "message": "Photos Library API has not been used in project 942887834541 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/photoslibrary.googleapis.com/overview?project=942887834541 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.",\n    "status": "PERMISSION_DENIED",\n    "details": [\n      {\n        "@type": "type.googleapis.com/google.rpc.Help",\n        "links": [\n          {\n            "description": "Google developers console API activation",\n            "url": "https://console.developers.google.com/apis/api/photoslibrary.googleapis.com/overview?project=942887834541"\n          }\n        ]\n      }\n    ]\n  }\n}\n'
Dec 19 18:24:12 photoframe photoframe[558]: 2019-12-19 18:24:12,344 - ERROR - No result returned for keyword "latest"!
Dec 19 19:22:29 photoframe photoframe[558]: 2019-12-19 19:22:29,823 - ERROR - netifaces call failed, using checkNetwork() instead (depends on internet)
Dec 19 19:22:29 photoframe photoframe[558]: Traceback (most recent call last):
Dec 19 19:22:29 photoframe photoframe[558]:   File "/root/photoframe/modules/helper.py", line 72, in getDeviceIp
Dec 19 19:22:29 photoframe photoframe[558]:     net = netifaces.ifaddresses(dev)[netifaces.AF_INET]
Dec 19 19:22:29 photoframe photoframe[558]: KeyError: 2
Dec 19 19:22:29 photoframe photoframe[558]: 2019-12-19 19:22:29,829 - ERROR - Failed to get IP via old method
Dec 19 19:22:29 photoframe photoframe[558]: Traceback (most recent call last):
Dec 19 19:22:29 photoframe photoframe[558]:   File "/root/photoframe/modules/helper.py", line 87, in _checkNetwork
Dec 19 19:22:29 photoframe photoframe[558]:     s.connect(("photoframe.sensenet.nu", 80))
Dec 19 19:22:29 photoframe photoframe[558]:   File "/usr/lib/python2.7/socket.py", line 228, in meth
Dec 19 19:22:29 photoframe photoframe[558]:     return getattr(self._sock,name)(*args)
Dec 19 19:22:29 photoframe photoframe[558]: gaierror: [Errno -3] Temporary failure in name resolution
Dec 19 19:24:13 photoframe photoframe[558]: 2019-12-19 19:24:13,914 - WARNING - Requesting photo failed with status code 403
Dec 19 19:24:13 photoframe photoframe[558]: 2019-12-19 19:24:13,920 - WARNING - More details: '{\n  "error": {\n    "code": 403,\n    "message": "Photos Library API has not been used in project 942887834541 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/photoslibrary.googleapis.com/overview?project=942887834541 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.",\n    "status": "PERMISSION_DENIED",\n    "details": [\n      {\n        "@type": "type.googleapis.com/google.rpc.Help",\n        "links": [\n          {\n            "description": "Google developers console API activation",\n            "url": "https://console.developers.google.com/apis/api/photoslibrary.googleapis.com/overview?project=942887834541"\n          }\n        ]\n      }\n    ]\n  }\n}\n'
Dec 19 19:24:13 photoframe photoframe[558]: 2019-12-19 19:24:13,922 - ERROR - No result returned for keyword "latest"!
Dec 19 20:24:14 photoframe photoframe[558]: 2019-12-19 20:24:14,718 - WARNING - Requesting photo failed with status code 403
Dec 19 20:24:14 photoframe photoframe[558]: 2019-12-19 20:24:14,724 - WARNING - More details: '{\n  "error": {\n    "code": 403,\n    "message": "Photos Library API has not been used in project 942887834541 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/photoslibrary.googleapis.com/overview?project=942887834541 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.",\n    "status": "PERMISSION_DENIED",\n    "details": [\n      {\n        "@type": "type.googleapis.com/google.rpc.Help",\n        "links": [\n          {\n            "description": "Google developers console API activation",\n            "url": "https://console.developers.google.com/apis/api/photoslibrary.googleapis.com/overview?project=942887834541"\n          }\n        ]\n      }\n    ]\n  }\n}\n'
Dec 19 20:24:14 photoframe photoframe[558]: 2019-12-19 20:24:14,725 - ERROR - No result returned for keyword "latest"!
Dec 19 21:24:18 photoframe photoframe[558]: 2019-12-19 21:24:18,714 - WARNING - Requesting photo failed with status code 403
Dec 19 21:24:18 photoframe photoframe[558]: 2019-12-19 21:24:18,722 - WARNING - More details: '{\n  "error": {\n    "code": 403,\n    "message": "Photos Library API has not been used in project 942887834541 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/photoslibrary.googleapis.com/overview?project=942887834541 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.",\n    "status": "PERMISSION_DENIED",\n    "details": [\n      {\n        "@type": "type.googleapis.com/google.rpc.Help",\n        "links": [\n          {\n            "description": "Google developers console API activation",\n            "url": "https://console.developers.google.com/apis/api/photoslibrary.googleapis.com/overview?project=942887834541"\n          }\n        ]\n      }\n    ]\n  }\n}\n'
Dec 19 21:24:18 photoframe photoframe[558]: 2019-12-19 21:24:18,723 - ERROR - No result returned for keyword "latest"!
Dec 19 21:37:57 photoframe photoframe[558]: 2019-12-19 21:37:57,712 - ERROR - netifaces call failed, using checkNetwork() instead (depends on internet)
Dec 19 21:37:57 photoframe photoframe[558]: Traceback (most recent call last):
Dec 19 21:37:57 photoframe photoframe[558]:   File "/root/photoframe/modules/helper.py", line 72, in getDeviceIp
Dec 19 21:37:57 photoframe photoframe[558]:     net = netifaces.ifaddresses(dev)[netifaces.AF_INET]
Dec 19 21:37:57 photoframe photoframe[558]: KeyError: 2
Dec 19 21:37:57 photoframe photoframe[558]: 2019-12-19 21:37:57,714 - ERROR - Failed to get IP via old method
Dec 19 21:37:57 photoframe photoframe[558]: Traceback (most recent call last):
Dec 19 21:37:57 photoframe photoframe[558]:   File "/root/photoframe/modules/helper.py", line 87, in _checkNetwork
Dec 19 21:37:57 photoframe photoframe[558]:     s.connect(("photoframe.sensenet.nu", 80))
Dec 19 21:37:57 photoframe photoframe[558]:   File "/usr/lib/python2.7/socket.py", line 228, in meth
Dec 19 21:37:57 photoframe photoframe[558]:     return getattr(self._sock,name)(*args)
Dec 19 21:37:57 photoframe photoframe[558]: gaierror: [Errno -3] Temporary failure in name resolution
Dec 19 22:24:21 photoframe photoframe[558]: 2019-12-19 22:24:21,034 - WARNING - Requesting photo failed with status code 403
Dec 19 22:24:21 photoframe photoframe[558]: 2019-12-19 22:24:21,041 - WARNING - More details: '{\n  "error": {\n    "code": 403,\n    "message": "Photos Library API has not been used in project 942887834541 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/photoslibrary.googleapis.com/overview?project=942887834541 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.",\n    "status": "PERMISSION_DENIED",\n    "details": [\n      {\n        "@type": "type.googleapis.com/google.rpc.Help",\n        "links": [\n          {\n            "description": "Google developers console API activation",\n            "url": "https://console.developers.google.com/apis/api/photoslibrary.googleapis.com/overview?project=942887834541"\n          }\n        ]\n      }\n    ]\n  }\n}\n'
Dec 19 22:24:21 photoframe photoframe[558]: 2019-12-19 22:24:21,042 - ERROR - No result returned for keyword "latest"!
Dec 19 23:24:21 photoframe photoframe[558]: 2019-12-19 23:24:21,861 - WARNING - Requesting photo failed with status code 403
Dec 19 23:24:21 photoframe photoframe[558]: 2019-12-19 23:24:21,869 - WARNING - More details: '{\n  "error": {\n    "code": 403,\n    "message": "Photos Library API has not been used in project 942887834541 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/photoslibrary.googleapis.com/overview?project=942887834541 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.",\n    "status": "PERMISSION_DENIED",\n    "details": [\n      {\n        "@type": "type.googleapis.com/google.rpc.Help",\n        "links": [\n          {\n            "description": "Google developers console API activation",\n            "url": "https://console.developers.google.com/apis/api/photoslibrary.googleapis.com/overview?project=942887834541"\n          }\n        ]\n      }\n    ]\n  }\n}\n'
Dec 19 23:24:21 photoframe photoframe[558]: 2019-12-19 23:24:21,870 - ERROR - No result returned for keyword "latest"!
Dec 19 23:48:13 photoframe photoframe[558]: 2019-12-19 23:48:13,770 - ERROR - netifaces call failed, using checkNetwork() instead (depends on internet)
Dec 19 23:48:13 photoframe photoframe[558]: Traceback (most recent call last):
Dec 19 23:48:13 photoframe photoframe[558]:   File "/root/photoframe/modules/helper.py", line 72, in getDeviceIp
Dec 19 23:48:13 photoframe photoframe[558]:     net = netifaces.ifaddresses(dev)[netifaces.AF_INET]
Dec 19 23:48:13 photoframe photoframe[558]: KeyError: 2
Dec 19 23:48:13 photoframe photoframe[558]: 2019-12-19 23:48:13,773 - ERROR - Failed to get IP via old method
Dec 19 23:48:13 photoframe photoframe[558]: Traceback (most recent call last):
Dec 19 23:48:13 photoframe photoframe[558]:   File "/root/photoframe/modules/helper.py", line 87, in _checkNetwork
Dec 19 23:48:13 photoframe photoframe[558]:     s.connect(("photoframe.sensenet.nu", 80))
Dec 19 23:48:13 photoframe photoframe[558]:   File "/usr/lib/python2.7/socket.py", line 228, in meth
Dec 19 23:48:13 photoframe photoframe[558]:     return getattr(self._sock,name)(*args)
Dec 19 23:48:13 photoframe photoframe[558]: gaierror: [Errno -3] Temporary failure in name resolution
Dec 20 00:24:22 photoframe photoframe[558]: 2019-12-20 00:24:22,689 - WARNING - Requesting photo failed with status code 403
Dec 20 00:24:22 photoframe photoframe[558]: 2019-12-20 00:24:22,696 - WARNING - More details: '{\n  "error": {\n    "code": 403,\n    "message": "Photos Library API has not been used in project 942887834541 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/photoslibrary.googleapis.com/overview?project=942887834541 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.",\n    "status": "PERMISSION_DENIED",\n    "details": [\n      {\n        "@type": "type.googleapis.com/google.rpc.Help",\n        "links": [\n          {\n            "description": "Google developers console API activation",\n            "url": "https://console.developers.google.com/apis/api/photoslibrary.googleapis.com/overview?project=942887834541"\n          }\n        ]\n      }\n    ]\n  }\n}\n'
Dec 20 00:24:22 photoframe photoframe[558]: 2019-12-20 00:24:22,697 - ERROR - No result returned for keyword "latest"!
Dec 20 01:24:23 photoframe photoframe[558]: 2019-12-20 01:24:23,515 - WARNING - Requesting photo failed with status code 403
Dec 20 01:24:23 photoframe photoframe[558]: 2019-12-20 01:24:23,521 - WARNING - More details: '{\n  "error": {\n    "code": 403,\n    "message": "Photos Library API has not been used in project 942887834541 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/photoslibrary.googleapis.com/overview?project=942887834541 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.",\n    "status": "PERMISSION_DENIED",\n    "details": [\n      {\n        "@type": "type.googleapis.com/google.rpc.Help",\n        "links": [\n          {\n            "description": "Google developers console API activation",\n            "url": "https://console.developers.google.com/apis/api/photoslibrary.googleapis.com/overview?project=942887834541"\n          }\n        ]\n      }\n    ]\n  }\n}\n'
Dec 20 01:24:23 photoframe photoframe[558]: 2019-12-20 01:24:23,522 - ERROR - No result returned for keyword "latest"!
Dec 20 02:17:17 photoframe photoframe[558]: 2019-12-20 02:17:17,831 - ERROR - netifaces call failed, using checkNetwork() instead (depends on internet)
Dec 20 02:17:17 photoframe photoframe[558]: Traceback (most recent call last):
Dec 20 02:17:17 photoframe photoframe[558]:   File "/root/photoframe/modules/helper.py", line 70, in getDeviceIp
Dec 20 02:17:17 photoframe photoframe[558]:     dev = netifaces.gateways()['default'][netifaces.AF_INET][1]
Dec 20 02:17:17 photoframe photoframe[558]: KeyError: 2
Dec 20 02:17:17 photoframe photoframe[558]: 2019-12-20 02:17:17,834 - ERROR - Failed to get IP via old method
Dec 20 02:17:17 photoframe photoframe[558]: Traceback (most recent call last):
Dec 20 02:17:17 photoframe photoframe[558]:   File "/root/photoframe/modules/helper.py", line 87, in _checkNetwork
Dec 20 02:17:17 photoframe photoframe[558]:     s.connect(("photoframe.sensenet.nu", 80))
Dec 20 02:17:17 photoframe photoframe[558]:   File "/usr/lib/python2.7/socket.py", line 228, in meth
Dec 20 02:17:17 photoframe photoframe[558]:     return getattr(self._sock,name)(*args)
Dec 20 02:17:17 photoframe photoframe[558]: gaierror: [Errno -3] Temporary failure in name resolution
Dec 20 02:24:24 photoframe photoframe[558]: 2019-12-20 02:24:24,342 - WARNING - Requesting photo failed with status code 403
Dec 20 02:24:24 photoframe photoframe[558]: 2019-12-20 02:24:24,348 - WARNING - More details: '{\n  "error": {\n    "code": 403,\n    "message": "Photos Library API has not been used in project 942887834541 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/photoslibrary.googleapis.com/overview?project=942887834541 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.",\n    "status": "PERMISSION_DENIED",\n    "details": [\n      {\n        "@type": "type.googleapis.com/google.rpc.Help",\n        "links": [\n          {\n            "description": "Google developers console API activation",\n            "url": "https://console.developers.google.com/apis/api/photoslibrary.googleapis.com/overview?project=942887834541"\n          }\n        ]\n      }\n    ]\n  }\n}\n'
Dec 20 02:24:24 photoframe photoframe[558]: 2019-12-20 02:24:24,349 - ERROR - No result returned for keyword "latest"!
Dec 20 03:24:27 photoframe photoframe[558]: 2019-12-20 03:24:27,653 - WARNING - Requesting photo failed with status code 403
Dec 20 03:24:27 photoframe photoframe[558]: 2019-12-20 03:24:27,658 - WARNING - More details: '{\n  "error": {\n    "code": 403,\n    "message": "Photos Library API has not been used in project 942887834541 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/photoslibrary.googleapis.com/overview?project=942887834541 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.",\n    "status": "PERMISSION_DENIED",\n    "details": [\n      {\n        "@type": "type.googleapis.com/google.rpc.Help",\n        "links": [\n          {\n            "description": "Google developers console API activation",\n            "url": "https://console.developers.google.com/apis/api/photoslibrary.googleapis.com/overview?project=942887834541"\n          }\n        ]\n      }\n    ]\n  }\n}\n'
Dec 20 03:24:27 photoframe photoframe[558]: 2019-12-20 03:24:27,659 - ERROR - No result returned for keyword "latest"!
Dec 20 04:24:28 photoframe photoframe[558]: 2019-12-20 04:24:28,514 - WARNING - Requesting photo failed with status code 403
Dec 20 04:24:28 photoframe photoframe[558]: 2019-12-20 04:24:28,521 - WARNING - More details: '{\n  "error": {\n    "code": 403,\n    "message": "Photos Library API has not been used in project 942887834541 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/photoslibrary.googleapis.com/overview?project=942887834541 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.",\n    "status": "PERMISSION_DENIED",\n    "details": [\n      {\n        "@type": "type.googleapis.com/google.rpc.Help",\n        "links": [\n          {\n            "description": "Google developers console API activation",\n            "url": "https://console.developers.google.com/apis/api/photoslibrary.googleapis.com/overview?project=942887834541"\n          }\n        ]\n      }\n    ]\n  }\n}\n'
Dec 20 04:24:28 photoframe photoframe[558]: 2019-12-20 04:24:28,522 - ERROR - No result returned for keyword "latest"!
Dec 20 05:24:29 photoframe photoframe[558]: 2019-12-20 05:24:29,279 - WARNING - Requesting photo failed with status code 403
Dec 20 05:24:29 photoframe photoframe[558]: 2019-12-20 05:24:29,285 - WARNING - More details: '{\n  "error": {\n    "code": 403,\n    "message": "Photos Library API has not been used in project 942887834541 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/photoslibrary.googleapis.com/overview?project=942887834541 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.",\n    "status": "PERMISSION_DENIED",\n    "details": [\n      {\n        "@type": "type.googleapis.com/google.rpc.Help",\n        "links": [\n          {\n            "description": "Google developers console API activation",\n            "url": "https://console.developers.google.com/apis/api/photoslibrary.googleapis.com/overview?project=942887834541"\n          }\n        ]\n      }\n    ]\n  }\n}\n'
Dec 20 05:24:29 photoframe photoframe[558]: 2019-12-20 05:24:29,286 - ERROR - No result returned for keyword "latest"!
Dec 20 06:16:21 photoframe photoframe[558]: 2019-12-20 06:16:21,869 - ERROR - netifaces call failed, using checkNetwork() instead (depends on internet)
Dec 20 06:16:21 photoframe photoframe[558]: Traceback (most recent call last):
Dec 20 06:16:21 photoframe photoframe[558]:   File "/root/photoframe/modules/helper.py", line 72, in getDeviceIp
Dec 20 06:16:21 photoframe photoframe[558]:     net = netifaces.ifaddresses(dev)[netifaces.AF_INET]
Dec 20 06:16:21 photoframe photoframe[558]: KeyError: 2
Dec 20 06:16:21 photoframe photoframe[558]: 2019-12-20 06:16:21,872 - ERROR - Failed to get IP via old method
Dec 20 06:16:21 photoframe photoframe[558]: Traceback (most recent call last):
Dec 20 06:16:21 photoframe photoframe[558]:   File "/root/photoframe/modules/helper.py", line 87, in _checkNetwork
Dec 20 06:16:21 photoframe photoframe[558]:     s.connect(("photoframe.sensenet.nu", 80))
Dec 20 06:16:21 photoframe photoframe[558]:   File "/usr/lib/python2.7/socket.py", line 228, in meth
Dec 20 06:16:21 photoframe photoframe[558]:     return getattr(self._sock,name)(*args)
Dec 20 06:16:21 photoframe photoframe[558]: gaierror: [Errno -3] Temporary failure in name resolution
Dec 20 06:24:30 photoframe photoframe[558]: 2019-12-20 06:24:30,086 - WARNING - Requesting photo failed with status code 403
Dec 20 06:24:30 photoframe photoframe[558]: 2019-12-20 06:24:30,093 - WARNING - More details: '{\n  "error": {\n    "code": 403,\n    "message": "Photos Library API has not been used in project 942887834541 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/photoslibrary.googleapis.com/overview?project=942887834541 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.",\n    "status": "PERMISSION_DENIED",\n    "details": [\n      {\n        "@type": "type.googleapis.com/google.rpc.Help",\n        "links": [\n          {\n            "description": "Google developers console API activation",\n            "url": "https://console.developers.google.com/apis/api/photoslibrary.googleapis.com/overview?project=942887834541"\n          }\n        ]\n      }\n    ]\n  }\n}\n'
Dec 20 06:24:30 photoframe photoframe[558]: 2019-12-20 06:24:30,094 - ERROR - No result returned for keyword "latest"!
Dec 20 07:10:10 photoframe photoframe[558]: 2019-12-20 07:10:10,066 - INFO - Internal display detected`

**Comment by y4utj4** [comment]
Nevermind, as I was! I found the issue. I guess the tutorial needs updated to reflect you must activate the API, not simply just set up OAuth (or I can't read). Either way, I have it working now, thanks!!

**Comment by mrworf** [comment]
I think it's a new step google added, thanks for letting me know, tutorial will be updated 😄 

Glad to hear you got it working
