### ISSUE TITLE
No such redirect

### ISSUE THREAD

**Issue by RonaldgMcDonald** [mrworf/photoframe#155]
Hello 

When I try to authorize:
I selected my account to continue to sensenet.nu
and got to sensenet.nu
Grant sensenet.nu permission
Confirm allowing sensenet.nu to view my google photos
then i get message No such redirect
Mar 15 17:25:38 KidsPhotos photoframe[359]:     self.flush()
Mar 15 17:25:38 KidsPhotos photoframe[359]:   File "/usr/lib/python2.7/socket.py", line 307, in flush
Mar 15 17:25:38 KidsPhotos photoframe[359]:     self._sock.sendall(view[write_offset:write_offset+buffer_size])
Mar 15 17:25:38 KidsPhotos photoframe[359]: error: [Errno 32] Broken pipe
Mar 15 17:25:38 KidsPhotos photoframe[359]: Traceback (most recent call last):
Mar 15 17:25:38 KidsPhotos photoframe[359]:   File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
Mar 15 17:25:38 KidsPhotos photoframe[359]:     self.process_request(request, client_address)
Mar 15 17:25:38 KidsPhotos photoframe[359]:   File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
Mar 15 17:25:38 KidsPhotos photoframe[359]:     self.finish_request(request, client_address)
Mar 15 17:25:38 KidsPhotos photoframe[359]:   File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
Mar 15 17:25:38 KidsPhotos photoframe[359]:     self.RequestHandlerClass(request, client_address, self)
Mar 15 17:25:38 KidsPhotos photoframe[359]:   File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
Mar 15 17:25:38 KidsPhotos photoframe[359]:     self.finish()
Mar 15 17:25:38 KidsPhotos photoframe[359]:   File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
Mar 15 17:25:38 KidsPhotos photoframe[359]:     self.wfile.close()
Mar 15 17:25:38 KidsPhotos photoframe[359]:   File "/usr/lib/python2.7/socket.py", line 283, in close
Mar 15 17:25:38 KidsPhotos photoframe[359]:     self.flush()
Mar 15 17:25:38 KidsPhotos photoframe[359]:   File "/usr/lib/python2.7/socket.py", line 307, in flush
Mar 15 17:25:38 KidsPhotos photoframe[359]:     self._sock.sendall(view[write_offset:write_offset+buffer_size])
Mar 15 17:25:38 KidsPhotos photoframe[359]: error: [Errno 32] Broken pipe
Mar 15 17:25:38 KidsPhotos photoframe[359]: Traceback (most recent call last):
Mar 15 17:25:38 KidsPhotos photoframe[359]:   File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
Mar 15 17:25:38 KidsPhotos photoframe[359]:     self.process_request(request, client_address)
Mar 15 17:25:38 KidsPhotos photoframe[359]:   File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
Mar 15 17:25:38 KidsPhotos photoframe[359]:     self.finish_request(request, client_address)
Mar 15 17:25:38 KidsPhotos photoframe[359]:   File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
Mar 15 17:25:38 KidsPhotos photoframe[359]:     self.RequestHandlerClass(request, client_address, self)
Mar 15 17:25:38 KidsPhotos photoframe[359]:   File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
Mar 15 17:25:38 KidsPhotos photoframe[359]:     self.finish()
Mar 15 17:25:38 KidsPhotos photoframe[359]:   File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
Mar 15 17:25:38 KidsPhotos photoframe[359]:     self.wfile.close()
Mar 15 17:25:38 KidsPhotos photoframe[359]:   File "/usr/lib/python2.7/socket.py", line 283, in close
Mar 15 17:25:38 KidsPhotos photoframe[359]:     self.flush()
Mar 15 17:25:38 KidsPhotos photoframe[359]:   File "/usr/lib/python2.7/socket.py", line 307, in flush
Mar 15 17:25:38 KidsPhotos photoframe[359]:     self._sock.sendall(view[write_offset:write_offset+buffer_size])
Mar 15 17:25:38 KidsPhotos photoframe[359]: error: [Errno 32] Broken pipe
Mar 15 17:25:38 KidsPhotos photoframe[359]: Traceback (most recent call last):
Mar 15 17:25:38 KidsPhotos photoframe[359]:   File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
Mar 15 17:25:38 KidsPhotos photoframe[359]:     self.process_request(request, client_address)
Mar 15 17:25:38 KidsPhotos photoframe[359]:   File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
Mar 15 17:25:38 KidsPhotos photoframe[359]:     self.finish_request(request, client_address)
Mar 15 17:25:38 KidsPhotos photoframe[359]:   File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
Mar 15 17:25:38 KidsPhotos photoframe[359]:     self.RequestHandlerClass(request, client_address, self)
Mar 15 17:25:38 KidsPhotos photoframe[359]:   File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
Mar 15 17:25:38 KidsPhotos photoframe[359]:     self.finish()
Mar 15 17:25:38 KidsPhotos photoframe[359]:   File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
Mar 15 17:25:38 KidsPhotos photoframe[359]:     self.wfile.close()
Mar 15 17:25:38 KidsPhotos photoframe[359]:   File "/usr/lib/python2.7/socket.py", line 283, in close
Mar 15 17:25:38 KidsPhotos photoframe[359]:     self.flush()
Mar 15 17:25:38 KidsPhotos photoframe[359]:   File "/usr/lib/python2.7/socket.py", line 307, in flush
Mar 15 17:25:38 KidsPhotos photoframe[359]:     self._sock.sendall(view[write_offset:write_offset+buffer_size])
Mar 15 17:25:38 KidsPhotos photoframe[359]: error: [Errno 32] Broken pipe
Mar 15 18:21:20 KidsPhotos photoframe[359]: Traceback (most recent call last):
Mar 15 18:21:20 KidsPhotos photoframe[359]:   File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
Mar 15 18:21:20 KidsPhotos photoframe[359]:     self.process_request(request, client_address)
Mar 15 18:21:20 KidsPhotos photoframe[359]:   File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
Mar 15 18:21:20 KidsPhotos photoframe[359]:     self.finish_request(request, client_address)
Mar 15 18:21:20 KidsPhotos photoframe[359]:   File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
Mar 15 18:21:20 KidsPhotos photoframe[359]:     self.RequestHandlerClass(request, client_address, self)
Mar 15 18:21:20 KidsPhotos photoframe[359]:   File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
Mar 15 18:21:20 KidsPhotos photoframe[359]:     self.finish()
Mar 15 18:21:20 KidsPhotos photoframe[359]:   File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
Mar 15 18:21:20 KidsPhotos photoframe[359]:     self.wfile.close()
Mar 15 18:21:20 KidsPhotos photoframe[359]:   File "/usr/lib/python2.7/socket.py", line 283, in close
Mar 15 18:21:20 KidsPhotos photoframe[359]:     self.flush()
Mar 15 18:21:20 KidsPhotos photoframe[359]:   File "/usr/lib/python2.7/socket.py", line 307, in flush
Mar 15 18:21:20 KidsPhotos photoframe[359]:     self._sock.sendall(view[write_offset:write_offset+buffer_size])
Mar 15 18:21:20 KidsPhotos photoframe[359]: error: [Errno 32] Broken pipe
Mar 15 18:21:55 KidsPhotos photoframe[359]: Traceback (most recent call last):
Mar 15 18:21:55 KidsPhotos photoframe[359]:   File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
Mar 15 18:21:55 KidsPhotos photoframe[359]:     self.process_request(request, client_address)
Mar 15 18:21:55 KidsPhotos photoframe[359]:   File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
Mar 15 18:21:55 KidsPhotos photoframe[359]:     self.finish_request(request, client_address)
Mar 15 18:21:55 KidsPhotos photoframe[359]:   File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
Mar 15 18:21:55 KidsPhotos photoframe[359]:     self.RequestHandlerClass(request, client_address, self)
Mar 15 18:21:55 KidsPhotos photoframe[359]:   File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
Mar 15 18:21:55 KidsPhotos photoframe[359]:     self.finish()
Mar 15 18:21:55 KidsPhotos photoframe[359]:   File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
Mar 15 18:21:55 KidsPhotos photoframe[359]:     self.wfile.close()
Mar 15 18:21:55 KidsPhotos photoframe[359]:   File "/usr/lib/python2.7/socket.py", line 283, in close
Mar 15 18:21:55 KidsPhotos photoframe[359]:     self.flush()
Mar 15 18:21:55 KidsPhotos photoframe[359]:   File "/usr/lib/python2.7/socket.py", line 307, in flush
Mar 15 18:21:55 KidsPhotos photoframe[359]:     self._sock.sendall(view[write_offset:write_offset+buffer_size])
Mar 15 18:21:55 KidsPhotos photoframe[359]: error: [Errno 32] Broken pipe
Mar 15 18:21:57 KidsPhotos photoframe[359]: Traceback (most recent call last):
Mar 15 18:21:57 KidsPhotos photoframe[359]:   File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
Mar 15 18:21:57 KidsPhotos photoframe[359]:     self.process_request(request, client_address)
Mar 15 18:21:57 KidsPhotos photoframe[359]:   File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
Mar 15 18:21:57 KidsPhotos photoframe[359]:     self.finish_request(request, client_address)
Mar 15 18:21:57 KidsPhotos photoframe[359]:   File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
Mar 15 18:21:57 KidsPhotos photoframe[359]:     self.RequestHandlerClass(request, client_address, self)
Mar 15 18:21:57 KidsPhotos photoframe[359]:   File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
Mar 15 18:21:57 KidsPhotos photoframe[359]:     self.finish()
Mar 15 18:21:57 KidsPhotos photoframe[359]:   File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
Mar 15 18:21:57 KidsPhotos photoframe[359]:     self.wfile.close()
Mar 15 18:21:57 KidsPhotos photoframe[359]:   File "/usr/lib/python2.7/socket.py", line 283, in close
Mar 15 18:21:57 KidsPhotos photoframe[359]:     self.flush()
Mar 15 18:21:57 KidsPhotos photoframe[359]:   File "/usr/lib/python2.7/socket.py", line 307, in flush
Mar 15 18:21:57 KidsPhotos photoframe[359]:     self._sock.sendall(view[write_offset:write_offset+buffer_size])
Mar 15 18:21:57 KidsPhotos photoframe[359]: error: [Errno 32] Broken pipe
(size of logfile 359605395 bytes, created Sun Mar 15 18:24:02 2020)
Last 100 lines from the system log (/var/log/syslog)
Mar 15 17:25:38 KidsPhotos photoframe[359]:     self.finish_request(request, client_address)
Mar 15 17:25:38 KidsPhotos photoframe[359]:   File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
Mar 15 17:25:38 KidsPhotos photoframe[359]:     self.RequestHandlerClass(request, client_address, self)
Mar 15 17:25:38 KidsPhotos photoframe[359]:   File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
Mar 15 17:25:38 KidsPhotos photoframe[359]:     self.finish()
Mar 15 17:25:38 KidsPhotos photoframe[359]:   File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
Mar 15 17:25:38 KidsPhotos photoframe[359]:     self.wfile.close()
Mar 15 17:25:38 KidsPhotos photoframe[359]:   File "/usr/lib/python2.7/socket.py", line 283, in close
Mar 15 17:25:38 KidsPhotos photoframe[359]:     self.flush()
Mar 15 17:25:38 KidsPhotos photoframe[359]:   File "/usr/lib/python2.7/socket.py", line 307, in flush
Mar 15 17:25:38 KidsPhotos photoframe[359]:     self._sock.sendall(view[write_offset:write_offset+buffer_size])
Mar 15 17:25:38 KidsPhotos photoframe[359]: error: [Errno 32] Broken pipe
Mar 15 17:25:38 KidsPhotos photoframe[359]: Traceback (most recent call last):
Mar 15 17:25:38 KidsPhotos photoframe[359]:   File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
Mar 15 17:25:38 KidsPhotos photoframe[359]:     self.process_request(request, client_address)
Mar 15 17:25:38 KidsPhotos photoframe[359]:   File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
Mar 15 17:25:38 KidsPhotos photoframe[359]:     self.finish_request(request, client_address)
Mar 15 17:25:38 KidsPhotos photoframe[359]:   File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
Mar 15 17:25:38 KidsPhotos photoframe[359]:     self.RequestHandlerClass(request, client_address, self)
Mar 15 17:25:38 KidsPhotos photoframe[359]:   File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
Mar 15 17:25:38 KidsPhotos photoframe[359]:     self.finish()
Mar 15 17:25:38 KidsPhotos photoframe[359]:   File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
Mar 15 17:25:38 KidsPhotos photoframe[359]:     self.wfile.close()
Mar 15 17:25:38 KidsPhotos photoframe[359]:   File "/usr/lib/python2.7/socket.py", line 283, in close
Mar 15 17:25:38 KidsPhotos photoframe[359]:     self.flush()
Mar 15 17:25:38 KidsPhotos photoframe[359]:   File "/usr/lib/python2.7/socket.py", line 307, in flush
Mar 15 17:25:38 KidsPhotos photoframe[359]:     self._sock.sendall(view[write_offset:write_offset+buffer_size])
Mar 15 17:25:38 KidsPhotos photoframe[359]: error: [Errno 32] Broken pipe
Mar 15 17:26:23 KidsPhotos systemd[1]: Starting Cleanup of Temporary Directories...
Mar 15 17:26:23 KidsPhotos systemd[1]: Started Cleanup of Temporary Directories.
Mar 15 18:11:09 KidsPhotos rngd[182]: stats: bits received from HRNG source: 80064
Mar 15 18:11:09 KidsPhotos rngd[182]: stats: bits sent to kernel pool: 34848
Mar 15 18:11:09 KidsPhotos rngd[182]: stats: entropy added to kernel pool: 34848
Mar 15 18:11:09 KidsPhotos rngd[182]: stats: FIPS 140-2 successes: 4
Mar 15 18:11:09 KidsPhotos rngd[182]: stats: FIPS 140-2 failures: 0
Mar 15 18:11:09 KidsPhotos rngd[182]: stats: FIPS 140-2(2001-10-10) Monobit: 0
Mar 15 18:11:09 KidsPhotos rngd[182]: stats: FIPS 140-2(2001-10-10) Poker: 0
Mar 15 18:11:09 KidsPhotos rngd[182]: stats: FIPS 140-2(2001-10-10) Runs: 0
Mar 15 18:11:09 KidsPhotos rngd[182]: stats: FIPS 140-2(2001-10-10) Long run: 0
Mar 15 18:11:09 KidsPhotos rngd[182]: stats: FIPS 140-2(2001-10-10) Continuous run: 0
Mar 15 18:11:09 KidsPhotos rngd[182]: stats: HRNG source speed: (min=114.172; avg=163.176; max=689.858)Kibits/s
Mar 15 18:11:09 KidsPhotos rngd[182]: stats: FIPS tests speed: (min=1.171; avg=2.153; max=8.847)Mibits/s
Mar 15 18:11:09 KidsPhotos rngd[182]: stats: Lowest ready-buffers level: 2
Mar 15 18:11:09 KidsPhotos rngd[182]: stats: Entropy starvations: 0
Mar 15 18:11:09 KidsPhotos rngd[182]: stats: Time spent starving for entropy: (min=0; avg=0.000; max=0)us
Mar 15 18:17:01 KidsPhotos CRON[1483]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Mar 15 18:21:20 KidsPhotos photoframe[359]: Traceback (most recent call last):
Mar 15 18:21:20 KidsPhotos photoframe[359]:   File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
Mar 15 18:21:20 KidsPhotos photoframe[359]:     self.process_request(request, client_address)
Mar 15 18:21:20 KidsPhotos photoframe[359]:   File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
Mar 15 18:21:20 KidsPhotos photoframe[359]:     self.finish_request(request, client_address)
Mar 15 18:21:20 KidsPhotos photoframe[359]:   File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
Mar 15 18:21:20 KidsPhotos photoframe[359]:     self.RequestHandlerClass(request, client_address, self)
Mar 15 18:21:20 KidsPhotos photoframe[359]:   File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
Mar 15 18:21:20 KidsPhotos photoframe[359]:     self.finish()
Mar 15 18:21:20 KidsPhotos photoframe[359]:   File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
Mar 15 18:21:20 KidsPhotos photoframe[359]:     self.wfile.close()
Mar 15 18:21:20 KidsPhotos photoframe[359]:   File "/usr/lib/python2.7/socket.py", line 283, in close
Mar 15 18:21:20 KidsPhotos photoframe[359]:     self.flush()
Mar 15 18:21:20 KidsPhotos photoframe[359]:   File "/usr/lib/python2.7/socket.py", line 307, in flush
Mar 15 18:21:20 KidsPhotos photoframe[359]:     self._sock.sendall(view[write_offset:write_offset+buffer_size])
Mar 15 18:21:20 KidsPhotos photoframe[359]: error: [Errno 32] Broken pipe
Mar 15 18:21:55 KidsPhotos photoframe[359]: Traceback (most recent call last):
Mar 15 18:21:55 KidsPhotos photoframe[359]:   File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
Mar 15 18:21:55 KidsPhotos photoframe[359]:     self.process_request(request, client_address)
Mar 15 18:21:55 KidsPhotos photoframe[359]:   File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
Mar 15 18:21:55 KidsPhotos photoframe[359]:     self.finish_request(request, client_address)
Mar 15 18:21:55 KidsPhotos photoframe[359]:   File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
Mar 15 18:21:55 KidsPhotos photoframe[359]:     self.RequestHandlerClass(request, client_address, self)
Mar 15 18:21:55 KidsPhotos photoframe[359]:   File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
Mar 15 18:21:55 KidsPhotos photoframe[359]:     self.finish()
Mar 15 18:21:55 KidsPhotos photoframe[359]:   File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
Mar 15 18:21:55 KidsPhotos photoframe[359]:     self.wfile.close()
Mar 15 18:21:55 KidsPhotos photoframe[359]:   File "/usr/lib/python2.7/socket.py", line 283, in close
Mar 15 18:21:55 KidsPhotos photoframe[359]:     self.flush()
Mar 15 18:21:55 KidsPhotos photoframe[359]:   File "/usr/lib/python2.7/socket.py", line 307, in flush
Mar 15 18:21:55 KidsPhotos photoframe[359]:     self._sock.sendall(view[write_offset:write_offset+buffer_size])
Mar 15 18:21:55 KidsPhotos photoframe[359]: error: [Errno 32] Broken pipe
Mar 15 18:21:57 KidsPhotos photoframe[359]: Traceback (most recent call last):
Mar 15 18:21:57 KidsPhotos photoframe[359]:   File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
Mar 15 18:21:57 KidsPhotos photoframe[359]:     self.process_request(request, client_address)
Mar 15 18:21:57 KidsPhotos photoframe[359]:   File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
Mar 15 18:21:57 KidsPhotos photoframe[359]:     self.finish_request(request, client_address)
Mar 15 18:21:57 KidsPhotos photoframe[359]:   File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
Mar 15 18:21:57 KidsPhotos photoframe[359]:     self.RequestHandlerClass(request, client_address, self)
Mar 15 18:21:57 KidsPhotos photoframe[359]:   File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
Mar 15 18:21:57 KidsPhotos photoframe[359]:     self.finish()
Mar 15 18:21:57 KidsPhotos photoframe[359]:   File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
Mar 15 18:21:57 KidsPhotos photoframe[359]:     self.wfile.close()
Mar 15 18:21:57 KidsPhotos photoframe[359]:   File "/usr/lib/python2.7/socket.py", line 283, in close
Mar 15 18:21:57 KidsPhotos photoframe[359]:     self.flush()
Mar 15 18:21:57 KidsPhotos photoframe[359]:   File "/usr/lib/python2.7/socket.py", line 307, in flush
Mar 15 18:21:57 KidsPhotos photoframe[359]:     self._sock.sendall(view[write_offset:write_offset+buffer_size])
Mar 15 18:21:57 KidsPhotos photoframe[359]: error: [Errno 32] Broken pipe
Mar 15 18:24:01 KidsPhotos dbus[211]: [system] Activating via systemd: service name='org.freedesktop.timedate1' unit='dbus-org.freedesktop.timedate1.service'
Mar 15 18:24:02 KidsPhotos systemd[1]: plymouth-start.service: Cannot add dependency job, ignoring: Unit plymouth-start.service is masked.
Mar 15 18:24:02 KidsPhotos systemd[1]: Starting Time & Date Service...
Mar 15 18:24:02 KidsPhotos dbus[211]: [system] Successfully activated service 'org.freedesktop.timedate1'
Mar 15 18:24:02 KidsPhotos systemd[1]: Started Time & Date Service.
Mar 15 18:24:02 KidsPhotos systemd-timedated[1681]: Changed time zone to 'America/Chicago'.

Ronald

**Comment by mrworf** [comment]
Hmm.. just tested the service and it's working. Maybe you have a 
adblocker or similar which is interfering with the OAuth flow?

**Comment by RonaldgMcDonald** [comment]
Thanks for the update, I created a new Google photos authorize and it
worked this time.
Thanks for the great software you created.

Ronald
