### ISSUE TITLE
Countdown on startup is slow

### ISSUE THREAD

**Issue by ubergeek42** [mrworf/photoframe#163]
I've got a Raspberry Pi Zero W, connected to an 2048x1536 display. During boot `convert` seems to take 2-3 seconds to generate each "Starting in N" image, which means the countdown before the slideshow starts takes some ~30seconds to complete instead of what I assume should just be 10.

Maybe the text rendered images can be cached? Or maybe there's a more efficient way to generate the image than `convert`.

**Comment by mrworf** [comment]
As it stands now, convert will continue to be used since it keeps the complixity of the app lower (can reuse it in the same pipeline). A PR to change this will be accepted as long as it doesn't break existing installs. Closing this ticket due to age
