### ISSUE TITLE
multiple wifi's-

### ISSUE THREAD

**Issue by gmimatt** [mrworf/photoframe#165]
Iwas trying to setup the wifi config file with multiple setups similar to the below page as referenced in previous thread here: http://www.geothread.net/multiple-wifi-networks-with-a-raspberry-pi/
However, when I add the second wifi setting, my pi will not connect to either network. What am I missing?

Also- thanks for the project! Almost ready to ship a monitor with a Pi Zero W mounted on the back to my mom in another state, so trying to nail this down before I ship it out of reach.

_Originally posted by @chewston in https://github.com/mrworf/photoframe/issues/144#issuecomment-570734485_

**Comment by mrworf** [comment]
Actually, someone edited the FAQ for this exact use-case, please see https://github.com/mrworf/photoframe/wiki/Frequently-Asked-Questions#you-want-to-setup-multiple-wifi-access-points-aka-setting-up-a-frame-to-surprise-your-in-laws

**Comment by gmimatt** [comment]
Thanks so much for the help!
Matt

**Comment by mrworf** [comment]
Closing ticket since I think it was solved now
