### ISSUE TITLE
No internet on startup

### ISSUE THREAD

**Issue by Bj-Go** [mrworf/photoframe#170]
Hello,

when I first start the Raspberry Pi with the flashed SD-card and WiFi credentials wrote into wifi-config, it only shows "No internet". The RP is directly next to the router. When using Raspbian, WiFi works great. So it has to do something with this program. Do you know a way to fix it?

PS It already did work fine but I just moved the RP a little bit and then nothing worked anymore. Tried reinstalling the image, changing the antenna's position, restarting everything but nothing worked

**Comment by mrworf** [comment]
Seems odd, the image uses the standard raspbian wpa supplicant and the wifi-config.txt is simply included in the wpa application configuration. Perhaps you need country added to it? Closing due to old age.
