### ISSUE TITLE
Stop working

### ISSUE THREAD

**Issue by georgeoftown** [mrworf/photoframe#171]
Thank you for helping making this project better 😅
Running version
commit 1fc3d7cdc81c6486aebc5c56eb7d3346b0ed54fc
Author: Henric Andersson 
Date:   Thu Apr 30 11:22:17 2020 -0700

    Hot fix: Used object which can be null

On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean
Last 100 lines from the photoframe log
Jan  2 08:00:50 photoframe photoframe[557]: display_power=1
(size of logfile 7987 bytes, created Sat Jan 2 11:17:01 2021)
Last 100 lines from the system log (/var/log/syslog)
Jan  2 06:25:01 photoframe liblogging-stdlog:  [origin software="rsyslogd" swVersion="8.24.0" x-pid="293" x-info="http://www.rsyslog.com"] rsyslogd was HUPed
Jan  2 06:41:43 photoframe systemd[1]: plymouth-start.service: Cannot add dependency job, ignoring: Unit plymouth-start.service is masked.
Jan  2 06:41:43 photoframe systemd[1]: Starting Daily apt upgrade and clean activities...
Jan  2 06:41:44 photoframe systemd[1]: Started Daily apt upgrade and clean activities.
Jan  2 06:41:44 photoframe systemd[1]: apt-daily-upgrade.timer: Adding 29min 25.149722s random time.
Jan  2 06:41:44 photoframe systemd[1]: apt-daily-upgrade.timer: Adding 25min 21.992977s random time.
Jan  2 06:53:43 photoframe systemd[1]: plymouth-start.service: Cannot add dependency job, ignoring: Unit plymouth-start.service is masked.
Jan  2 06:53:43 photoframe systemd[1]: Starting Daily apt download activities...
Jan  2 06:53:44 photoframe systemd[1]: Started Daily apt download activities.
Jan  2 06:53:44 photoframe systemd[1]: apt-daily.timer: Adding 6h 39min 15.901377s random time.
Jan  2 06:53:44 photoframe systemd[1]: apt-daily.timer: Adding 10h 47min 49.647559s random time.
Jan  2 07:11:04 photoframe rngd[319]: stats: bits received from HRNG source: 2580064
Jan  2 07:11:04 photoframe rngd[319]: stats: bits sent to kernel pool: 2522560
Jan  2 07:11:04 photoframe rngd[319]: stats: entropy added to kernel pool: 2522560
Jan  2 07:11:04 photoframe rngd[319]: stats: FIPS 140-2 successes: 129
Jan  2 07:11:04 photoframe rngd[319]: stats: FIPS 140-2 failures: 0
Jan  2 07:11:04 photoframe rngd[319]: stats: FIPS 140-2(2001-10-10) Monobit: 0
Jan  2 07:11:04 photoframe rngd[319]: stats: FIPS 140-2(2001-10-10) Poker: 0
Jan  2 07:11:04 photoframe rngd[319]: stats: FIPS 140-2(2001-10-10) Runs: 0
Jan  2 07:11:04 photoframe rngd[319]: stats: FIPS 140-2(2001-10-10) Long run: 0
Jan  2 07:11:04 photoframe rngd[319]: stats: FIPS 140-2(2001-10-10) Continuous run: 0
Jan  2 07:11:04 photoframe rngd[319]: stats: HRNG source speed: (min=730.495; avg=1004.981; max=1162.921)Kibits/s
Jan  2 07:11:04 photoframe rngd[319]: stats: FIPS tests speed: (min=5.240; avg=7.161; max=16.629)Mibits/s
Jan  2 07:11:04 photoframe rngd[319]: stats: Lowest ready-buffers level: 2
Jan  2 07:11:04 photoframe rngd[319]: stats: Entropy starvations: 0
Jan  2 07:11:04 photoframe rngd[319]: stats: Time spent starving for entropy: (min=0; avg=0.000; max=0)us
Jan  2 07:17:01 photoframe CRON[7229]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Jan  2 08:00:50 photoframe photoframe[557]: display_power=1
Jan  2 08:11:04 photoframe rngd[319]: stats: bits received from HRNG source: 2600064
Jan  2 08:11:04 photoframe rngd[319]: stats: bits sent to kernel pool: 2552800
Jan  2 08:11:04 photoframe rngd[319]: stats: entropy added to kernel pool: 2552800
Jan  2 08:11:04 photoframe rngd[319]: stats: FIPS 140-2 successes: 130
Jan  2 08:11:04 photoframe rngd[319]: stats: FIPS 140-2 failures: 0
Jan  2 08:11:04 photoframe rngd[319]: stats: FIPS 140-2(2001-10-10) Monobit: 0
Jan  2 08:11:04 photoframe rngd[319]: stats: FIPS 140-2(2001-10-10) Poker: 0
Jan  2 08:11:04 photoframe rngd[319]: stats: FIPS 140-2(2001-10-10) Runs: 0
Jan  2 08:11:04 photoframe rngd[319]: stats: FIPS 140-2(2001-10-10) Long run: 0
Jan  2 08:11:04 photoframe rngd[319]: stats: FIPS 140-2(2001-10-10) Continuous run: 0
Jan  2 08:11:04 photoframe rngd[319]: stats: HRNG source speed: (min=730.495; avg=1005.056; max=1162.921)Kibits/s
Jan  2 08:11:04 photoframe rngd[319]: stats: FIPS tests speed: (min=5.240; avg=7.160; max=16.629)Mibits/s
Jan  2 08:11:04 photoframe rngd[319]: stats: Lowest ready-buffers level: 2
Jan  2 08:11:04 photoframe rngd[319]: stats: Entropy starvations: 0
Jan  2 08:11:04 photoframe rngd[319]: stats: Time spent starving for entropy: (min=0; avg=0.000; max=0)us
Jan  2 08:17:01 photoframe CRON[7620]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Jan  2 09:11:04 photoframe rngd[319]: stats: bits received from HRNG source: 2640064
Jan  2 09:11:04 photoframe rngd[319]: stats: bits sent to kernel pool: 2582560
Jan  2 09:11:04 photoframe rngd[319]: stats: entropy added to kernel pool: 2582560
Jan  2 09:11:04 photoframe rngd[319]: stats: FIPS 140-2 successes: 132
Jan  2 09:11:04 photoframe rngd[319]: stats: FIPS 140-2 failures: 0
Jan  2 09:11:04 photoframe rngd[319]: stats: FIPS 140-2(2001-10-10) Monobit: 0
Jan  2 09:11:04 photoframe rngd[319]: stats: FIPS 140-2(2001-10-10) Poker: 0
Jan  2 09:11:04 photoframe rngd[319]: stats: FIPS 140-2(2001-10-10) Runs: 0
Jan  2 09:11:04 photoframe rngd[319]: stats: FIPS 140-2(2001-10-10) Long run: 0
Jan  2 09:11:04 photoframe rngd[319]: stats: FIPS 140-2(2001-10-10) Continuous run: 0
Jan  2 09:11:04 photoframe rngd[319]: stats: HRNG source speed: (min=730.495; avg=1005.125; max=1162.921)Kibits/s
Jan  2 09:11:04 photoframe rngd[319]: stats: FIPS tests speed: (min=5.240; avg=7.158; max=16.629)Mibits/s
Jan  2 09:11:04 photoframe rngd[319]: stats: Lowest ready-buffers level: 2
Jan  2 09:11:04 photoframe rngd[319]: stats: Entropy starvations: 0
Jan  2 09:11:04 photoframe rngd[319]: stats: Time spent starving for entropy: (min=0; avg=0.000; max=0)us
Jan  2 09:17:01 photoframe CRON[8005]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Jan  2 10:11:04 photoframe rngd[319]: stats: bits received from HRNG source: 2660064
Jan  2 10:11:04 photoframe rngd[319]: stats: bits sent to kernel pool: 2612800
Jan  2 10:11:04 photoframe rngd[319]: stats: entropy added to kernel pool: 2612800
Jan  2 10:11:04 photoframe rngd[319]: stats: FIPS 140-2 successes: 133
Jan  2 10:11:04 photoframe rngd[319]: stats: FIPS 140-2 failures: 0
Jan  2 10:11:04 photoframe rngd[319]: stats: FIPS 140-2(2001-10-10) Monobit: 0
Jan  2 10:11:04 photoframe rngd[319]: stats: FIPS 140-2(2001-10-10) Poker: 0
Jan  2 10:11:04 photoframe rngd[319]: stats: FIPS 140-2(2001-10-10) Runs: 0
Jan  2 10:11:04 photoframe rngd[319]: stats: FIPS 140-2(2001-10-10) Long run: 0
Jan  2 10:11:04 photoframe rngd[319]: stats: FIPS 140-2(2001-10-10) Continuous run: 0
Jan  2 10:11:04 photoframe rngd[319]: stats: HRNG source speed: (min=730.495; avg=1005.145; max=1162.921)Kibits/s
Jan  2 10:11:04 photoframe rngd[319]: stats: FIPS tests speed: (min=5.240; avg=7.157; max=16.629)Mibits/s
Jan  2 10:11:04 photoframe rngd[319]: stats: Lowest ready-buffers level: 2
Jan  2 10:11:04 photoframe rngd[319]: stats: Entropy starvations: 0
Jan  2 10:11:04 photoframe rngd[319]: stats: Time spent starving for entropy: (min=0; avg=0.000; max=0)us
Jan  2 10:17:01 photoframe CRON[8391]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Jan  2 11:11:04 photoframe rngd[319]: stats: bits received from HRNG source: 2700064
Jan  2 11:11:04 photoframe rngd[319]: stats: bits sent to kernel pool: 2642560
Jan  2 11:11:04 photoframe rngd[319]: stats: entropy added to kernel pool: 2642560
Jan  2 11:11:04 photoframe rngd[319]: stats: FIPS 140-2 successes: 135
Jan  2 11:11:04 photoframe rngd[319]: stats: FIPS 140-2 failures: 0
Jan  2 11:11:04 photoframe rngd[319]: stats: FIPS 140-2(2001-10-10) Monobit: 0
Jan  2 11:11:04 photoframe rngd[319]: stats: FIPS 140-2(2001-10-10) Poker: 0
Jan  2 11:11:04 photoframe rngd[319]: stats: FIPS 140-2(2001-10-10) Runs: 0
Jan  2 11:11:04 photoframe rngd[319]: stats: FIPS 140-2(2001-10-10) Long run: 0
Jan  2 11:11:04 photoframe rngd[319]: stats: FIPS 140-2(2001-10-10) Continuous run: 0
Jan  2 11:11:04 photoframe rngd[319]: stats: HRNG source speed: (min=730.495; avg=1005.180; max=1162.921)Kibits/s
Jan  2 11:11:04 photoframe rngd[319]: stats: FIPS tests speed: (min=5.240; avg=7.155; max=16.629)Mibits/s
Jan  2 11:11:04 photoframe rngd[319]: stats: Lowest ready-buffers level: 2
Jan  2 11:11:04 photoframe rngd[319]: stats: Entropy starvations: 0
Jan  2 11:11:04 photoframe rngd[319]: stats: Time spent starving for entropy: (min=0; avg=0.000; max=0)us
Jan  2 11:17:01 photoframe CRON[8777]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
(size of logfile 7987 bytes, created Sat Jan 2 11:17:01 2021)
Stacktrace of all running threads
# ThreadID: 1973834864
File: "/usr/lib/python2.7/threading.py", line 774, in __bootstrap
  self.__bootstrap_inner()
File: "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  self.run()
File: "/root/photoframe/modules/shutdown.py", line 59, in run
  i = poller.poll(None)

# ThreadID: 1963979888
File: "/usr/lib/python2.7/threading.py", line 774, in __bootstrap
  self.__bootstrap_inner()
File: "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  self.run()
File: "/root/photoframe/modules/timekeeper.py", line 118, in run
  time.sleep(60) # every minute

# ThreadID: 1995684032
File: "./frame.py", line 185, in 
  frame.start()
File: "./frame.py", line 182, in start
  self.webServer.start()
File: "/root/photoframe/modules/server.py", line 84, in start
  self.run()
File: "/root/photoframe/modules/server.py", line 101, in run
  self.app.run(debug=False, port=self.port, host=self.listen )
File: "/usr/lib/python2.7/dist-packages/flask/app.py", line 841, in run
  run_simple(host, port, self, **options)
File: "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 708, in run_simple
  inner()
File: "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 673, in inner
  srv.serve_forever()
File: "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 511, in serve_forever
  HTTPServer.serve_forever(self)
File: "/usr/lib/python2.7/SocketServer.py", line 233, in serve_forever
  self._handle_request_noblock()
File: "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
  self.process_request(request, client_address)
File: "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
  self.finish_request(request, client_address)
File: "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
  self.RequestHandlerClass(request, client_address, self)
File: "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
  self.handle()
File: "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 228, in handle
  rv = BaseHTTPRequestHandler.handle(self)
File: "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
  self.handle_one_request()
File: "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 263, in handle_one_request
  return self.run_wsgi()
File: "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 205, in run_wsgi
  execute(self.server.app)
File: "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 193, in execute
  application_iter = app(environ, start_response)
File: "/usr/lib/python2.7/dist-packages/flask/app.py", line 1997, in __call__
  return self.wsgi_app(environ, start_response)
File: "/usr/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
  response = self.full_dispatch_request()
File: "/usr/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
  rv = self.dispatch_request()
File: "/usr/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
  return self.view_functions[rule.endpoint](**req.view_args)
File: "/root/photoframe/routes/baseroute.py", line 62, in __call__
  return self.handle(self.app, **kwargs)
File: "/root/photoframe/routes/debug.py", line 34, in handle
  report.append(debug.stacktrace())
File: "/root/photoframe/modules/debug.py", line 48, in stacktrace
  for filename, lineno, name, line in traceback.extract_stack(stack):

**Comment by mrworf** [comment]
Well, according to the info you shared, it all seems to work.

Can you provide some details as to what "Stop working" means? What do you see on the frame, what does the web interface show, etc.

**Comment by mrworf** [comment]
Closing since there were no updates.
