### ISSUE TITLE
wpa_supplicant bug fix and dual/dueling? DHCP clients

### ISSUE THREAD

**Issue by dadr** [mrworf/photoframe#174]
When using the 2019-01-05 release image, I see there are two DHCP daemons running, (dhcpcd & dhclient) and also I see two IPv4 addresses on WiFi.  I also found a fix_wifi script.   It's my belief (and experience) that the problem that this script is trying to work around has been fixed in a subsequent release of the wpasupplicant package.  I have seen the original 2.4 version crash.  I've found that upgrading the wpa_supplicant to 2.6 and disabling the fix-wifi service seemed to set things right on the system I was working with.

**Comment by dadr** [comment]
I've done some more digging, and I don't think it's "just" wpasupplicant.   I'm seeing the ifup@wlan0 service fail and then the network service fails because of that.   Disabling the fixwifi service does stop the dual IP address problem, but then the system sometimes gets in a bad state.  Given all this, I would not have opened an issue, so perhaps we should close this one?

If it's any incentive, the network stack is much more robust in Buster  ;-)

**Comment by mrworf** [comment]
It's actually on my todo list, that and Python3 since 2.7 is now deprecated. Work has just been too busy with the pandemic that I've had a hard time to find the time.

We'll see what 2021 brings 😸

**Comment by dadr** [comment]
It's always good to have work.  I avoided asking about Python3.    I have some good ideas for photoframe, but will also need to find the time.   The PC platform is becoming a bigger bite to chew than I thought it would be.  It's pretty clear that it won't be able to run on any PC or any linux.  However, with the Buster distro and Inteldrmfb frame buffer driver, I think it will cover a great many low end PCs - especially NUCs, Chromeboxes, and Thin Clients based on Intel.   

The other thing I wanted to mention is that I've only seen one small problem after a manual install on the latest lite RaspberryPi OS.  The thumbnail in the configuration page doesn't get served.  The URL looks right, it just doesn't return anything.
