### ISSUE TITLE
Failed to wake up 

### ISSUE THREAD

**Issue by dadr** [mrworf/photoframe#188]
Standard photoframe software, did not show pictures at the hour it should have turned on.  Did open a socket for web management, but did not return anything.   I attached the log page, but it seems almost like a system problem.  There seems to be zombie threads for each of my attempts to hit the management page.   It's not clear, but possible that the lux was below the level to turn on the display.  (dark, rainy morning)  After I turned on the lights it seemed to wake up, and also became responsive to the web management page again.
[debug.txt](https://github.com/mrworf/photoframe/files/6211846/debug.txt)

**Comment by mrworf** [comment]
Hmm.. should still have worked when the display is off. Have you experienced this again?

**Comment by dadr** [comment]
I have not seen that one again.  We can close this.
