### ISSUE TITLE
Request: Flag to never update automatically (for installs at far away parent's house)

### ISSUE THREAD

**Issue by jmhammond** [mrworf/photoframe#196]
I setup four photoframes using this software. Two are at my house, so this morning after #195, I was able to manually kick off the update and they're working.

Unfortunately the other two are at my parent's house and my in-laws house and #195 is still affecting them. They're hours away and despite our best efforts, they're not great at following tech directions over the phone... With any luck, the frame should automatically pull from github overnight and they'll be good to go in the morning.

That said, the request: can we have a flag that prevents the system from ever pulling from github automatically?  That way I can still update it manually when I visit but they can remain working for months in between.

**Comment by mrworf** [comment]
Yes, they auto update independently of the main code (so even a completely borked frame should be able to update) . I live in the US and my parents are in Sweden, some 5000 miles away and no ssh or vpn access, so this was crucial to me. I'm really sorry about the bug this morning but tomorrow morning you'll be back in good shape again.

But I hear you, so I'll look into adding the feature. 

On June 27, 2021 7:17:38 PM GMT+02:00, John Hammond ***@***.***> wrote:
>I setup four photoframes using this software. Two are at my house, so
>this morning after #195, I was able to manually kick off the update and
>they're working.
>
>Unfortunately the other two are at my parent's house and my in-laws
>house and #195 is still affecting them. They're hours away and despite
>our best efforts, they're not great at following tech directions over
>the phone... With any luck, the frame should automatically pull from
>github overnight and they'll be good to go in the morning.
>
>That said, the request: can we have a flag that prevents the system
>from ever pulling from github automatically?  That way I can still
>update it manually when I visit but they can remain working for months
>in between.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/mrworf/photoframe/issues/196

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by jmhammond** [comment]
I just realized (after reading through all instances of update.sh) that [it's a cron job](https://github.com/mrworf/photoframe/blob/076dbd50969d35fe92e21d37319836b472f751aa/MANUAL.md#i-want-it-to-auto-update) that calls the daily update, not the python app. 

I just need to remove the relevant line from `/etc/crontab` and I'll be good to go. 

I'll close this issue because this from the install image and nothing to do with the code base.
