### ISSUE TITLE
Expired cert on https://photoframe.sensenet.nu

### ISSUE THREAD

**Issue by 8layer8** [mrworf/photoframe#198]
* Server certificate:
*  subject: CN=*.sensenet.nu
*  start date: Oct 28 15:05:11 2020 GMT
*  expire date: Nov 29 15:05:11 2021 GMT
*  issuer: C=BE; O=GlobalSign nv-sa; CN=AlphaSSL CA - SHA256 - G2
*  SSL certificate verify result: certificate has expired (10), continuing anyway.

I see how to host it myself, and will pursue that in the meantime.

**Comment by mrworf** [comment]
Oups! Forgot to update this server :) My bad, I have the new cert, just didn't push it to this server. 

Thanks for letting me know

**Comment by mrworf** [comment]
Updated
