### ISSUE TITLE
Show slideshow on SPI LCD?

### ISSUE THREAD

**Issue by bkcberry** [mrworf/photoframe#2]
Hello, just wondering if you have any ideas about how to make the slideshow appear on an SPI LCD? I have a 3.5" waveshare LCD. I've tried your pre-built image and also installing manually on raspbian, but the slideshow will only show on HDMI either way. LXDE shows on the LCD, which is on TTY7, and when i SSH in and use 'chvt 1' to switch the LCD to TTY1 it just shows console text.

**Comment by mrworf** [comment]
Hmm, depends. If the SPI LCD shows up as a framebuffer it should be possible to make it work. Look in the `/dev/` for files starting with `fb` ... `fb0` would be the HDMI, question is if your SPI LCD shows up as `fb1` or similar. 

If you have both `fb0` and `fb1` you could try putting random noise on the lcd by issuing `cat /dev/urandom > /dev/fb1`. If that works (the LCD fills with junk), then I think it should be possible to get this working but it may require a few rounds of testing on your part if you're ok with that?

**Comment by mrworf** [comment]
Was it this display? https://www.amazon.com/gp/product/B01N48NOXI ... If so, I ordered one to play with 😄 ... will let you know how it goes

**Comment by bkcberry** [comment]
Haha, yes it was! I'd be happy to help with any testing you still end up needing. I was able to semi get it working with a program called fbcp that copied the framebuffer, but the pics were really distorted. Wasn't sure at that point if it was a problem with the resolution or something else. Since you have minimum values for resolution that are higher than the resolution of that screen I tried setting them manually but that did not help. I also tried creating a custom HDMI resolution but that didn't do anything either.

**Comment by mrworf** [comment]
Sorry for lack of updates, ran into some issues with WiFi while using the SPI display, but a new raspbian version seems to have solved it. Working a new release and after that I'll look into getting the display running.

**Comment by mrworf** [comment]
![image](https://user-images.githubusercontent.com/1848354/41383058-c165967a-6f23-11e8-9ef4-f072d29f33a2.png)
Work in progress 😸

**Comment by mrworf** [comment]
If you want to give it a try, there is a branch called internal-display.

To enable the 3.5" display, do NOT use their installer, it's horrible 😄 just do the following as root:

```
cd to_wherever_the_drivers_are_located
cp waveshare35b-overlay.dtb /boot/overlays/waveshare35b-overlay.dtb
cp waveshare35b-overlay.dtb /boot/overlays/waveshare35b.dtbo
```
then edit the `/boot/config.txt` and add the following lines at the end:
```
dtparam=spi=on
dtoverlay=waveshare35b
```
remove any lines starting the the same keyword

Now, reboot and enjoy... and please let me know how it works

**Comment by bkcberry** [comment]
Awesome! I'm going to take a few mins to check this out this coming week!

**Comment by mrworf** [comment]
Major improvement on this branch today. If you swap to this branch, you'll also find a display-drivers folder, inside of it is a zip file with the 3.5" display drivers. Inside photoframe configuration page it's now possible to upload drivers for the rpi. Yes, it means that it will manipulate your config.txt but it always saves the original and only adds to the end (so it can undo the changes).

End result is that you should be able to upload the correct driver, have it reboot and then it should automatically default to first available display (if any). 

I need to do some more testing (on RPiZ as well as RPi3+) and make sure that updating to this version works, but once that's done, I'm rolling out a new release with this feature enabled as well as making the zip file available for the driver (it's already on github :)). It also means it should be a cinch to support other kinds of fbtft displays and even the 7" waveshare one (https://www.waveshare.com/wiki/7inch_LCD_for_Pi ... and yes, I broke down and ordered it for my RPiZw).

**Comment by mrworf** [comment]
Closing this issue, support is now enabled by default on master. waveshare35b driver package can be found as zipfile in display-drivers folder in the git repo. Use the new install function to enable it on your RPi 😃

**Comment by bkcberry** [comment]
So this is pretty much working for me (with the latest image of raspbian), except all of the colors on the screen are inverted? I used your instructions above to install the drivers for the screen. Any ideas?

 I started over from scratch with minibian since i figured that might be what you used, but it's throwing an error about not being able to load images after i paste in the oauth JSON.

**Comment by bkcberry** [comment]
I got it working! You have the 3.5B screen and I have 3.5A, so that's what was causing the crazy colors. Thanks again main, this is awesome!

**Comment by mrworf** [comment]
Cool! I just finished and uploaded the latest release ( https://github.com/mrworf/photoframe/releases/tag/v1.1.1 ). They're all based on raspbian. It supports the drivers so you can create one for the 3.5" A version if you'd like (see https://github.com/mrworf/photoframe/tree/master/display-drivers for details on how). 

Either way, I'm happy you got it working, feel free to update the wiki with your build (ie, how it looks and such).
