### ISSUE TITLE
Pi on 4K

### ISSUE THREAD

**Issue by sboutros** [mrworf/photoframe#20]
I've tried connecting Pi3 to 2 different 4K screens.
When the frame runs, I get a black border around the image - maybe 150px, all 4 sides.
Is this a Pi/4K issue or is that part of the image rending logic?

**Comment by mrworf** [comment]
My first thought is that you're seeing underscan/overscan, where the pi is purposefully adding a black border to avoid painting outside the visible part. But this is easy to test, if you have a terminal open and you're logged in as root, just issue the following command

```
cat /dev/urandom > /dev/fb0
```
and your screen should fill with random colors. If these don't go all the way out to the border of your screen, then you're looking at underscan/overscan, which you can read more about here https://www.opentechguides.com/how-to/article/raspberry-pi/28/raspi-display-setting.html

Let me know what you find

**Comment by sboutros** [comment]
Yep, turns out it was underscanned. Thanks for the quick save!

**Comment by mrworf** [comment]
If you have time, please share on the wiki on your 4k build/setup since you're the first one I know doing this 😄
