### ISSUE TITLE
Pi Zero 2 W

### ISSUE THREAD

**Issue by b1ane22** [mrworf/photoframe#200]
Trying to boot the pre-built image on the Zero 2 W and does not work. Won’t even boot. I know that the 2W requires the latest OS release, which does work with a new Raspbian image. Will I have to install photoframe manually?

**Comment by dadr** [comment]
The latest Raspberry Pi OS has redone the video driver (in a good way - making it more like garden variety linux systems).
But it also deprecated the tvservice program that managed the old video driver and which is used extensively in photoframe.   

However I *think* you can still get this to work...
You can try the following:  Install manually, and make sure you install the "lite legacy" version of the OS - this should put in the legacy video driver.   I've just finished up another commit to the V2 frame, and if @mrworf accepts it, then you can use the instructions for the "Python3" branch.   If you can't wait, (and if you are willing to try something that may still have bugs) you can follow the instructions in the readme at my working branch: `https://github.com/dadr/photoframe/tree/python3`

The one difference is in the line that clones the repo to the Raspberry pi,  to test use this line instead:
`git clone --branch python3 --single-branch https://github.com/dadr/photoframe.git`
it changes `mrworf` to `dadr` - and for fair warning, you will probably have to install manually again, once this is all ready for production.   However, I'd love to hear your comments and inputs on the new version - especially about any bugs.

I'll try to install on Bullseye as well, and see how that works.  But that will be more than a week from now, I have to go to my brother-in-law's funeral.  (Covid)

**Comment by dadr** [comment]
By the way, I made a photoframe with a Pi 3A which has similar cores and memory, and from that system I think that the Zero 2W will be a great platform for this.

**Comment by b1ane22** [comment]
Thank you! I was trying to install all the packages with python3 but was just getting stuck. 
I just got done installing the branch version and it seems to be working with the web interface, however I can't upload any new display drivers. When I upload through the web portal it says "Upload complete, refreshing drivers" but they're not selectable via the dropdown. Now, on the pi I do see the zip files in `/photoframe/display-drivers` but don't see them in `photoframe_config/display-drivers`.

**Comment by dadr** [comment]
Thanks b1ane22, that might be a bug.  I don't have any systems that use the display drivers, so I have not tested those.  Perhaps @mrworf can give it a try?

**Comment by mrworf** [comment]
It's been a while since I tinkered with that. Can you share logs from this? There should be a bunch of logs to help us with this.

**Comment by b1ane22** [comment]
Absolutely! I am trying to complete another 7" and 5" LCD photoframe for myself and the fiancés' family. The first one I built, I did with just the Zero W and worked perfectly! I see it's trying to extract the zipfile but failing for some reason. I downloaded the sample ones from the `\photoframe\display-drivers` and also tried re-making them manually using the readme file. All failed so far. Here are the log files.
[photoframe log.txt](https://github.com/mrworf/photoframe/files/7884952/photoframe.log.txt)
[stacktrace.txt](https://github.com/mrworf/photoframe/files/7884953/stacktrace.txt)
[sys log.txt](https://github.com/mrworf/photoframe/files/7884954/sys.log.txt)

**Comment by mrworf** [comment]
Hmm... could you be missing `unzip` ? See if `/usr/bin/unzip` exists and works

**Comment by mrworf** [comment]
`sudo apt install unzip` should be the ticket to solve that if that's the case

**Comment by b1ane22** [comment]
`/usr/bin/unzip` did exist. Once I was in `/photoframe/display-drivers` I was able to unzip the files and they're now showing via dropdown on the webpage but once selected doesn't reboot like my working one.

**Comment by b1ane22** [comment]
`Jan 17 18:58:38 raspberrypi photoframe[466]: 2022-01-17 18:58:38,915 - INFO - Registering URL /events/remove/ to RouteEvents
Jan 17 18:58:38 raspberrypi photoframe[466]:  * Serving Flask app "modules.server" (lazy loading)
Jan 17 18:58:38 raspberrypi photoframe[466]:  * Environment: production
Jan 17 18:58:38 raspberrypi photoframe[466]:    WARNING: Do not use the development server in a production environment.
Jan 17 18:58:38 raspberrypi photoframe[466]:    Use a production WSGI server instead.
Jan 17 18:58:38 raspberrypi photoframe[466]:  * Debug mode: off
Jan 17 18:58:48 raspberrypi photoframe[466]: 2022-01-17 18:58:48,971 - INFO - Starting presentation
Jan 17 21:08:07 raspberrypi photoframe[466]: 2022-01-17 21:08:07,273 - ERROR - Failed to extract files from zipfile
Jan 17 22:23:14 raspberrypi photoframe[466]: 2022-01-17 22:23:14,544 - ERROR - Failed to extract files from zipfile
Jan 17 22:24:12 raspberrypi photoframe[466]: 2022-01-17 22:24:12,799 - ERROR - Failed to extract files from zipfile
Jan 17 22:54:32 raspberrypi photoframe[466]: 2022-01-17 22:54:32,029 - ERROR - Failed to load manifest for waveshare7
Jan 17 22:54:32 raspberrypi photoframe[466]: Traceback (most recent call last):
Jan 17 22:54:32 raspberrypi photoframe[466]:   File "/root/photoframe/modules/drivers.py", line 227, in activate
Jan 17 22:54:32 raspberrypi photoframe[466]:     with open(os.path.join(driverlist[driver], 'manifest.json'), 'rb') as f:
Jan 17 22:54:32 raspberrypi photoframe[466]: FileNotFoundError: [Errno 2] No such file or directory: '/root/photoframe/display-drivers/waveshare7/manifest.json'
Jan 17 22:55:21 raspberrypi photoframe[466]: 2022-01-17 22:55:21,032 - ERROR - Failed to load manifest for waveshare35a
Jan 17 22:55:21 raspberrypi photoframe[466]: Traceback (most recent call last):
Jan 17 22:55:21 raspberrypi photoframe[466]:   File "/root/photoframe/modules/drivers.py", line 227, in activate
Jan 17 22:55:21 raspberrypi photoframe[466]:     with open(os.path.join(driverlist[driver], 'manifest.json'), 'rb') as f:
Jan 17 22:55:21 raspberrypi photoframe[466]: FileNotFoundError: [Errno 2] No such file or directory: '/root/photoframe/display-drivers/waveshare35a/manifest.json'
Jan 17 22:55:23 raspberrypi photoframe[466]: 2022-01-17 22:55:23,654 - ERROR - Failed to load manifest for waveshare7`

**Comment by b1ane22** [comment]
Did not mean to close it. Here's the new logs
[photoframe log 1.txt](https://github.com/mrworf/photoframe/files/7885019/photoframe.log.1.txt)
.

**Comment by mrworf** [comment]
what zip file did you upload to the photoframe? Seems like the `manifest.json` file is missing?

**Comment by b1ane22** [comment]
I tried all of them from here [https://github.com/mrworf/photoframe/tree/master/display-drivers](url)

**Comment by mrworf** [comment]
Looking at the code, this file is generated (sorry, it's been a while :)). We need to find out why it can't unzip since there's more to this flow than just unzipping. 

If you feel comfortable editing the files, here's what I propose you do for the `modules/drivers.py`

On line 145, which says
```
result = subprocess.check_call(['/usr/bin/unzip', file, '-d', os.path.join(folder, extra)], stdout=self.void, stderr=self.void)
```
change this to
```
logging.info('path: "%s"', os.path.join(folder, extra))
result = subprocess.check_call(['/usr/bin/unzip', file, '-d', os.path.join(folder, extra)])
```
This should capture the output from the command in syslog and with logging.info we'll know what folder it was trying to unzip to.

Please note that this hasn't been tested, since I'm not at my desktop at the moment, but I believe this will give us the details we need to know what's going on here.

**Comment by b1ane22** [comment]
Okay, so I was able to change the code and I removed all files from `/photoframe/display-drivers` and `/photoframe_config/display-drivers` so we can start fresh. Then I tried uploading the `waveshare7` driver and the `waveshare35a `driver. Now, it actually shows in the dropdown but when I select it, nothing happens. Here are the logs:
[photoframe log 2.txt](https://github.com/mrworf/photoframe/files/7885180/photoframe.log.2.txt)
[sys log 2.txt](https://github.com/mrworf/photoframe/files/7885181/sys.log.2.txt)

**Comment by b1ane22** [comment]
I fixed it! 

In the `drivers.py` code, line 265 needs to be updated from `with open('/boot/config.txt.new', 'wb') as f:` to 			`with open('/boot/config.txt.new', 'w') as f:`

I found it in the syslog:
```
Jan 17 23:46:18 raspberrypi photoframe[467]:   File "/root/photoframe/modules/drivers.py", line 269, in activate
Jan 17 23:46:18 raspberrypi photoframe[467]:     f.write('%s\n' % line)
Jan 17 23:46:18 raspberrypi photoframe[467]: TypeError: a bytes-like object is required, not 'str'
```

Found this link and was able to update and test! I have the 7" LCD finally working as it should!
`https://stackoverflow.com/questions/33054527/typeerror-a-bytes-like-object-is-required-not-str-when-writing-to-a-file-in`
