### ISSUE TITLE
Google Photos Authorisation "no such redirect"

### ISSUE THREAD

**Issue by mnkypshngbttns** [mrworf/photoframe#207]
HI Henric,
I like a few others I see have started to get the need to reauthorise google photos every week or two. Today when I went to reauthorise with the old json client secret file it failed so I tried creating a new one. With the new one I get up the continue to sensenet and then error "no such redirect" and can't authorise. Any ideas on whats happening?
Don't think the log will help but just in case
Dec  8 14:40:46 photoframe rngd[328]: stats: FIPS 140-2(2001-10-10) Monobit: 0
Dec  8 14:40:46 photoframe rngd[328]: stats: FIPS 140-2(2001-10-10) Poker: 0
Dec  8 14:40:46 photoframe rngd[328]: stats: FIPS 140-2(2001-10-10) Runs: 0
Dec  8 14:40:46 photoframe rngd[328]: stats: FIPS 140-2(2001-10-10) Long run: 0
Dec  8 14:40:46 photoframe rngd[328]: stats: FIPS 140-2(2001-10-10) Continuous run: 0
Dec  8 14:40:46 photoframe rngd[328]: stats: HRNG source speed: (min=576.926; avg=815.535; max=1020.601)Kibits/s
Dec  8 14:40:46 photoframe rngd[328]: stats: FIPS tests speed: (min=5.034; avg=7.240; max=16.069)Mibits/s
Dec  8 14:40:46 photoframe rngd[328]: stats: Lowest ready-buffers level: 2
Dec  8 14:40:46 photoframe rngd[328]: stats: Entropy starvations: 0
Dec  8 14:40:46 photoframe rngd[328]: stats: Time spent starving for entropy: (min=0; avg=0.000; max=0)us
Dec  8 14:42:05 photoframe wpa_supplicant[708]: wlan0: WPA: Group rekeying completed with 74:83:c2:c1:7a:2d [GTK=CCMP]
Dec  8 15:17:01 photoframe CRON[29736]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Dec  8 15:40:46 photoframe rngd[328]: stats: bits received from HRNG source: 3380064
Dec  8 15:40:46 photoframe rngd[328]: stats: bits sent to kernel pool: 3332288
Dec  8 15:40:46 photoframe rngd[328]: stats: entropy added to kernel pool: 3332288
Dec  8 15:40:46 photoframe rngd[328]: stats: FIPS 140-2 successes: 169
Dec  8 15:40:46 photoframe rngd[328]: stats: FIPS 140-2 failures: 0
Dec  8 15:40:46 photoframe rngd[328]: stats: FIPS 140-2(2001-10-10) Monobit: 0
Dec  8 15:40:46 photoframe rngd[328]: stats: FIPS 140-2(2001-10-10) Poker: 0
Dec  8 15:40:46 photoframe rngd[328]: stats: FIPS 140-2(2001-10-10) Runs: 0
Dec  8 15:40:46 photoframe rngd[328]: stats: FIPS 140-2(2001-10-10) Long run: 0
Dec  8 15:40:46 photoframe rngd[328]: stats: FIPS 140-2(2001-10-10) Continuous run: 0
Dec  8 15:40:46 photoframe rngd[328]: stats: HRNG source speed: (min=576.926; avg=815.590; max=1020.601)Kibits/s
Dec  8 15:40:46 photoframe rngd[328]: stats: FIPS tests speed: (min=5.034; avg=7.240; max=16.069)Mibits/s
Dec  8 15:40:46 photoframe rngd[328]: stats: Lowest ready-buffers level: 2
Dec  8 15:40:46 photoframe rngd[328]: stats: Entropy starvations: 0
Dec  8 15:40:46 photoframe rngd[328]: stats: Time spent starving for entropy: (min=0; avg=0.000; max=0)us
Dec  8 15:42:05 photoframe wpa_supplicant[708]: wlan0: WPA: Group rekeying completed with 74:83:c2:c1:7a:2d [GTK=CCMP]
Dec  8 16:17:01 photoframe CRON[30122]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Dec  8 16:40:46 photoframe rngd[328]: stats: bits received from HRNG source: 3420064
Dec  8 16:40:46 photoframe rngd[328]: stats: bits sent to kernel pool: 3362048
Dec  8 16:40:46 photoframe rngd[328]: stats: entropy added to kernel pool: 3362048
Dec  8 16:40:46 photoframe rngd[328]: stats: FIPS 140-2 successes: 171
Dec  8 16:40:46 photoframe rngd[328]: stats: FIPS 140-2 failures: 0
Dec  8 16:40:46 photoframe rngd[328]: stats: FIPS 140-2(2001-10-10) Monobit: 0
Dec  8 16:40:46 photoframe rngd[328]: stats: FIPS 140-2(2001-10-10) Poker: 0
Dec  8 16:40:46 photoframe rngd[328]: stats: FIPS 140-2(2001-10-10) Runs: 0
Dec  8 16:40:46 photoframe rngd[328]: stats: FIPS 140-2(2001-10-10) Long run: 0
Dec  8 16:40:46 photoframe rngd[328]: stats: FIPS 140-2(2001-10-10) Continuous run: 0
Dec  8 16:40:46 photoframe rngd[328]: stats: HRNG source speed: (min=576.926; avg=815.688; max=1020.601)Kibits/s
Dec  8 16:40:46 photoframe rngd[328]: stats: FIPS tests speed: (min=5.034; avg=7.238; max=16.069)Mibits/s
Dec  8 16:40:46 photoframe rngd[328]: stats: Lowest ready-buffers level: 2
Dec  8 16:40:46 photoframe rngd[328]: stats: Entropy starvations: 0
Dec  8 16:40:46 photoframe rngd[328]: stats: Time spent starving for entropy: (min=0; avg=0.000; max=0)us
Dec  8 16:42:05 photoframe wpa_supplicant[708]: wlan0: WPA: Group rekeying completed with 74:83:c2:c1:7a:2d [GTK=CCMP]
Dec  8 17:17:01 photoframe CRON[30509]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Dec  8 17:40:46 photoframe rngd[328]: stats: bits received from HRNG source: 3440064
Dec  8 17:40:46 photoframe rngd[328]: stats: bits sent to kernel pool: 3392288
Dec  8 17:40:46 photoframe rngd[328]: stats: entropy added to kernel pool: 3392288
Dec  8 17:40:46 photoframe rngd[328]: stats: FIPS 140-2 successes: 172
Dec  8 17:40:46 photoframe rngd[328]: stats: FIPS 140-2 failures: 0
Dec  8 17:40:46 photoframe rngd[328]: stats: FIPS 140-2(2001-10-10) Monobit: 0
Dec  8 17:40:46 photoframe rngd[328]: stats: FIPS 140-2(2001-10-10) Poker: 0
Dec  8 17:40:46 photoframe rngd[328]: stats: FIPS 140-2(2001-10-10) Runs: 0
Dec  8 17:40:46 photoframe rngd[328]: stats: FIPS 140-2(2001-10-10) Long run: 0
Dec  8 17:40:46 photoframe rngd[328]: stats: FIPS 140-2(2001-10-10) Continuous run: 0
Dec  8 17:40:46 photoframe rngd[328]: stats: HRNG source speed: (min=576.926; avg=815.738; max=1020.601)Kibits/s
Dec  8 17:40:46 photoframe rngd[328]: stats: FIPS tests speed: (min=5.034; avg=7.237; max=16.069)Mibits/s
Dec  8 17:40:46 photoframe rngd[328]: stats: Lowest ready-buffers level: 2
Dec  8 17:40:46 photoframe rngd[328]: stats: Entropy starvations: 0
Dec  8 17:40:46 photoframe rngd[328]: stats: Time spent starving for entropy: (min=0; avg=0.000; max=0)us
Dec  8 17:42:06 photoframe wpa_supplicant[708]: wlan0: WPA: Group rekeying completed with 74:83:c2:c1:7a:2d [GTK=CCMP]
Dec  8 17:43:17 photoframe systemd[1]: plymouth-start.service: Cannot add dependency job, ignoring: Unit plymouth-start.service is masked.
Dec  8 17:43:17 photoframe systemd[1]: Starting Daily apt download activities...
Dec  8 17:43:18 photoframe systemd[1]: Started Daily apt download activities.
Dec  8 17:43:18 photoframe systemd[1]: apt-daily.timer: Adding 10h 20min 48.324736s random time.
Dec  8 17:43:18 photoframe systemd[1]: apt-daily.timer: Adding 9h 2min 22.265907s random time.
Dec  8 18:17:01 photoframe CRON[30939]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Dec  8 18:40:46 photoframe rngd[328]: stats: bits received from HRNG source: 3480064
Dec  8 18:40:46 photoframe rngd[328]: stats: bits sent to kernel pool: 3422048
Dec  8 18:40:46 photoframe rngd[328]: stats: entropy added to kernel pool: 3422048
Dec  8 18:40:46 photoframe rngd[328]: stats: FIPS 140-2 successes: 174
Dec  8 18:40:46 photoframe rngd[328]: stats: FIPS 140-2 failures: 0
Dec  8 18:40:46 photoframe rngd[328]: stats: FIPS 140-2(2001-10-10) Monobit: 0
Dec  8 18:40:46 photoframe rngd[328]: stats: FIPS 140-2(2001-10-10) Poker: 0
Dec  8 18:40:46 photoframe rngd[328]: stats: FIPS 140-2(2001-10-10) Runs: 0
Dec  8 18:40:46 photoframe rngd[328]: stats: FIPS 140-2(2001-10-10) Long run: 0
Dec  8 18:40:46 photoframe rngd[328]: stats: FIPS 140-2(2001-10-10) Continuous run: 0
Dec  8 18:40:46 photoframe rngd[328]: stats: HRNG source speed: (min=576.926; avg=815.817; max=1020.601)Kibits/s
Dec  8 18:40:46 photoframe rngd[328]: stats: FIPS tests speed: (min=5.034; avg=7.236; max=16.069)Mibits/s
Dec  8 18:40:46 photoframe rngd[328]: stats: Lowest ready-buffers level: 2
Dec  8 18:40:46 photoframe rngd[328]: stats: Entropy starvations: 0
Dec  8 18:40:46 photoframe rngd[328]: stats: Time spent starving for entropy: (min=0; avg=0.000; max=0)us
Dec  8 18:42:06 photoframe wpa_supplicant[708]: wlan0: WPA: Group rekeying completed with 74:83:c2:c1:7a:2d [GTK=CCMP]
Dec  8 19:17:01 photoframe CRON[31324]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Dec  8 19:40:46 photoframe rngd[328]: stats: bits received from HRNG source: 3500064
Dec  8 19:40:46 photoframe rngd[328]: stats: bits sent to kernel pool: 3452288
Dec  8 19:40:46 photoframe rngd[328]: stats: entropy added to kernel pool: 3452288
Dec  8 19:40:46 photoframe rngd[328]: stats: FIPS 140-2 successes: 175
Dec  8 19:40:46 photoframe rngd[328]: stats: FIPS 140-2 failures: 0
Dec  8 19:40:46 photoframe rngd[328]: stats: FIPS 140-2(2001-10-10) Monobit: 0
Dec  8 19:40:46 photoframe rngd[328]: stats: FIPS 140-2(2001-10-10) Poker: 0
Dec  8 19:40:46 photoframe rngd[328]: stats: FIPS 140-2(2001-10-10) Runs: 0
Dec  8 19:40:46 photoframe rngd[328]: stats: FIPS 140-2(2001-10-10) Long run: 0
Dec  8 19:40:46 photoframe rngd[328]: stats: FIPS 140-2(2001-10-10) Continuous run: 0
Dec  8 19:40:46 photoframe rngd[328]: stats: HRNG source speed: (min=576.926; avg=815.866; max=1020.601)Kibits/s
Dec  8 19:40:46 photoframe rngd[328]: stats: FIPS tests speed: (min=5.034; avg=7.235; max=16.069)Mibits/s
Dec  8 19:40:46 photoframe rngd[328]: stats: Lowest ready-buffers level: 2
Dec  8 19:40:46 photoframe rngd[328]: stats: Entropy starvations: 0
Dec  8 19:40:46 photoframe rngd[328]: stats: Time spent starving for entropy: (min=0; avg=0.000; max=0)us

**Comment by mnkypshngbttns** [comment]
The "no such redirect" comes after clicking continue on the 
sensenet.nu wants access to your Google Account page

**Comment by mrworf** [comment]
Hmm, no, this doesn't provide much to go on. Does your browser's console hold any hints?
