### ISSUE TITLE
http://photoframe.sensenet.nu/ connection refused

### ISSUE THREAD

**Issue by adambarnett52** [mrworf/photoframe#209]
This morning i lost authorization ( same as #201 ) i uploaded by json like normal but i am getting a connect refused to http://photoframe.sensenet.nu/ 

Is the service down, 

Thanks

![image](https://user-images.githubusercontent.com/5599251/222095393-11c4ebf4-2ace-4af9-ad55-aa2bb028399e.png)

**Comment by mrworf** [comment]
Sorry, we had multiple outages here in the Bay, including internet (lots of storms) so the reverse proxy had failed to start (due to lack of external IP). I've started it again and now it's working.

Again sorry for the inconvenience

**Comment by adambarnett52** [comment]
Amazing. Thanks

**Comment by shermanpark** [comment]
Awesome - thank you!Sent from my iPhoneOn Mar 4, 2023, at 2:20 PM, adambarnett52 ***@***.***> wrote:﻿
Amazing. Thanks
