### ISSUE TITLE
Image pool

### ISSUE THREAD

**Issue by sboutros** [mrworf/photoframe#21]
I have 4 keywords that return images from Google Photos. 
Have around 50k photos to pick from.
Refresh list of photos every 1 hours

I see very minimal change in the image pool. Despite running all day, rebooting, ./update/force, etc.
Am I missing something?

Is there a single pool, comprised of all the keywords or does each keyword have its own pool?

**Comment by mrworf** [comment]
Did you try those keywords on https://photos.google.com ?

I typically have it set to refresh after 24 or 48hrs. Refresh essentially forces the frame to query google and fetch the list of photos again thus clearing out the internal tracking of "photos I've shown".

**Comment by sboutros** [comment]
Yep keywords generate image results.
I am also getting images that don't match any keywords (deleted keywords) - is it possible they are still stuck in a list somewhere?

Also is there a single pool, comprised of all the keywords or does each keyword have its own pool?

**Comment by mrworf** [comment]
Each line is a query which returns a list of images, this list is then run though using random to find an element which it can show and it hasn't shown before. So if you have two lines with `henric landscape` and `europe` for example, it will download two lists based off these two queries. 

You could try rebooting in-case it for some reason got stuck and didn't realize that a query was deleted.

Lastly, by accessing `http://<the ip of your frame>:7777/debug` it will show the last 100 entries which relate to the frame software, in case something fishy is going on. Please post it here (or upload a text file with the entries) and we'll see if can give us a clue.

**Comment by sboutros** [comment]
Understood, thanks. Attached 2 files.

[debug.txt](https://github.com/mrworf/photoframe/files/2479768/debug.txt)
[debug-all.txt](https://github.com/mrworf/photoframe/files/2479769/debug-all.txt)

**Comment by mrworf** [comment]
There seems to be some issues where a certain keyword yields zero images causing an exception.  This might be the old keyword you mentioned before. As for the rest, there are plenty of `Seen XXX, expected to see YYY` entries which is the memory logic running and the XXX counting upward towards YYY which is correct.

**Comment by mrworf** [comment]
Is this still an issue? Did you try disabling the refresh, forcing it to iterate through all pictures before restarting?
