### ISSUE TITLE
Add transitions

### ISSUE THREAD

**Issue by jabellas** [mrworf/photoframe#23]
First of all, thanks for such a great photoframe software. Was super-easy to set up and now I can finish my photoframe build.  I have a current photoframe that I am using with windows XP and an ancient google screensaver. I have kept using it because it has the 'Ken Burns effect' -dissolve between pictures, zoom and pan-as a transition which is a really elegant way to deal with multiple resolutions and aspect rations. 

I am not sure a Raspberry Pi has enough video processing oomph to do that but even a simple dissolve would be a nice addition.

**Comment by mrworf** [comment]
Unfortunately I'm currently rending directly to the display/framebuffer without any hardware acceleration, so at this point it will not be possible to do transitions. While I do like the idea it would be difficult to do while still supporting things like smaller displays which aren't running of HDMI.
