### ISSUE TITLE
Rotate the "slideshow"...

### ISSUE THREAD

**Issue by Snille** [mrworf/photoframe#25]
Hi! Thank you for this nice setup! 
I'm currently trying to set up my second frame. But I want to use it in portrait mode.
I have rotated the display in the config.txt. I know that it's correct. I have other RPis with the same function but not using them as a photoframes (rotating the display 270 degrees with "display_rotate=3"). 

However the "slideshow" still displays the picture as if it where in landscape mode.
Is there a way to define a new "screen mode" (720x1280) somehow?
All options available in the WebGUI is in landscape mode.

Best regards Erik

**Comment by mrworf** [comment]
UI will always show the landscape options since that's what's being reported by the underlying DVI/HDMI connection. However, the display_rotate=3 "should" work since I know other people are using that. 

I know you have other machines doing this, but could you try using raspbian or similar and try the same thing? Just copy the config.txt to the distro and see that it works.

**Comment by Snille** [comment]
I'll give it a new try on a fresh install. I'll let you know. :)

**Comment by mrworf** [comment]
Thanks 😸

**Comment by Snille** [comment]
Ok, here is the results...
I started with a normal Rasbian on the Pi 2.
I only changed in the /boot/config.txt adding the line "display_rotate=3"
Booted and all looked good.
![image](https://user-images.githubusercontent.com/1011699/49080700-c749ca80-f244-11e8-94f9-710d7e02d8e9.png)

The I "etched" the Photoframe image to another SD-Card.
Changed in the /boot/wifi-config.txt so that the frame would conned to my wifi.
Added the same line in the /boot/config.txt as above.
Booted, and it "looks" ok.
![image](https://user-images.githubusercontent.com/1011699/49080670-ada88300-f244-11e8-9dd8-2aec29a1c324.png)

When it boots, I flip over to the console just to show that the frame is in portrait mode first.
But then when the slideshow actually starts something happens... See the short video.
https://photos.app.goo.gl/kaVupG29PDSBFssW7
I have "fast-forwarded" some parts just to save time... :)
I reboot the frame at the end with "CTRL+ALT+Delete" just to show that now, the console is in landscape mode for some reson...

I'm hoping I have missed something. :)

Best regards Erik

**Comment by mrworf** [comment]
I wonder... I think part of viewing a photo it may reinit the display using fbset, which may cause the rpi to get the wrong size. Essentially it's not understanding that width and height are swapped.

I'll see what I can do about that. Thanks for testing and for providing the video that helped a lot.

**Comment by Snille** [comment]
Hi again, unfortunately the fix did not work as expected. The rotation seam to be ok now.
But the picture gets skewed up in some way...
![image](https://user-images.githubusercontent.com/1011699/49798700-36deb000-fd43-11e8-8b9f-c92603f05e34.png)

Here is a short clip again of the boot: https://photos.app.goo.gl/paJvj32mWx6388BS9
Let me know if I should test something else?

Best regards Erik

**Comment by mrworf** [comment]
I know what the issue is, when rotated, the width of a pixel row isn't "exactly" the same as what fbset reports, ie, it reports 1080x1920 but in reality it was 1088x1920 (width must be dividable by 16). I added this logic, but it seems that RPi2 is different from RPi3, so I must find a way to programmatically determine this. This why webui looks ok but actual display is not

**Comment by Snille** [comment]
Ok, no problem, here is the result: 
pi@photoframe03:~ $ fbset -i

mode "800x1280"
    geometry 800 1280 800 1280 32
    timings 0 0 0 0 0 0 0
    rgba 8/16,8/8,8/0,8/24
endmode

Frame buffer device information:
    Name        : BCM2708 FB
    Address     : 0x3e42a000
    Size        : 4096000
    Type        : PACKED PIXELS
    Visual      : TRUECOLOR
    XPanStep    : 1
    YPanStep    : 1
    YWrapStep   : 0
    LineLength  : 3200
    Accelerator : No
pi@photoframe03:~ $

**Comment by Snille** [comment]
This is the same result form a "Landscape" frame, just for reference:
pi@photoframe02:~ $ fbset -i

mode "1280x800"
    geometry 1280 800 1280 800 32
    timings 0 0 0 0 0 0 0
    rgba 8/16,8/8,8/0,8/24
endmode

Frame buffer device information:
    Name        : BCM2708 FB
    Address     : 0x1e812000
    Size        : 4096000
    Type        : PACKED PIXELS
    Visual      : TRUECOLOR
    XPanStep    : 1
    YPanStep    : 1
    YWrapStep   : 0
    LineLength  : 5120
    Accelerator : No
pi@photoframe02:~ $

**Comment by mrworf** [comment]
I see, no need to align at that resolution. And my suspicion about line length holds up, so hopefully I can get that fixed today. Thanks

**Comment by mrworf** [comment]
I should have fixed it now, if you're able to, do a `git pull` on the project and try again.

**Comment by Snille** [comment]
Looking good!! It's working! :)
![image](https://user-images.githubusercontent.com/1011699/49816950-5095ec80-fd6f-11e8-8b1c-01ea77fc76cb.png)
****
![image](https://user-images.githubusercontent.com/1011699/49817020-78855000-fd6f-11e8-92f7-9cbba60d8943.png)

Thank you!!

**Comment by mrworf** [comment]
YAY!

**Comment by mrworf** [comment]
Feel free to add some details about your frame and hardwork on the [wiki](https://github.com/mrworf/photoframe/wiki) for this project. Helps inspire others to dive into this 😃
