### ISSUE TITLE
Outh redirect error

### ISSUE THREAD

**Issue by salomoro** [mrworf/photoframe#26]
i got this error,  i this uri still working?
https://photoframe.sensenet.nu

Error: redirect_uri_mismatch
The redirect URI in the request, https://photoframe.sensenet.nu, does not match the ones authorized for the OAuth client. To update the authorized redirect URIs, visit:

**Comment by mrworf** [comment]
It should look like this in the Google console:
![image](https://user-images.githubusercontent.com/1848354/48731123-24180600-ebf1-11e8-934c-832f2bf7563e.png)
(blue highlight added by me)

If it doesn't say `https://photoframe.sensenet.nu` then you get that error back during the OAuth process.

**Comment by salomoro** [comment]
Hi HenricIt works,...i did like you describe, but  it was not working until a few days bevor.thanksRobertoAm 19.11.2018 20:50 schrieb Henric Andersson <notifications@github.com>:It should look like this in the Google console:

(blue highlight added by me)
If it doesn't say https://photoframe.sensenet.nu then you get that error back during the OAuth process.

**Comment by mrworf** [comment]
Glad to hear it :)
