### ISSUE TITLE
Can't find images

### ISSUE THREAD

**Issue by Notyou98** [mrworf/photoframe#28]
If I test key words, it goes to my photos, and allows me to search. I added a search parameter, and if i open it is successively searches my photos. I have authorized and reauthorized my account several times. The pictures still don't show up. if i use the default search that automatically goes to the last picture, and test it i get "Error 404 The requested URL was not found on this server." I also can't change the timezone. It always goes back to default.

**Comment by rafik24** [comment]
I have the same issue, I have enabled debug and get:

2018-12-08 18:33:39,442 - DEBUG - https://picasaweb.google.com:443 "GET /data/feed/api/user/default?max-results=1000&kind=photo&start-index=1&fields=entry%28title%2Ccontent%2Cgphoto%3Atimestamp%2Cgphoto%3Avideostatus%29&imgmax=1600u&access=all&alt=json HTTP/1.1" 200 None
2018-12-08 18:33:39,456 - ERROR - Failed to load images
Traceback (most recent call last):
  File "/root/photoframe/modules/slideshow.py", line 249, in getImages
    logging.debug('Loaded %d images into list' % len(images['feed']['entry']))
KeyError: 'entry'

Can you please help ?

**Comment by mrworf** [comment]
Looking into it

**Comment by mrworf** [comment]
Can you guys share the EXACT query you're setting in photoframe which isn't working. Maybe it has characters which cause issues when I ask google.

**Comment by rafik24** [comment]
Hi Henric,

Thank you for looking into this.

I had a go today and all seem to work when I set a filter keyword, however it did not the last 2 days.

Seem like google API does not like the empty filter keyword.

Great project you have done, Thank you !

Thanks,
Rafik

**Comment by Notyou98** [comment]
I tried the default blank, and class. class is the album name. I also have several photos not in the album that I named class in an effort to get them to be found.

**Comment by brewer-michael** [comment]
I had this issue until I pulled out the blank search for recent images. Since I could pull up images with a keyword, I figured that might be causing it. Sure enough, stripping out the blank search brought up my photos. Now to figure out why the screen goes dark every little while...

**Comment by mrworf** [comment]
@brewer-michael So you're saying the default query is what caused one of your issues?

**Comment by brewer-michael** [comment]
@mrworf it seems that way. Instead of pulling in recent messages, I was getting a black screen saying a network or configuration occurred. After I pulled that out, it successfully brought in images for the "sun" keyword I entered below the default. BTW thanks for your work on this! It's working great

**Comment by mrworf** [comment]
I think this all boils down to the old Picasa API, it's notorious for being so-so when asked for the latest photos. Work is being done to add the new API and allowing you to use a mix of source (old/new api, multiple accounts, etc). 

Please don't hesitate to open new issues for any other problems you're encountering.

**Comment by brewer-michael** [comment]
Yeah I was reading that in some of the other issues. At some point when life allows I want to grab the project and look over it. Being able to throw images on a network share would be really cool, and I have another Pi set up as a Nextcloud server with a shared drive so I would have a leg up on setup for that.

**Comment by mrworf** [comment]
Closing this now since the issue was resolved
