### ISSUE TITLE
Move shutdown GPIO or make configurable?

### ISSUE THREAD

**Issue by kaigoth** [mrworf/photoframe#3]
First off, thanks for the work on this!

Would love to see the GPIO for the power off switch be made configurable via the interface.

I built using an original RPi with stretch lite. I'm using the original instead of the 3 due to the lower power reqs (and I had a couple lying around). With a USB Nano WiFi adapter the USB port on my monitor (HP E221i) seems to power it without issue. (Note: I tried several Dell models, none of the USB ports provide power.) I have a model 3 that definitely does not like the lower power output from the monitor and I get undervoltage errors overwriting the display and causing issues. The original might not like it either, but it doesn't seem to be complaining. Just REALLY slow to start displaying pictures after first boot, and the fastest it seems to switch between photos is ~1:30 regardless of setting. Not having a second power cord is worth it though, IMO.

Anyways, because I'm using an original RPi, I don't have GPIO 26. I will use another GPIO and modify "shutdown.py" accordingly, however I would also like to use the update feature (especially if you plan to add flickr support). I expect my manual change will get overwritten sooner or later though. It would be much easier if this were a configurable option in the browser.

Again, thanks for the awesome app!

**Comment by mrworf** [comment]
I'm glad you like it and it's cool it works on the older RPi as well. And yeah, like you noticed, the image processing will unfortunately be slow but at least it works 😄 

Customization of the GPIO is a good idea, so I'll try to have that done next week. WIll update when done

_Btw, feel free to create a page on the wiki with details of your frame build so others can see your amazing work 😉_

**Comment by mrworf** [comment]
Good catch on #2, the first one is interesting because I get the defaults by asking the HDMI driver, so that would be interesting to troubleshoot. I'll get back with instructions on that if you're up for it 😸

**Comment by mrworf** [comment]
So it seems I reversed two options in the method getting the current state of the connection.

**Comment by mrworf** [comment]
All stuff mentioned here should be fixed now 😄 let me know how it works

**Comment by kaigoth** [comment]
Awesome, thanks!
I see the GPIO option (will test tomorrow). Oddly enough, I'm getting ambient numbers now too! Not sure if anything you updated would have caused that?

"Current ambient environment 39.32 lux and 2453K color temperature."

**Comment by kaigoth** [comment]
Changing the GPIO works halfway! I am able to shut down, but not power up.

**Comment by mrworf** [comment]
Power Up is unfortunately something which is RPi hardware specific. For more details, check out https://howchoo.com/g/mwnlytk3zmm/how-to-add-a-power-button-to-your-raspberry-pi

**Comment by kaigoth** [comment]
Ahh, thanks!

**Comment by kaigoth** [comment]
Finally finished my first build, was going to add it to the wiki but don't seem to have permission.

**Comment by mrworf** [comment]
Try now

**Comment by kaigoth** [comment]
Working, will write something up!

**Comment by mrworf** [comment]
Cool 😄 looking forward to it 😸

**Comment by shigadeyo** [comment]
Are these the correct switches to use for the power off/on function?
https://www.ebay.com/itm/382548037696/
