### ISSUE TITLE
Remotely Update Keywords

### ISSUE THREAD

**Issue by brewer-michael** [mrworf/photoframe#33]
Is there any semi-API functionality already in place where I could send new keywords to the frame via web request? That way I could perhaps contact the frame without having to load the settings in a browser.

**Comment by mrworf** [comment]
The html page uses /keywords/add with a json where the key is keywords. This is done using a post request 

Getting /keywords will provide a list of existing keywords and posting a json to /keywords/delete where id references an ID from previous rest api will delete it. 

⁣Sent from TypeApp ​

**Comment by brewer-michael** [comment]
Thanks @mrworf !

**Comment by mrworf** [comment]
If I remember, you should do a HTTP POST and provide a JSON containing the id and when you get all keywords, they should include two fields, keywords and id

**Comment by brewer-michael** [comment]
So you are saying a GET to /keywords should return both keywords and ids?
If I run `curl -i -H "Accept: application/json" -H "Content-Type: application/json" -X GET http://localhost:7777/keywords`

I get
`{
    "keywords": [
        "sun"
    ]
}`

I tried modifying frame.py to get id, ids, and a couple other variations but that just came back null.

**Comment by mrworf** [comment]
Thinking back, it might be as simple as id being an index to the array you got, so zero would be the first keyword in the list.

**Comment by brewer-michael** [comment]
I thought of that, but after adding an additional keyword and trying to remove id=1 by sending variants of the following just returned a "status" :false
`curl -i -H "Accept: application/json" -H "Content-Type: application/json" -data {"id":"1"} -X POST http://192.168.1.113:7777/keywords/delete`

**Comment by mrworf** [comment]
I honestly don't remember how this work :) Why don't you use the dev mode of firefox/chrome and simply look at the request made when deleting a keyword. I'll dig deeper into it this weekend, but for now that should give you the answer you seek

**Comment by brewer-michael** [comment]
Will do! I've been trying to anticipate what the id would be from what it is doing in settings.py, but that sounds like an easier route!
`def getKeyword(self, id=None):
		if id is None:
			rnd = random.SystemRandom().randint(0, len(self.settings['cfg']['keywords'])-1)
			return rnd # self.settings['cfg']['keywords'][rnd]
		elif id >= 0 and id < len(self.settings['cfg']['keywords']):
			return self.settings['cfg']['keywords'][id]
		else:
			return None

	def countKeywords(self):
		return len(self.settings['cfg']['keywords'])`

**Comment by brewer-michael** [comment]
Eureka! Firefox for some reason is the only client that is returning the ids. Everything else is just showing the keywords. They do increment based on their position in the array for 0, 1, 2, 3, etc. Thanks for the Firefox suggestion
