### ISSUE TITLE
Contributed photos do not appear

### ISSUE THREAD

**Issue by roboticsguy1988** [mrworf/photoframe#35]
I created an Google Photo album called "TestPhotoFrame" for example. I then used the keyword "TestPhotoFrame" in your software, which was able to find all the photos i had put in the album. I then added a contributor to that album. The contributor added their own photos to that same album and yet they do not show up under that keyword.  It appears google doesn't add that "tag" to photos contributed to an album.

Is there a way to either allow me to point the software to one specific album or to get the contributed photos to show up?

Also it would be nice to add a button to force it to sync with google photos.

Finally, is there a limit to the number of photos? I assume this downloads all the photos from the album and then displays them or does it load each photo from the web each time?

**Comment by bjarnemagnussen** [comment]
When searching using as keyword the album (or "opening" with the keyword from the photoframe manager itself), Google Photos only shows my own pictures and does not show contributed/shared pictures, even though they exist in the album. Do you think this will be fixed when updating to GooglePhotos API? I have tried to look for a change in the settings, but nothing shows up that helps.

**Comment by mrworf** [comment]
In a few days you'll be able to test, the google photos integration is almost done. Hopefully it solves the issue.

**Comment by mrworf** [comment]
Integration is merged, in 24hrs (depending on your time zone) the frame will autoupdate, please try the new Google Photos integration and see if it solves the issue

**Comment by mrworf** [comment]
The "Open" option has not been fixed, it always uses the picasaweb interfaces which is why it doesn't make any sense.

Always add albums without quotes to the google photos provider. The open option will be fixed in a few days.

**Comment by mrworf** [comment]
@Snille I opened #41 for tracking the real issue and I'm now closing this one since it (this issue's problem) has been resolved.
