### ISSUE TITLE
SSLError when run from systemd

### ISSUE THREAD

**Issue by bkcberry** [mrworf/photoframe#37]
If i run photoframe.sh from terminal, everything works as expected. When systemd starts it after a reboot, though, it freezes and the log shows the errors below:

> -- Logs begin at Tue 2018-12-25 18:35:03 GMT, end at Tue 2018-12-25 18:35:55 GMT. --
> Dec 25 18:35:11 raspberrypi systemd[1]: Started Photo Frame.
> Dec 25 18:35:29 raspberrypi photoframe[499]: 2018-12-25 18:35:29,926 - INFO - No http-auth.json found, disabling http authentication
> Dec 25 18:35:30 raspberrypi photoframe[499]: 2018-12-25 18:35:30,038 - INFO - No SMB subsystem, color sensor unavailable
> Dec 25 18:35:53 raspberrypi photoframe[499]: 2018-12-25 18:35:53,255 - INFO - Starting presentation
> Dec 25 18:35:53 raspberrypi photoframe[499]: 2018-12-25 18:35:53,264 - ERROR - No result returned!
> Dec 25 18:35:54 raspberrypi photoframe[499]: 2018-12-25 18:35:54,842 - ERROR - Issues downloading
> Dec 25 18:35:54 raspberrypi photoframe[499]: Traceback (most recent call last):
> Dec 25 18:35:54 raspberrypi photoframe[499]:   File "/root/photoframe/modules/oauth.py", line 64, in request
> Dec 25 18:35:54 raspberrypi photoframe[499]:     result = auth.get(uri, stream=stream, params=params)
> Dec 25 18:35:54 raspberrypi photoframe[499]:   File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 501, in get
> Dec 25 18:35:54 raspberrypi photoframe[499]:     return self.request('GET', url, **kwargs)
> Dec 25 18:35:54 raspberrypi photoframe[499]:   File "/usr/lib/python2.7/dist-packages/requests_oauthlib/oauth2_session.py", line 358, in request
> Dec 25 18:35:54 raspberrypi photoframe[499]:     headers=headers, data=data, **kwargs)
> Dec 25 18:35:54 raspberrypi photoframe[499]:   File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
> Dec 25 18:35:54 raspberrypi photoframe[499]:     resp = self.send(prep, **send_kwargs)
> Dec 25 18:35:54 raspberrypi photoframe[499]:   File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
> Dec 25 18:35:54 raspberrypi photoframe[499]:     r = adapter.send(request, **kwargs)
> Dec 25 18:35:54 raspberrypi photoframe[499]:   File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 497, in send
> Dec 25 18:35:54 raspberrypi photoframe[499]:     raise SSLError(e, request=request)
> Dec 25 18:35:54 raspberrypi photoframe[499]: SSLError: ("bad handshake: Error([('', 'osrandom_rand_bytes', 'getrandom() initialization failed.')],)",)
> Dec 25 18:35:54 raspberrypi photoframe[499]: Exception in thread Thread-4:
> Dec 25 18:35:54 raspberrypi photoframe[499]: Traceback (most recent call last):
> Dec 25 18:35:54 raspberrypi photoframe[499]:   File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
> Dec 25 18:35:54 raspberrypi photoframe[499]:     self.run()
> Dec 25 18:35:54 raspberrypi photoframe[499]:   File "/usr/lib/python2.7/threading.py", line 754, in run
> Dec 25 18:35:54 raspberrypi photoframe[499]:     self.__target(*self.__args, **self.__kwargs)
> Dec 25 18:35:54 raspberrypi photoframe[499]:   File "/root/photoframe/modules/slideshow.py", line 101, in presentation
> Dec 25 18:35:54 raspberrypi photoframe[499]:     result = self.services.servicePrepareNextItem(svc, filename, ['image/jpeg'], {'width' : self.settings.getUser('width'), 'height'
> Dec 25 18:35:54 raspberrypi photoframe[499]:   File "/root/photoframe/modules/servicemanager.py", line 268, in servicePrepareNextItem
> Dec 25 18:35:54 raspberrypi photoframe[499]:     return svc.prepareNextItem(destinationFile, supportedMimeTypes, displaySize)
> Dec 25 18:35:54 raspberrypi photoframe[499]:   File "/root/photoframe/services/svc_googlephotos.py", line 52, in prepareNextItem
> Dec 25 18:35:54 raspberrypi photoframe[499]:     result = self.fetchImage(destinationFile, supportedMimeTypes, displaySize)
> Dec 25 18:35:54 raspberrypi photoframe[499]:   File "/root/photoframe/services/svc_googlephotos.py", line 86, in fetchImage
> Dec 25 18:35:54 raspberrypi photoframe[499]:     result = self.requestUrl(imageUrl, destination=destinationFile)
> Dec 25 18:35:54 raspberrypi photoframe[499]:   File "/root/photoframe/services/base.py", line 286, in requestUrl
> Dec 25 18:35:54 raspberrypi photoframe[499]:     result = self._OAUTH.request(url, destination, params, data=data, usePost=usePost)
> Dec 25 18:35:54 raspberrypi photoframe[499]:   File "/root/photoframe/modules/oauth.py", line 94, in request
> Dec 25 18:35:54 raspberrypi photoframe[499]:     return {'status':result.status_code, 'content':result.content}
> Dec 25 18:35:54 raspberrypi photoframe[499]: AttributeError: 'NoneType' object has no attribute 'status_code'
> 

Did i miss something?
Merry Christmas!

**Comment by mrworf** [comment]
See https://gitlab.com/librespacefoundation/satnogs/satnogs-client-ansible/issues/29 ... I solved it on the image for Photoframe by installing the rng-tools package which makes sure there's enough entropy for the random generator.

**Comment by bkcberry** [comment]
Awesome, installing that package took care of those errors.. but now this one is happening:

> -- Logs begin at Thu 2016-11-03 17:16:42 GMT, end at Wed 2018-12-26 05:00:44 GMT. --
> Dec 26 00:57:57 raspberrypi systemd[1]: Started Photo Frame.
> Dec 26 01:00:38 raspberrypi photoframe[493]: 2018-12-26 01:00:38,606 - INFO - No http-auth.json found, disabling http authentication
> Dec 26 01:00:38 raspberrypi photoframe[493]: 2018-12-26 01:00:38,887 - INFO - No SMB subsystem, color sensor unavailable
> Dec 26 01:00:52 raspberrypi photoframe[493]: 2018-12-26 01:00:52,611 - INFO - Starting presentation
> Dec 26 01:00:54 raspberrypi photoframe[493]: Exception in thread Thread-4:
> Dec 26 01:00:54 raspberrypi photoframe[493]: Traceback (most recent call last):
> Dec 26 01:00:54 raspberrypi photoframe[493]:   File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
> Dec 26 01:00:54 raspberrypi photoframe[493]:     self.run()
> Dec 26 01:00:54 raspberrypi photoframe[493]:   File "/usr/lib/python2.7/threading.py", line 754, in run
> Dec 26 01:00:54 raspberrypi photoframe[493]:     self.__target(*self.__args, **self.__kwargs)
> Dec 26 01:00:54 raspberrypi photoframe[493]:   File "/root/photoframe/modules/slideshow.py", line 101, in presentation
> Dec 26 01:00:54 raspberrypi photoframe[493]:     result = self.services.servicePrepareNextItem(svc, filename, ['image/jpeg'], {'width' : self.settings.getUser('width'), Dec 26 01:00:54 raspberrypi photoframe[493]:   File "/root/photoframe/modules/servicemanager.py", line 268, in servicePrepareNextItem
> Dec 26 01:00:54 raspberrypi photoframe[493]:     return svc.prepareNextItem(destinationFile, supportedMimeTypes, displaySize)
> Dec 26 01:00:54 raspberrypi photoframe[493]:   File "/root/photoframe/services/svc_googlephotos.py", line 52, in prepareNextItem
> Dec 26 01:00:54 raspberrypi photoframe[493]:     result = self.fetchImage(destinationFile, supportedMimeTypes, displaySize)                                              Dec 26 01:00:54 raspberrypi photoframe[493]:   File "/root/photoframe/services/svc_googlephotos.py", line 79, in fetchImage
> Dec 26 01:00:54 raspberrypi photoframe[493]:     images = self.getImagesFor(keyword)
> Dec 26 01:00:54 raspberrypi photoframe[493]:   File "/root/photoframe/services/svc_googlephotos.py", line 191, in getImagesFor
> Dec 26 01:00:54 raspberrypi photoframe[493]:     params = self.translateKeywordToId(keyword)                                                                             Dec 26 01:00:54 raspberrypi photoframe[493]:   File "/root/photoframe/services/svc_googlephotos.py", line 146, in translateKeywordToId                                   Dec 26 01:00:54 raspberrypi photoframe[493]:     print "Album: " + data['albums'][i]['title']                                                                            Dec 26 01:00:54 raspberrypi photoframe[493]: UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 13: ordinal not in range(128)                ~                                                                                                                                                                        ~                                                                                                                                                                        ~                                                                                                                                                                        ~
> ~
> ~
> ~
> lines 1-24/24 (END)

**Comment by bkcberry** [comment]
Seems like u2019 is a quotation mark, but I haven't added any quotes around my album name

**Comment by bkcberry** [comment]
Working now, thanks!
