### ISSUE TITLE
Ambient Status Display...

### ISSUE THREAD

**Issue by kaigoth** [mrworf/photoframe#4]
Sensor is working, there are noticeable changes to the images displayed when the ambient light is changed. The status in the browser never changes though.

"Current ambient environment -.-- lux and ----K color temperature."

Any clues for troubleshooting would be appreciated! Would like to use ambient power save feature, but would be nice to see current readings when setting this up.

Thanks!

**Comment by mrworf** [comment]
Can you open the javascript console and reload the page and see if you get any errors?

**Comment by kaigoth** [comment]
After updating I refreshed and I now see numbers!

"Current ambient environment 30.74 lux and 2613K color temperature."

Not sure if maybe I had a corrupted config somewhere, but this is no longer a problem. Thanks!

**Comment by mrworf** [comment]
I snuck in a a change to avoid browser caching on files sent from the web server, that could very well have fixed it 😜

**Comment by kaigoth** [comment]
Thanks!
