### ISSUE TITLE
Problem with new GooglePhotos Provider

### ISSUE THREAD

**Issue by hpheuer** [mrworf/photoframe#40]
I went through your (very well documented!) "How to create an authorization file" for GooglePhotos and added the authorization to PhotoFrame, but nothing was displayed. No pictures were found:
[DebugTrace.txt](https://github.com/mrworf/photoframe/files/2716551/DebugTrace.txt)

Thanks for your great app and your help!

**Comment by mrworf** [comment]
I think you just need to add an album name to the config, or simply add "latest" to get the latest 1000 photos (no quotes). That's what the logfile suggests. I guess the text on the screen should be more clear that you need to add albums to the configuration.

This is what mine look like:
![image](https://user-images.githubusercontent.com/1848354/50540854-61f03e80-0b4e-11e9-8a7e-92b189cf9f5a.png)

**Comment by hpheuer** [comment]
Thanks! The "latest" keyword worked for me too. It seems that GooglePhotos is now picking photos randomly, the same way as with the Picasa provider. I'm happy.

Some people in my family didn't like the blurred background. Maybe you could add an option, to have a black background. I helped myself by removing most of the parameters in the "convert"-call in the helper.py file. But this is of course not very professional.

Thanks again for your fast help!

**Comment by mrworf** [comment]
It's your lucky day @hpheuer, I added and pushed that feature right now. If you force an update you should get a new option to play with.
