### ISSUE TITLE
issues with Google Photo Api 

### ISSUE THREAD

**Issue by anasna83** [mrworf/photoframe#45]
Hi ! Thanks for the update !  I moved to google photo api, however, there are some issues occurs, sometimes the frame stuck on an image, and some time it stuck on a black screen, then I have to reboot and after that awhile happens again. 

I have around 25 albums , each one have around 200 photos (some photos shared in multiple albums)  , I tried to remove some of them and stays on fewer albums but it still happening ?  Are there any specific rules for the albums using this api ?  I used these albums on the previous api with no problems.

Thanks again

**Comment by mrworf** [comment]
When it's black or stuck, does the web interface still work? If so, when that happens, can you get logs? Just point your webbrowser to the address of your frame but add /debug to the url and you should get the last 100 lines. Please post them here and let's see if we can solve this.

**Comment by anasna83** [comment]
I found what is the difference between the albums that stuck with the others. The albums were created by Google Photo Assistant and they are sectioned (or sorted ) based on city/place, so when open them on google photo there are sections like this: 

<img width="1229" alt="screen shot 2018-12-29 at 9 32 56 pm" src="https://user-images.githubusercontent.com/11182650/50543880-d3ada400-0bb1-11e9-9e78-21f9904d52b9.png">
<img width="1231" alt="screen shot 2018-12-29 at 9 33 08 pm-2" src="https://user-images.githubusercontent.com/11182650/50543910-ccd36100-0bb2-11e9-902a-03737bbf4f24.png">

so I ended up by creating the albums again without the assistant help and now frame works perfectly !

Thank you

**Comment by mrworf** [comment]
From the logs though it looks like you're using an older version of photoframe. You may want to update because the newest one uses Google Photos API which may solve the issue.

**Comment by anasna83** [comment]
ok thanks , will give it a try

**Comment by mrworf** [comment]
Let me know how it went.

**Comment by anasna83** [comment]
I made force update , its no longer stuck.  Thank you ! I like the behavior of picasa api more, using google photo api makes photos sometimes repeated and not totally random, and in large albums many photos didn't show up for once in the last two days. is this totally related to their api ? Thank you again

**Comment by mrworf** [comment]
The random/repeat issue you're seeing seems to be a photoframe problem. Hopefully should have that fixed soon.

**Comment by anasna83** [comment]
After testing for around 1 hour it looks no repeating and randomized well ! thanks 

I found this on the debug "WARNING - Unsupported media: image/png"
should all images be *.jpg ?

**Comment by mrworf** [comment]
I think I just forgot to add support for the more common ones, for now it prefers jpeg but I'll add png and a few others as well. Closing this issue since it seems to work as expected now.
