### ISSUE TITLE
Photos from Google not really random

### ISSUE THREAD

**Issue by hpheuer** [mrworf/photoframe#46]
Thanks for the enhancement. I've played around adding some albums and it really looks great. 

When I'm just using the "latest"-keyword, the infinite wisdom of Google's AI keeps repeating some images instead of showing all of them just once in a random order. I'm not sure, if you have any chance to change this behaviour.

Maybe there's a way to configure Google to display just all photos independent of any album assocication? That could be the PhotoFrame default configuration, if no album name is given.

**Comment by mrworf** [comment]
So I think the logic for tracking shown images might not be 100% robust, especially when photos show up twice with different IDs. I noticed it too so I'll have a look and see what's going on.

**Comment by mrworf** [comment]
The latest change uses a different tracker for which photos that have been shown. Please let me know if it works better now.

**Comment by hpheuer** [comment]
All fixed. The changes solved the problem. The system runs perfect. I'm happy
