### ISSUE TITLE
FR: Allow caching of images

### ISSUE THREAD

**Issue by roboticsguy1988** [mrworf/photoframe#47]
One feature that would be useful is the option to cache images. Every set amount of time the photo frame would then compared the cached images with the latest list and either download new photos or delete photos that are no longer on the list.

This would come in handy for photo frames using a limited connection such as a cellular connection.  This also adds another question does the software support a wired pi connection? Does it support the cellular CDMA or GSM hat on the pi?

**Comment by mrworf** [comment]
This could lead to a tremendous amount of images stored locally, the "latest" option alone will cause 1000 images to be cached. It would also eat a potentially large amount of storage (which might not be an issue all things considered with 128GB sd cards and what not).

But I don't see how this would cut down on data, if you download 1000 pictures immediately or one by one, it's still 1000 pictures. Worse still, if your album changes often enough it would throw away potentially 100s of pictures.

Now, what could be done is cache the images shown and unless the list of photos change, it simply reuses the already downloaded images.

Another option is to use local storage for all the photos you want to show, but that requires support from photoframe.

**Comment by roboticsguy1988** [comment]
What you said in the third paragraph is what I would be looking for.
Basically I would save all the images once over WiFi or a wired connection
and then take the photo frame to the remote location to run over a cellular
connection. The only time it would download any photos would be if there
was a change such as a photo being added or deleted. They would be stored
on a large microsd card.

It would definitely help save on data. If your frame went through 1000
photos a day then you would be downloading 1000 photos a day. But if you
saved them then you would only have the first download after that it would
only download changes.

I used the term caching originally. Since that is more of a term for
temporary storage I'll just say save or store.

**Comment by mrworf** [comment]
This is a more complicated solution since I would need to track the age of each image, so do not expect it in the near future.

**Comment by roboticsguy1988** [comment]
Why would you need to track the age? You would compare to the list every
time.

So if the list starts out as 1,2,3,4,5 then two days later this list
changes to 1,2,5,9,10,12 then you would remove photos 3 and 4 and add
photos 9, 10, and 12.

**Comment by mrworf** [comment]
You're right, I was still thinking caching in the traditional sense

**Comment by drlimbo** [comment]
@mrworf Any plans to cache the images locally?
We'd love to use the photoframe for an Art-Project, but we don't have a stable internet connection there =( The idea of a local cache would be awesome!

**Comment by mrworf** [comment]
It's a bit lower on my list of things to do, tbh. But it will eventually make it :)

**Comment by leogaube** [comment]
@mrworf: I can take this feature request off your hands. I am actually already working on it!
Should be done sometime next week ;)

**Comment by drlimbo** [comment]
@leogaube how is your work going on? any news about local caching?

**Comment by leogaube** [comment]
I am already done. However, it is a pretty big update, because it includes other features as well. that's why I wanted to take my time for testing/bug fixes. A
Pull request with a detailed explanation will be coming tomorrow.

**Comment by mrworf** [comment]
Finally merged, should now cache photos as they're shown thanks to @leogaube
