### ISSUE TITLE
Every other image not following 

### ISSUE THREAD

**Issue by jfoster832** [mrworf/photoframe#48]
I have a weird issue we almost every other image pull I get a issue showing image check network or settings message. The the next image it pulls.  I tried resetting the pi 3 b+ to default and reloaded the image and same result the raspberry pi is sitting like 8 ft from the access point so I am unsure what's going on.  The syslog is filled with this message over and over.

Dec 30 21:52:01 photoframe photoframe[546]: 2018-12-30 21:52:01,789 - ERROR - Fail$Dec 30 21:52:01 photoframe photoframe[546]: Traceback (most recent call last):     Dec 30 21:52:01 photoframe photoframe[546]:   File "/root/photoframe/modules/slide$Dec 30 21:52:01 photoframe photoframe[546]:     logging.debug('Loaded %d images in$Dec 30 21:52:01 photoframe photoframe[546]: KeyError: 'entry'

**Comment by mrworf** [comment]
Try forcing an update from the web ui

⁣Sent from TypeApp ​

**Comment by jfoster832** [comment]
I guess I was using a older version as there was no force update button on the interface.  I left the unit plugged in overnight for the first time and it updated itself and seemed to resolve all the issues with this.  Thanks!
