### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by vetmiker** [mrworf/photoframe#49]
I'm getting a 500 "Internal Server Error" at the end of the OAuth process (after I authorize in Google) connecting to Google Photos, after following the directions listed. Any idea where I might be going wrong?

I am on release 1.2.0 on Raspberry Pi 3 B+.

Thanks!

-Mike

**Comment by mrworf** [comment]
What's the URL in the browser window?

**Comment by vetmiker** [comment]
I did a hard reset of the device, looked at the log files more, then figured out that in Google Console I needed to enable "Photos Library API" first, then everything worked. I think this step is missing from your setup doc here: https://mrworf.github.io/photoframe/2018/02/26/setting-up-photoframe.html

This ticket can be closed. I should have done more research before I submitted it - my apologies!!

This is a great project - thank you for your effort and time you've put into this!!!

-Mike

**Comment by mrworf** [comment]
Thanks for letting me know which instructions you were following. I updated them to point out that they don't apply anymore.
