### ISSUE TITLE
Compatibility with Raspberry Pi Zero (WH)?

### ISSUE THREAD

**Issue by bjarnemagnussen** [mrworf/photoframe#5]
Hi, 
I want to know if photoframe is compatible also with Raspberry Pi Zero? Has someone tried it? Or is there something in this build that makes it exclusively available for Raspberry Pi 3?

Edit: I should add I am also referring to the ready build under releases.

**Comment by mrworf** [comment]
It works, but there are some general kinks in the ready build which can cause problems. I'm working a new build which solves these but it's a week or two out before I can get it done.

**Comment by mrworf** [comment]
Doing final testing today, hopefully a new release uploaded within the next 8hrs :)

**Comment by bjarnemagnussen** [comment]
Sounds fantastic! Unfortunately I haven't received my Raspberry Pi Zero yet, otherwise I would like to offer my help testing it immediately. :)

**Comment by mrworf** [comment]
And it's out. New release which works fine with RPi Zero Wireless :) Let me know how it works out once you've gotten your board.

**Comment by mrworf** [comment]
Closing this issue, please file new issue if you're running into problems with your RPi

**Comment by bjarnemagnussen** [comment]
I have finally found the time to build my photoframe with a Raspberry Pi Zero using your image and it works perfectly! Thousand thanks for all your work! And merry christmas!
