### ISSUE TITLE
Power saving with schedule only (without sensor)

### ISSUE THREAD

**Issue by anasna83** [mrworf/photoframe#50]
I'm trying to make the frame turn Off at 2 A.M and On at 8 A.M without using the sensor, like this:

<img width="499" alt="screen shot 2018-12-31 at 7 38 09 pm" src="https://user-images.githubusercontent.com/11182650/50569494-39299e00-0d34-11e9-914e-4ce88469712e.png">

However, the function doesn't work properly , I tried different times and sometimes it works fine. it looks like if the turn off time is at "A.M"  (or maybe if both times in A.M) it won't work, would you please take a look on that. Thanks again :)

**Comment by mrworf** [comment]
@anasna83 Let me know if the latest update fixed it

**Comment by anasna83** [comment]
Working perfectly ! Thanks
