### ISSUE TITLE
Getting errors this morning on my keywords.

### ISSUE THREAD

**Issue by Snille** [mrworf/photoframe#52]
Good morning! :)
I'm getting errors on all my frame this morning...
In the Log:
`Jan  2 09:08:19 photoframe03 photoframe[539]: 2019-01-02 09:08:19,425 - INFO - Starting presentation
Jan  2 09:08:19 photoframe03 photoframe[539]: 2019-01-02 09:08:19,439 - ERROR - Unable to create query the keyword "Fotoram Louise"
Jan  2 09:08:20 photoframe03 photoframe[539]: 2019-01-02 09:08:20,632 - ERROR - Unable to create query the keyword "Fotoram Louise"
Jan  2 09:08:22 photoframe03 photoframe[539]: 2019-01-02 09:08:22,546 - ERROR - Unable to create query the keyword "Fotoram Louise"
Jan  2 09:08:23 photoframe03 photoframe[539]: 2019-01-02 09:08:23,814 - ERROR - Unable to create query the keyword "Fotoram Louise"`

On screen: 
![image](https://user-images.githubusercontent.com/1011699/50584352-56af5280-0e6f-11e9-9890-dc54ce068295.png)

The album name is correct: Fotoram Louise
![image](https://user-images.githubusercontent.com/1011699/50584388-94ac7680-0e6f-11e9-98b1-39855e32dc4d.png)

The "Open" button now works by the way! 

Happy New Year! :)

**Comment by Snille** [comment]
I just found out that it's a case issue.
If I add the name of the album in lower case only, it works again.

**Comment by mrworf** [comment]
Got a bunch of fixes on testing now in the majorfixings branch, which addresses the lower/upper case issue among other things. Should also migrate existing keywords to new format.

**Comment by Snille** [comment]
Now working, all keywords get's added in lower case. :)
