### ISSUE TITLE
Issue with slideshow freezing. 

### ISSUE THREAD

**Issue by JTJaneway** [mrworf/photoframe#57]
I'm still new to this and learning, but do not see any information about it on here. I am having an issue with the slideshow freezing when it goes through all the pictures.

**Comment by mrworf** [comment]
Two questions:
- It freezes after all photos have been shown or just randomly?
- Define freeze. Does the web UI still work but the screen is black?

**Comment by JTJaneway** [comment]
As far as freezing it shows and image from the selected folder, but wont change. There are two versions of the issue I have experienced now. Sometimes it shows one image and never changes. The other is that it will play a slideshow of images in the selected folder, but once every image has been shown it will freeze on the final image and not continue changing. Web UI still shows whichever image is being displayed.

**Comment by mrworf** [comment]
And you are using the ready made image from this site or did you install it manually?

**Comment by mrworf** [comment]
And you are using the ready made image from this site or did you install it manually?

**Comment by mrworf** [comment]
Okay, then you're on the latest version which is good to know. 

Can you post the output from this page:
http://<your frame's IP>:7777/debug/

**Comment by JTJaneway** [comment]
Jan 15 21:58:39 photoframe photoframe[432]:   File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
Jan 15 21:58:39 photoframe photoframe[432]:     self.wfile.close()
Jan 15 21:58:39 photoframe photoframe[432]:   File "/usr/lib/python2.7/socket.py", line 283, in close
Jan 15 21:58:39 photoframe photoframe[432]:     self.flush()
Jan 15 21:58:39 photoframe photoframe[432]:   File "/usr/lib/python2.7/socket.py", line 307, in flush
Jan 15 21:58:39 photoframe photoframe[432]:     self._sock.sendall(view[write_offset:write_offset+buffer_size])
Jan 15 21:58:39 photoframe photoframe[432]: error: [Errno 32] Broken pipe
Jan 15 22:06:40 photoframe photoframe[532]: 2019-01-15 22:06:40,942 - INFO - ColorSensor not available
Jan 15 22:07:04 photoframe photoframe[532]: 2019-01-15 22:07:04,997 - INFO - Starting presentation
Jan 15 22:09:04 photoframe photoframe[532]: Traceback (most recent call last):
Jan 15 22:09:04 photoframe photoframe[532]:   File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
Jan 15 22:09:04 photoframe photoframe[532]:     self.process_request(request, client_address)
Jan 15 22:09:04 photoframe photoframe[532]:   File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
Jan 15 22:09:04 photoframe photoframe[532]:     self.finish_request(request, client_address)
Jan 15 22:09:04 photoframe photoframe[532]:   File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
Jan 15 22:09:04 photoframe photoframe[532]:     self.RequestHandlerClass(request, client_address, self)
Jan 15 22:09:04 photoframe photoframe[532]:   File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
Jan 15 22:09:04 photoframe photoframe[532]:     self.finish()
Jan 15 22:09:04 photoframe photoframe[532]:   File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
Jan 15 22:09:04 photoframe photoframe[532]:     self.wfile.close()
Jan 15 22:09:04 photoframe photoframe[532]:   File "/usr/lib/python2.7/socket.py", line 283, in close
Jan 15 22:09:04 photoframe photoframe[532]:     self.flush()
Jan 15 22:09:04 photoframe photoframe[532]:   File "/usr/lib/python2.7/socket.py", line 307, in flush
Jan 15 22:09:04 photoframe photoframe[532]:     self._sock.sendall(view[write_offset:write_offset+buffer_size])
Jan 15 22:09:04 photoframe photoframe[532]: error: [Errno 32] Broken pipe
Jan 15 22:12:20 photoframe photoframe[532]: 2019-01-15 22:12:20,015 - ERROR - Issues downloading
Jan 15 22:12:20 photoframe photoframe[532]: Traceback (most recent call last):
Jan 15 22:12:20 photoframe photoframe[532]:   File "/root/photoframe/modules/oauth.py", line 64, in request
Jan 15 22:12:20 photoframe photoframe[532]:     result = auth.get(uri, stream=stream, params=params)
Jan 15 22:12:20 photoframe photoframe[532]:   File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 501, in get
Jan 15 22:12:20 photoframe photoframe[532]:     return self.request('GET', url, **kwargs)
Jan 15 22:12:20 photoframe photoframe[532]:   File "/usr/lib/python2.7/dist-packages/requests_oauthlib/oauth2_session.py", line 358, in request
Jan 15 22:12:20 photoframe photoframe[532]:     headers=headers, data=data, **kwargs)
Jan 15 22:12:20 photoframe photoframe[532]:   File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
Jan 15 22:12:20 photoframe photoframe[532]:     resp = self.send(prep, **send_kwargs)
Jan 15 22:12:20 photoframe photoframe[532]:   File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
Jan 15 22:12:20 photoframe photoframe[532]:     r = adapter.send(request, **kwargs)
Jan 15 22:12:20 photoframe photoframe[532]:   File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 497, in send
Jan 15 22:12:20 photoframe photoframe[532]:     raise SSLError(e, request=request)
Jan 15 22:12:20 photoframe photoframe[532]: SSLError: ("bad handshake: SysCallError(-1, 'Unexpected EOF')",)
Jan 15 22:29:04 photoframe photoframe[532]: Traceback (most recent call last):
Jan 15 22:29:04 photoframe photoframe[532]:   File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
Jan 15 22:29:04 photoframe photoframe[532]:     self.process_request(request, client_address)
Jan 15 22:29:04 photoframe photoframe[532]:   File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
Jan 15 22:29:04 photoframe photoframe[532]:     self.finish_request(request, client_address)
Jan 15 22:29:04 photoframe photoframe[532]:   File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
Jan 15 22:29:04 photoframe photoframe[532]:     self.RequestHandlerClass(request, client_address, self)
Jan 15 22:29:04 photoframe photoframe[532]:   File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
Jan 15 22:29:04 photoframe photoframe[532]:     self.finish()
Jan 15 22:29:04 photoframe photoframe[532]:   File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
Jan 15 22:29:04 photoframe photoframe[532]:     self.wfile.close()
Jan 15 22:29:04 photoframe photoframe[532]:   File "/usr/lib/python2.7/socket.py", line 283, in close
Jan 15 22:29:04 photoframe photoframe[532]:     self.flush()
Jan 15 22:29:04 photoframe photoframe[532]:   File "/usr/lib/python2.7/socket.py", line 307, in flush
Jan 15 22:29:04 photoframe photoframe[532]:     self._sock.sendall(view[write_offset:write_offset+buffer_size])
Jan 15 22:29:04 photoframe photoframe[532]: error: [Errno 32] Broken pipe
Jan 15 22:25:48 photoframe photoframe[660]: 2019-01-15 22:25:48,110 - INFO - ColorSensor not available
Jan 15 22:32:41 photoframe photoframe[660]: 2019-01-15 22:32:41,358 - INFO - Starting presentation
Jan 15 22:50:25 photoframe photoframe[660]: 2019-01-15 22:50:25,583 - WARNING - Unsupported media: video/mp4
Jan 15 22:51:26 photoframe photoframe[660]: 2019-01-15 22:51:26,826 - INFO - Interim saving of memory every 20 entries
Jan 15 23:16:59 photoframe photoframe[387]: 2019-01-15 23:16:59,424 - INFO - ColorSensor not available
Jan 15 23:17:36 photoframe photoframe[387]: 2019-01-15 23:17:36,457 - INFO - Starting presentation
Jan 15 23:36:57 photoframe photoframe[387]: 2019-01-15 23:36:57,427 - INFO - Interim saving of memory every 20 entries
Jan 15 23:56:09 photoframe photoframe[387]: 2019-01-15 23:56:09,901 - ERROR - Issues downloading
Jan 15 23:56:09 photoframe photoframe[387]: Traceback (most recent call last):
Jan 15 23:56:09 photoframe photoframe[387]:   File "/root/photoframe/modules/oauth.py", line 64, in request
Jan 15 23:56:09 photoframe photoframe[387]:     result = auth.get(uri, stream=stream, params=params)
Jan 15 23:56:09 photoframe photoframe[387]:   File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 501, in get
Jan 15 23:56:09 photoframe photoframe[387]:     return self.request('GET', url, **kwargs)
Jan 15 23:56:09 photoframe photoframe[387]:   File "/usr/lib/python2.7/dist-packages/requests_oauthlib/oauth2_session.py", line 358, in request
Jan 15 23:56:09 photoframe photoframe[387]:     headers=headers, data=data, **kwargs)
Jan 15 23:56:09 photoframe photoframe[387]:   File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
Jan 15 23:56:09 photoframe photoframe[387]:     resp = self.send(prep, **send_kwargs)
Jan 15 23:56:10 photoframe photoframe[387]:   File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
Jan 15 23:56:10 photoframe photoframe[387]:     r = adapter.send(request, **kwargs)
Jan 15 23:56:10 photoframe photoframe[387]:   File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 487, in send
Jan 15 23:56:10 photoframe photoframe[387]:     raise ConnectionError(e, request=request)
Jan 15 23:56:10 photoframe photoframe[387]: ConnectionError: HTTPSConnectionPool(host='lh3.googleusercontent.com', port=443): Max retries exceeded with url: /lr/AJ-Ewvl2NTEzNVXvFtlE52ysxaxUl_WZP7Kk7gbZNY2Umt-ZLzex4biXFPlsn6dEfcE2lorVFLfuLfkEzAwSG1AcOMg1g5lXFqRybZFKh5HqdHVeZ3wNv-ftB4OPTPKMJrQk4Jtdf8gioMv4ma1ihNDvgSlPd7WQf6A3E_Jk1addenNcju7FQokzk6tEBbGoRGZJ34CQ3xxDKkV2Uzw1xIJbZErn2LTCKto-0DKC9MerZaJuKIvwyZYYwebSImt3Y87Ahq0LTJRGbs2_CMU7LtJLgJPBRXvUIrzrc2IkKu2TNAMQVyIEUMR95j_6tsLd_3y7oUT9vC1NbVRzHW-Oq6Ur9fy0IAaFwDVJYGVmCsDsWlJxkXqsZt-Uy2JMKMDoFqUGZJdAP7v3VPsevINqHcyvv0gPj2arGxFqwZe5XHaketsCk80mrfYREGCnsr0ZjaKwlma1LiqeFXUR4tYuuyuXAnJYBMBjpiR8gXizoc0CaezOgl3p3la_YQuPgvYG8HZk4jfN9Qqcl8QuvM4_R6KgWNvty1Thm8Xd8gbe6AN8ecTRZDP1lQfSll76wPrnxAX9l47dxeR2rDayKN1a-eMGTXJRR4TVinbyWG9iefmcO8mxmGvZErPMCQFcZcoQSNro3oOWj3vlMSM3TT1qR6M6x5UMkroJ5yJjeqlVnB5Lrrx1safJ2aSYJtEAEFYMIbisL3SaEM5AHihaht7LfdWxRw00fLcHouSW96CofiCRocRNgWI7umcOgF41PdFFkGsgeKLj_72JE5R6vImLBFBnkveYpUHqpm0JYM4qRWAMBGS2mqSsS7Nud25NJJd0RGwFX61Rl9dNxZLUJf68KdO-qqVokEpOGQTLFBtdsIMPueVQP9n24JFe2SWwGQVHKjfi=w1080-h1080 (Caused by NewConnectionError(': Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
Jan 16 00:45:03 photoframe photoframe[387]: display_power=0
Jan 16 00:45:08 photoframe photoframe[387]: display_power=1
Jan 16 00:46:14 photoframe photoframe[524]: 2019-01-16 00:46:14,850 - INFO - ColorSensor not available
Jan 16 00:46:50 photoframe photoframe[524]: 2019-01-16 00:46:50,848 - INFO - Starting presentation
Jan 16 01:24:23 photoframe photoframe[654]: 2019-01-16 01:24:23,454 - INFO - ColorSensor not available
Jan 16 01:24:47 photoframe photoframe[654]: 2019-01-16 01:24:47,539 - INFO - Starting presentation
Jan 16 01:25:26 photoframe photoframe[654]: 2019-01-16 01:25:26,504 - WARNING - Requesting photo failed with status code 401
Jan 16 01:25:26 photoframe photoframe[654]: 2019-01-16 01:25:26,519 - WARNING - More details: '{\n  "error": {\n    "code": 401,\n    "message": "Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.",\n    "status": "UNAUTHENTICATED"\n  }\n}\n'
Jan 16 01:25:26 photoframe photoframe[654]: 2019-01-16 01:25:26,525 - ERROR - No result returned for keyword "album 1"!
Jan 16 15:49:52 photoframe photoframe[654]: 2019-01-16 15:49:52,544 - INFO - Change of configuration, flush data and restart
Jan 16 15:49:52 photoframe photoframe[654]: Exception in thread Thread-4:
Jan 16 15:49:52 photoframe photoframe[654]: Traceback (most recent call last):
Jan 16 15:49:52 photoframe photoframe[654]:   File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
Jan 16 15:49:52 photoframe photoframe[654]:     self.run()
Jan 16 15:49:52 photoframe photoframe[654]:   File "/usr/lib/python2.7/threading.py", line 754, in run
Jan 16 15:49:52 photoframe photoframe[654]:     self.__target(*self.__args, **self.__kwargs)
Jan 16 15:49:52 photoframe photoframe[654]:   File "/root/photoframe/modules/slideshow.py", line 150, in presentation
Jan 16 15:49:52 photoframe photoframe[654]:     os.remove(self.imageCurrent)
Jan 16 15:49:52 photoframe photoframe[654]: OSError: [Errno 2] No such file or directory: '/tmp/image'
Jan 16 15:51:50 photoframe photoframe[660]: 2019-01-16 15:51:50,316 - INFO - ColorSensor not available
Jan 16 15:52:25 photoframe photoframe[660]: 2019-01-16 15:52:25,570 - INFO - Starting presentation
Binary file /var/log/syslog matches

**Comment by mrworf** [comment]
It seems that the client authentication has expired. Do you still have the OAuth 2.0 client id listed under https://console.developers.google.com/apis/credentials ?

**Comment by JTJaneway** [comment]
I redid the authentication in the web UI and it ran fine for about an hour and a half. There are 30 photos in the album and it is set to change every 60 seconds. So I would assume it went through every photo at least once? It has again though stopped and not continued cycling through.

**Comment by mrworf** [comment]
and if you check the log, does it again mention error 401 or similar? Once the frame updates (happens every night) I've added a new debug mode, so try /debug/stacktrace instead of just /debug ... It should work by tomorrow (if not, force an update from the UI to get it) and then when it gets stuck, please give me the result of that web page, it should tell us what the system is doing.

**Comment by mrworf** [comment]
If it still works, should we close this issue and if it happens again, you can open a new one with logs and stacktrace (/debug and /debug/stacktrace respectively) ?

**Comment by mrworf** [comment]
Closing the issue, please reopen if still a problem
