### ISSUE TITLE
Images sometimes resized incorrectly

### ISSUE THREAD

**Issue by merlynkline** [mrworf/photoframe#63]
Images are sometimes expanded and cropped unnecessarily. I have observed this in several cases, e.g. when the image retrieved is 1803x1080px for display on a 1920x1080px display.

I believe this is caused by a bug in the static method makeFullframe() in `modules/helper.py`, triggered when the retrieved image is very close to the size of the display. In the cited example, where the image is 1803x1080px, it is not true that `adjHeight < displayHeight` so we end up with `padding` between 20 and 60 so `zoomOnly` is forced to `True`, causing `convert` to be called with `-resize ^1920x1080`. This expresses minimum dimensions so the width is expanded to 1080 and the height is therefore expanded and then cropped to keep the aspect ratio.

I have noticed this because I am using my simpleUrl service to fetch images from my own local server, which delivers them pre-sized to fit the frame. It also writes some descriptive text in the top right corner of the image, which is cropped in these cases. Otherwise these minor crops would probably go unnoticed.

There is likely a better algorithm for resizing images to handle near-fits such as this more gracefully, probably just doing nothing. I intend to give this some thought and submit a patch when I get the opportunity, if nobody else gets there first.

**Comment by mrworf** [comment]
Hmm... I think I understand what you're saying. Today the zoom mode will always force height (`-resize WxH^`) to match the display resolution, even if it might have been preferable to use width, all depending on how it fits. This causes black borders in some cases where there shouldn't have been.

Is my understanding correct, or did I misunderstand?

If the image is a perfect fit for the current display, there's a last `else` case which causes it to do nothing.

**Comment by mrworf** [comment]
Essentially, the parameters to `-resize` must take into account which dimension that should be stretched to match the display instead of hardcoding it to height.

**Comment by merlynkline** [comment]
The resize parameter I am blaming is here:
https://github.com/mrworf/photoframe/blob/f20a9954a1050625c119599636cce0dac2f891f5/modules/helper.py#L124
That's just based on a reading of the code though - I haven't had the opportunity to experiment with this yet.

If you can contrive to fetch an image of the size I mention then you should see this happen (there's a handy new service that might make that easier to achieve :) ). Basically the image is the right height but not quite as wide as the screen. This parameter causes `convert` to expand the width of the image to fit, at which point it is too tall (owing to aspect ratio preservation), so it gets cropped. I guess that if the user has explicitly requested "zoom only" then that's probably the right thing to do but in this case I haven't done that; I think it's been forced into zoom-only mode because the calculated padding is between 20 and 60. That's a good shortcut, but for my use case I'd rather never have the image cropped, and pay the price of black borders (so I don't lose my annotations).

**Comment by mrworf** [comment]
Hmm... but I just tried that (used https://images.pexels.com/photos/274131/pexels-photo-274131.jpeg?cs=srgb&dl=abstract-alcohol-art-274131.jpg&fm=jpg with the SimpleUrl service) and it looked correctly.

The imagemagick manual for `-resize` here http://www.imagemagick.org/Usage/resize/ states 

```
Fill Area Flag ('^' flag)
As of IM v6.3.8-3 IM now has a new geometry option flag '^' which is used to resize the image based on the smallest fitting dimension. That is, the image is resized to completely fill (and even overflow) the pixel area given. 
```

Granted, I tested on a linux laptop with ubuntu 18, but I'm fairly sure that the RPi image uses a modern enough IM6 version for this to work. 

What version of imagemagick's `convert` tool do you have?

**Comment by mrworf** [comment]
(and this keeps the aspect)

**Comment by mrworf** [comment]
![image](https://user-images.githubusercontent.com/1848354/51870986-001c2380-230a-11e9-8cd4-bfe29a978352.png)
The only thing visible here is that it didn't use width as the guiding dimension, which I stated above

**Comment by merlynkline** [comment]
I'm using the RPi image in your distro. But the doc you quote says it right there: "the image is resized to completely fill (and even **overflow**) the pixel area given". So what I think is happening is that the image is being resized so the width fits, which means that the height (which started out exactly correct) now overflows and is cropped.

**Comment by mrworf** [comment]
Hmm.. I think there's few things going on here 😃 

1. Zoom is supposed to fill the screen, sacrificing content by cropping if so needed (maybe it should be called Fill instead?)
2. There's a bug in zoom, causing it to ignore the case where an image is portrait, still treating it as landscape (thus giving black bars)
3. You want to have a true zoom, where it rescales with aspect but it will never crop

Does this make sense?

**Comment by merlynkline** [comment]
That makes sense but...
1. That's fine but I don't have zoom turned on. I think it's getting turned on in this case because the padding is small.
2. That may be true but the example I cite in the original report isn't portrait.
3. I guess that's what I want. I think that's what blur does though. But in this case it decides not to blur, I guess because there's not really enough room to do it and make it look nice, so it falls into zoom mode instead. I'd rather it just showed the fitted image with black bars in that particular case.

Sorry if all this is a bit vague - I've just driven three hours (so I'm nowhere near my photoframe to look at this properly) and I'm about to go to bed (I'm in the UK).

**Comment by mrworf** [comment]
1. Yes, it will default to zoom to fill when padding is < 20px
2. Can you share one of those images and the display size via email to github@sensenet.nu so I can replicate it here?
3. Yes, I need to revise the naming and also include some more sensible options so there's less magic... For example:
  - Fill (will zoom with correct aspect BUT crop if needed to fill display)
  - Fit (Resize with aspect to fit, leave blank spaces)
  - Blur (same as fit but fill blank space with blurred copy)
  - Auto (Blur unless too small border, then fill display instead)
That combined with no magic should hopefully cover all bases. Technically I should have a "Leave as-is unless too big" but who wants a poststamp sized photo if it's not big enough? 😆 ... Also add help text to explain the different modes so people know what they are choosing.

If that sounds good to you, then that is what I'll implement when I get a spare hour this weekend

Ugh, 3hr drive sucks. If it makes you feel better, I was on a train to my dentist to check on my wisdom teeth extraction 😐

**Comment by mrworf** [comment]
I started digging into the change, and quickly realized that my aspect resize code is semi-broken, it might resize the image but it can still end up with a height which is larger than display height. Not good. This should fix that as well. 

Work continues 😄

**Comment by merlynkline** [comment]
Sounds fine to me in general - I'll be happy as long as I can have some mode where photos are guaranteed to fill the screen as far as possible without losing their aspect ratio and without being cropped.

If you want to get into how I would go about designing if I were responsible for this as a commercial product then I'd say that your proposal introduces more complexity than most users will be interested in. The current UI is fine but you just need to consider the semantics carefully. Currently "zoom" really means "zoom to fill and crop to fit", while "blur" really means "zoom to fit and pad with blur to fill" (I think). If the user has chosen "blur" as opposed to "blur and zoom" then why did they do that? Presumably because they don't want it to zoom (i.e. crop). So in the case where you can't blur for whatever reason (e.g. padding too small) then you need to pick magic that doesn't zoom (crop), because the user has explicitly asked you not to do that. I'd say the simplest option would be to do nothing special, so you'd just end up with black bars on the sides or top of the image. Looking at the desktop wallpaper options on the Chromebook I'm typing this on, it has just two options: "Center", which means resize to *fit* the screen and then centre (not sure what it does with unfilled space but for a photoframe blur would be great), and "Center crop", which means resize to *fill* the screen and then crop out the centre. This is about as simple as it gets, is trivially supported by the `convert` utility, and covers all reasonable bases. I'd consider this a great model. IIRC Windows offers some other modes, like "tile", which I consider to be classic MS feature-creep nonsense and best ignored :)

But this isn't a commercial product and I'm not the PO or UX designer :)

I'll upload a demo image when I get home in a couple of days but any image of the size I mentioned in the original report should exhibit the same issue, as would many other sizes I imagine. My screen is full HD, 1920x1080.

HTH. Good luck with the teeth!

**Comment by mrworf** [comment]
Hehe, I've already changed the naming scheme and it's not that odd anymore. In fact, once you put sensible names on it, it pretty much match your chrome book. The whole reason that you even can choose is because there was some good arguments made for it.

The magic was added once support for 3.2" displays were added where it would look awful with too small of a padding (looked more like graphical glitches). 

So I agree with you, the resize options grew organically and now it's time to make them more user-friendly. 

I hope once the changes are pushed that you'll be happy. If not, open new issues and we'll see what can be done 😂

⁣Sent from TypeApp ​

**Comment by merlynkline** [comment]
I just updated my photoframe and pushed my test image to it and it now displays as I would expect so I'm marking this as resolved. From what you say I think you will be doing more but this issue no longer manifests as reported here. May thanks for your attention to this.
