### ISSUE TITLE
FR: Display pictures from local repository

### ISSUE THREAD

**Issue by shigadeyo** [mrworf/photoframe#70]
Just wanted to emphasize the desire for a local provider options such as file share and/or DLNA. That would be really helpful since I don't currently use any cloud services and would like to have several picture frames on the local network reading from the same location. Thanks!

**Comment by ceebu** [comment]
+1 to this request - 

I upload my newer photos from my phone to Google Photos, but my older photos, or the ones taken from my DSLR are stored locally - Would be great to have a local source.

**Comment by mrworf** [comment]
Just to clarify, local source would in this case be as in the memory card of the frame or a local networked share?

**Comment by Opalinus** [comment]
> a local networked share?

I think that's preferable. That way we can add new pictures without needing to add ssh or similiar.

**Comment by mrworf** [comment]
@ceebu I assume this is what you expect as well?

**Comment by starckdavid** [comment]
Adding a local source even on the SD can bring features to this great project, such as automatic processing photos of mails, use photod from wathsapp .... if people do not want to use it, it's not a problem 😀! Thanks

**Comment by mrworf** [comment]
Latest version now supports this thanks to @leogaube ... You should have a new photo provider called "USB-Photos"

**Comment by shigadeyo** [comment]
The USB-Photos is definitely a great new feature, but it doesn't provide any support for displaying pictures from a network repository (e.g., file share/NAS/DLNA) that was originally requested. Should I open a new feature request for that again?

**Comment by mrworf** [comment]
Yes, I think that's a good idea since it's a wholly different scenario.

Thanks for catching that :)
