### ISSUE TITLE
Custom Resolution

### ISSUE THREAD

**Issue by simphide** [mrworf/photoframe#79]
Hi,

is it possible to use a custom resolution?
The display I use is 1024*600p. Is there a way to set this resolution?

Thanks in advance!

**Comment by mrworf** [comment]
It should be listed under the dropdown box for the frame. It essentially queries the system about what the capabilities of the screen is and populates the list.

For non-HDMI displays, it will use whatever the default resolution is.

May I ask what screen and how is it connected?

**Comment by simphide** [comment]
Sure it is this display: https://www.amazon.de/gp/product/B07HQTCH4Z/

Photo frame is running on a pi zero. The display is connected via HDMI

**Comment by mrworf** [comment]
By default, photoframe and RPi will not use custom resolutions, but you can do that manually:

1. Open the `config.txt` file from the SD card on your computer
2. Remove any `hdmi_mode` line
3. Add `hdmi_cvt=1280 600 60`
4. Save file and reinsert SD card in RPi

You may have to play around a bit if this doesn't work on the first attempt. More about the hdmi_cvt option can be found here:
https://www.raspberrypi.org/documentation/configuration/config-txt/video.md

Let me know if it works

**Comment by mrworf** [comment]
Updated the comment, since I missed some details

**Comment by simphide** [comment]
Seems to work! Thank you very much!

**Comment by mrworf** [comment]
Glad I could help :)
