### ISSUE TITLE
I have tried every steps but the display is always showed blank.

### ISSUE THREAD

**Issue by tarbucndge** [mrworf/photoframe#8]
Please could you help? Maybe something happens to the photoframe.sensenet.nu?

**Comment by tarbucndge** [comment]
I am using raspberry Pi Zero W

**Comment by mrworf** [comment]
Are you using the hdmi output? Initial setup must be done with that. Did you edit the wifi config so it can connect to your local wifi?

Photoframe.Sensenet.Nu is only used during Google photos setup

**Comment by tarbucndge** [comment]
Yes I am using HDMI ouput. I have gone through the guide several times, but I just couldnt get it to work. What do you mean by initial setup?

**Comment by mrworf** [comment]
Are you using the ready made SD card releases or installing manually? 

⁣Sent from TypeApp ​

**Comment by tarbucndge** [comment]
Yes, of course, the pi is connected to wifi and I have already done the initial setup, with all the steps.

**Comment by tarbucndge** [comment]
I can connect to it from my computer via web browser too.

**Comment by tarbucndge** [comment]
I am using the ready made sd card release. I have tried both release june13
and june 20. Both gave the same result.

**Comment by tarbucndge** [comment]
I can connect to it from my computer via web browser too.

**Comment by tarbucndge** [comment]
I am using the ready made sd card release. I have tried both release june13 and june 20. Both gave the same result.

**Comment by mrworf** [comment]
And the web interface works? Do you get a drop down box with different display resolutions?

Also, can you attach the syslog after booting up?

**Comment by tarbucndge** [comment]
The web interface works. How can I get the syslog file?

**Comment by tarbucndge** [comment]
The dropdown box is working and I can see the screen blinking once I change the resolution.

**Comment by mrworf** [comment]
It's located in /var/log/... But you need ssh access to reach it. If the display is reacting to resolution changes, it could be you need to tweak the config.txt file. Add "hdmi_safe 1" without quotes to that file (on the sdcard) and try again. I think it's simply a matter of Hdmi not working with your display. See more about the options here https://www.raspberrypi.org/documentation/configuration/config-txt/video.md

**Comment by tarbucndge** [comment]
I've got the syslog file here
[syslog.txt](https://github.com/mrworf/photoframe/files/2152985/syslog.txt)

**Comment by tarbucndge** [comment]
I have tried to use the pi with a raspbian stretch sd card, the screen works fine with that. I also add the hdmi_safe 1 to the config.txt. When the pi boot up, the web interface change the resolution to 640x480p (60Hz) automatically.
The screen is still black.

**Comment by tarbucndge** [comment]
The small screen on the web interface is also blank.

**Comment by mrworf** [comment]
I think I know what is wrong. There's an issue causing it to fail early. If you go to /root/photoframe and run update.sh you'll get a bug fixed version. It should hopefully resolve this problem

**Comment by tarbucndge** [comment]
I have tried it. It does not work. I have the syslog file again here. Thank you.
[syslog.txt](https://github.com/mrworf/photoframe/files/2153012/syslog.txt)

**Comment by mrworf** [comment]
I have to get home and try it out on my rpi0w, should have some answers by the late afternoon. Sorry for all the hassle

**Comment by tarbucndge** [comment]
NO, Thank you! I am going to sleep now. Talk later.

**Comment by mrworf** [comment]
I've looked at the logs and found one corner case which wasn't covered. It still doesn't explain why it didn't work. One guess is, just like you mentioned, that photoframe.sensenet.nu had an outage causing request to take forever... I've resolved that and also pushed a new version.

Please login and run `update.sh` to make sure you're on the latest version. Then see if it works as intended. You might want to reauthorize google photos just to make sure it has a valid token from Google (note! it takes up to whatever you set the delay to after doing that until you'll see any pictures).

If you're still having issues, login and go to `/root/photoframe` and do the following:
```
service frame stop
./frame --debug | tee logfile.txt
```
And let it run, after a minute or so of no successful image, stop the program with CTRL-C (possibly need to press a few times due to `tee`) and send me the resulting `logfile.txt` which was created in `/root/photoframe/` and we'll see if we can't crack this nut.

**Comment by tarbucndge** [comment]
It didn't work. I tried the two commands you gave me.
The second command showed an error:  bash: ./frame: No such file or directory

**Comment by tarbucndge** [comment]
and when I tried to reboot the pi, sometime it showed on the screen that there is an issue showing the picture, please check the network settings.
I can also see the message from my web interface too. And also from ssh I can ping to a web address outside my network.

**Comment by mrworf** [comment]
Forgot to say you first need to change directory to where it's installed, so before running those two commands, type "cd /root/photoframe" (without quotes) 

Then run those two lines. The log file will be in /root/photoframe folder. 

⁣Sent from TypeApp ​

**Comment by tarbucndge** [comment]
I did do that. Look at the picture. 
![photoframe1](https://user-images.githubusercontent.com/33946641/42167445-537e5772-7e38-11e8-97a1-87755e8b5353.jpg)

**Comment by mrworf** [comment]
I must have been tired, sorry. It's called frame.py not frame. Sorry 

⁣Sent from TypeApp ​

**Comment by tarbucndge** [comment]
and here 
![photoframe2](https://user-images.githubusercontent.com/33946641/42167765-3600f348-7e39-11e8-908d-bea79a50f51b.jpg)

**Comment by mrworf** [comment]
Did you also collect the log using tee as described above?

**Comment by tarbucndge** [comment]
the logfile.txt is still empty. But I got this one. Hope it will help.
![photoframe3](https://user-images.githubusercontent.com/33946641/42167944-c1c6e5f4-7e39-11e8-83bd-8ab2e6e3f39b.jpg)

**Comment by tarbucndge** [comment]
I also got this one: 
![photoframe4](https://user-images.githubusercontent.com/33946641/42168147-5f25d526-7e3a-11e8-9925-29e8c74dde36.jpg)

**Comment by mrworf** [comment]
Yeah, I saw you using non-ascii keywords, which definitely was something I hadn't tested, and it may be part of the issue. But at least it's not having issues downloading the info about photos, but the data itself seems corrupt. If you can, can you join my slack service at https://dev.sensenet.nu/ (it works now if you tried before) and then we can chat in realtime for a bit faster turn-around 😄 There's a #photoframe channel.

**Comment by tarbucndge** [comment]
It's working now. I think the error is because of the keyword. The program doesnt understand my keyword (the keyword was typed in my language). and also the empty - picks the last photo added doesnt work too.
I change the keyword to english then is working.

**Comment by mrworf** [comment]
Hmm... can you paste the keyword which broke it here so I can test and fix it? It should deal with non-ascii text too

**Comment by mrworf** [comment]
The default part seems very random. According to google it's supposed to be last 1000 photos, but I think my system does only 5 photos. But nice that you found what it was.

**Comment by tarbucndge** [comment]
I have joined the slack, but cannot type anything.
Here is the keyword "Nếp"

**Comment by tarbucndge** [comment]
I can't see what you write from slack

**Comment by tarbucndge** [comment]
I can see what you say. I just cannot send you a message back.
Sure I can change the keyword to english. And wait for you. No rush really.

**Comment by mrworf** [comment]
You managed to send an A though.. odd, maybe browser issue. Anyway, yeah, I'm looking into the use of non-ascii characters now. Seems to be tricky since google is flatout rejecting the data. I'll update later today when I've done more testing

**Comment by tarbucndge** [comment]
Tha

**Comment by tarbucndge** [comment]
Thank you for resolving the issue!!! And congratulation!
