### ISSUE TITLE
How can I display only photos from a particular album ? 

### ISSUE THREAD

**Issue by jorisjean** [mrworf/photoframe#82]
Super nice project :-) but from what i see Photo frame will randomly dispaly images from the whole gallery. Is there any way to limit this only to one (shared) album ?
I could also create a dedicated google photo account for the fram and share an album from my personal one. Would this work ?
Thanks,
Joris
PS: not sure this is the right place to ask this but i'm taking my chance.

**Comment by mrworf** [comment]
If you use Google Photos provider, this is exactly how it works, ie, you specify one or more albums and it shows photos from these albums (selected at random).

The usecase you describe is used by other people running this frame and works fine :)

**Comment by mrworf** [comment]
Only picassa will show random photos if you don't specify anything

**Comment by jorisjean** [comment]
Thanks a lot !!
