### ISSUE TITLE
Email receipt retrieval of backup attachments in Google

### ISSUE THREAD

**Issue by starckdavid** [mrworf/photoframe#83]
Hi and thank you for your wonderful project. I want to assemble one for my great grandmother. And i ask me, if we can add a feature that allowed each of the 18 little children to simply sent on his picture frame photos by mail?
And maybe later store them in Google photo automatically?

**Comment by mrworf** [comment]
The best you can do is create a shared album which is shown on the frame and allow all the people access to upload photos to that shared album.

**Comment by mrworf** [comment]
Closing this since the described feature is more a google photos request than a frame specific one
