### ISSUE TITLE
Photo not changing

### ISSUE THREAD

**Issue by rustypasini** [mrworf/photoframe#88]
Once in a while, the photo stops changing, at which time the photoframe log shows this:

May  7 07:17:17 photoframe photoframe[13588]: 2019-05-07 07:17:17,462 - INFO - Interim saving of memory every 20 entries
May  7 08:18:01 photoframe photoframe[13588]: 2019-05-07 08:18:01,775 - INFO - Interim saving of memory every 20 entries
May  7 09:18:53 photoframe photoframe[13588]: 2019-05-07 09:18:53,073 - INFO - Interim saving of memory every 20 entries
May  7 10:19:40 photoframe photoframe[13588]: 2019-05-07 10:19:40,896 - INFO - Interim saving of memory every 20 entries
May  7 11:20:35 photoframe photoframe[13588]: 2019-05-07 11:20:35,792 - INFO - Interim saving of memory every 20 entries
May  7 11:57:01 photoframe photoframe[13588]: 2019-05-07 11:57:01,778 - WARNING - Unsupported media: image/heif
May  7 12:19:18 photoframe photoframe[13588]: 2019-05-07 12:19:18,012 - INFO - Interim saving of memory every 20 entries
May  7 13:22:05 photoframe photoframe[13588]: 2019-05-07 13:22:05,037 - INFO - Interim saving of memory every 20 entries
May  7 14:22:51 photoframe photoframe[13588]: 2019-05-07 14:22:51,341 - INFO - Interim saving of memory every 20 entries
May  7 15:23:34 photoframe photoframe[13588]: 2019-05-07 15:23:34,346 - INFO - Interim saving of memory every 20 entries
May  7 16:24:21 photoframe photoframe[13588]: 2019-05-07 16:24:21,079 - INFO - Interim saving of memory every 20 entries
May  7 17:25:05 photoframe photoframe[13588]: 2019-05-07 17:25:05,804 - INFO - Interim saving of memory every 20 entries
May  7 18:25:57 photoframe photoframe[13588]: 2019-05-07 18:25:57,083 - INFO - Interim saving of memory every 20 entries
May  7 18:39:49 photoframe photoframe[13588]: Traceback (most recent call last):
May  7 18:39:49 photoframe photoframe[13588]:   File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
May  7 18:39:49 photoframe photoframe[13588]:     self.process_request(request, client_address)
May  7 18:39:49 photoframe photoframe[13588]:   File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
May  7 18:39:49 photoframe photoframe[13588]:     self.finish_request(request, client_address)
May  7 18:39:49 photoframe photoframe[13588]:   File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
May  7 18:39:49 photoframe photoframe[13588]:     self.RequestHandlerClass(request, client_address, self)
May  7 18:39:49 photoframe photoframe[13588]:   File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
May  7 18:39:49 photoframe photoframe[13588]:     self.finish()
May  7 18:39:49 photoframe photoframe[13588]:   File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
May  7 18:39:49 photoframe photoframe[13588]:     self.wfile.close()
May  7 18:39:49 photoframe photoframe[13588]:   File "/usr/lib/python2.7/socket.py", line 283, in close
May  7 18:39:49 photoframe photoframe[13588]:     self.flush()
May  7 18:39:49 photoframe photoframe[13588]:   File "/usr/lib/python2.7/socket.py", line 307, in flush
May  7 18:39:49 photoframe photoframe[13588]:     self._sock.sendall(view[write_offset:write_offset+buffer_size])
May  7 18:39:49 photoframe photoframe[13588]: error: [Errno 32] Broken pipe

**Comment by mrworf** [comment]
Hmm...odd... you should have a newer version of the frame now which has a "Log Report" button. When you see this behavior again, click that button and attach the output to this issue and hopefully it will shed more light on why this happens.

Thanks

**Comment by rustypasini** [comment]
Thanks!  It happened twice before I posted this issue, however it has not occurred again since.

**Comment by mrworf** [comment]
Closing this for now, please use the "Log Report" and open a new issue if this comes back.
