### ISSUE TITLE
Update app to use new API for Google Photos

### ISSUE THREAD

**Issue by mrworf** [mrworf/photoframe#9]
Google has finally released the new API for accessing photos, but it would require a big change to the existing implementation.

More details about API here:
https://developers.google.com/photos/library/guides/list

Update Aug 13 2018, google killed the old API access without much warning. 

Working on rewriting the photoframe so it can use the new API. Will take a week or two due to other commitments as well.

**Comment by mrworf** [comment]
This should be done using the provider approach so the old setup still works for people

**Comment by mrworf** [comment]
So without warning, Google killed the old API.

**Comment by mrworf** [comment]
Luckily it was a false alarm, old API still works.

**Comment by charltones** [comment]
API is going to be turned off next month - in January. Did you get anywhere with rewriting to use the new photos API?

**Comment by roboticsguy1988** [comment]
I am curious as well if you made any progress with the new API?

**Comment by mrworf** [comment]
A PR was submitted by aniemoeller but it is not in yet since I'm in the middle of making sure photoframe can have many different sources of photos.

I just got that working yesterday and will now work on getting a new photo provider for Google Photos and it should be done and released during the holidays. Anyone using the photoframe today will be migrated to the new setup but will need to setup Google Photos separately since it behaves differently.

See branch serviceapi for latest work on this. Hope this helps @charltones and @roboticsguy1988

**Comment by mrworf** [comment]
Very brave souls can try the GooglePhotos support now, but beware, no support is given if it breaks your installation, so backup that SD card before testing :)

1. Switch to serviceapi branch
2. Log into google api console and enable Google Photos API (takes 5min to take effect!)
3. Add the new GooglePhotos provider

If this sounds like greek, you're better off waiting for official rollout  :)

**Comment by mrworf** [comment]
Merged to master, closing this issue. Please open new issues if there are problems found
