### ISSUE TITLE
Refresh Images 

### ISSUE THREAD

**Issue by displayscreens** [mrworf/photoframe#91]
Hi, 
Is it still possible to refresh the image list after all images displayed?  Currently only refreshing 24 hours or on a settings change.
p.s - love this, best photoframe out there
Thanks

**Comment by mrworf** [comment]
I think the behavior actually just changed, so whenever you run out of photos for a service, it will refresh automatically.

**Comment by mrworf** [comment]
I need to confirm that :)

**Comment by displayscreens** [comment]
OK thanks, it doesn't seem to be working for me, i did notice in the settings.json it was set to "24", i've tried "0" and "", but not success.

**Comment by leogaube** [comment]
I am sorry, if this is something that I have caused with my changes. Currently, the "refresh-content" option in settings does not seem to do anything, however, I just had a quick look at the git history and I think it never did anything.
This should be easy to fix, but I would leave it to @mrworf to decide in which class to implement it, as it currently only affacts the GooglePhotosApi but might be important for future services as well.

In the meantime, you could remove keywords and add them again, or delete the .json-files inside /root/photoframe_config/services/{service_id}/private/ manually.

**Comment by mrworf** [comment]
@leogaube I think I did it when I changed over to GooglePhotos and service based interface.

**Comment by displayscreens** [comment]
Can confirm not actually updating at all, even after 24 hours.
Ran two instances
1 x Fresh install left running 24 hours no update
1 x Fresh install updates only after "forget memory" pressed

**Comment by beerone1** [comment]
Hi I was just wondering if this issued had been fixed at all

**Comment by mrworf** [comment]
Sorry, been on vacation in Sweden so no update on this yet. 

On July 1, 2019 9:59:36 PM PDT, beerone1 <notifications@github.com> wrote:
>Hi I was just wondering if this issued had been fixed at all
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/mrworf/photoframe/issues/91#issuecomment-507518557

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by snorlatx** [comment]
Hi, I really like this program, it's been the best photoframe slideshow so far.

I'm also having trouble getting new images to load after placing them in my Google Photos album. I tried using SSH to create a cronjob to reboot the pi once a day, but no luck. Will there be any updates for this issue?

**Comment by mrworf** [comment]
I should have more time now considering we're not supposed to leave home 😂 I'll try and look into it by the end of the week. Thanks for reminding me.

On April 8, 2020 7:28:26 AM PDT, snorlatx <notifications@github.com> wrote:
>Hi, I really like this program, it's been the best photoframe slideshow
>so far.
>
>I'm also having trouble getting new images to load after placing them
>in my Google Photos album. I tried using SSH to create a cronjob to
>reboot the pi once a day, but no luck. Will there be any updates for
>this issue?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/mrworf/photoframe/issues/91#issuecomment-610992180

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by PatrickJenner** [comment]
Thanks for all the good works @mrworf, I love the app!
I am having similar problems like @snorlatx . My Google Photos account is telling me I have 90 items in a folder even though I count 115. The Pi is displaying approx. 70 of them. New images may only show up if I delete another. I have turned of caching, toggled random order display and changed the order in Google photos all without luck.

**Comment by mrworf** [comment]
![image](https://user-images.githubusercontent.com/1848354/79392914-0b686880-7f29-11ea-9cef-ef9549966746.png)
coming soon to a frame near you :) Should help understand any conflicting info about what images it will show. Also working on re-introducing the freshness feature (ie, force refresh of indexes if too old). Stay tuned

**Comment by PatrickJenner** [comment]
I may have solved my issue. Whenever I update my Google Photos in the Android app the images are not exposed to the Photoframe app. I need to open the included Google Photos folder in the Photoframe webinterface and tick every photo in there that I like to expose. It is like there are two versions of Google Photos, the official app and its web interface.

**Comment by mrworf** [comment]
Do you mean you need to add the photos to a specific album or?

**Comment by mrworf** [comment]
update. Running my frame now with the changes, just want to make sure nothing breaks and that it refreshes the index when out of photos. Should take a day or so before I know

**Comment by crazyhondaownr** [comment]
> update. Running my frame now with the changes, just want to make sure nothing breaks and that it refreshes the index when out of photos. Should take a day or so before I know

Is there any update on this ? have these updates been pushed

**Comment by mrworf** [comment]
Took longer due to the whole navigate previous/next photo, etc. Right now it's broke, but I may push it anyway to fix the refresh situation. Took time to test and validate and had to refactor a lot of old code since the memory subsystem was ... shall we say, less ideal (ie, lots of bugs). Expect update in the coming days this week

**Comment by mrworf** [comment]
it's broke refers to the prev/next :)

**Comment by mrworf** [comment]
Merged, fixes many issues with memory (both usage and remembering things). Streamlines the code base and simplifies parts.
Still more work to be done, but please give it a spin. Should auto update over night but you can force it as needed via the Web UX.

**Comment by mrworf** [comment]
Closing this since freshness is now working. Please reopen if still an issue
