### ISSUE TITLE
Photo frame error on black screen

### ISSUE THREAD

**Issue by roboticsguy1988** [mrworf/photoframe#92]
The two photoframes I setup for family members is now displaying the error "GooglePhotos failed: You haven't implemented "getImagesFor" yet"

Any ideas? 
![IMG_20190609_162504](https://user-images.githubusercontent.com/21338179/59163761-2aa99480-8ad3-11e9-8b2c-b9adcea1319f.jpg)

**Comment by mrworf** [comment]
Hmm... there was a bigger change this week to enable a bunch of neat tricks, maybe something went wrong (I did test it, but as always, murphy is always waiting in the shadows). I'll do some testing on my end and see if I can replicate it.

**Comment by mrworf** [comment]
Actually, this is a false error. Any chance you can login to the web interface and supply the output from "Log Report" (button) ? Code indicates that it could be an issue with google queries or the result of it.

**Comment by mrworf** [comment]
Behavior had also changed internally causing a temporary error to be deemed permanent. I've changed and pushed that, let me know what happened :) Also, if you're still having issues, please utilize the new "Log Report" button to get a wealth of information which helps me determine what's going on.

**Comment by roboticsguy1988** [comment]
Thank you! They are both working now. Sorry it took a while to reply the photo frames are at family members houses. I should really install remote control software on each of them.

**Comment by mrworf** [comment]
They just started working again without any interaction from you? Or did it take 24hrs (due to the update I made)

Glad it's working again. 

On June 11, 2019 4:43:25 AM PDT, roboticsguy1988 <notifications@github.com> wrote:
>Thank you! They are both working now. Sorry it took a while to reply
>the photo frames are at family members houses. I should really install
>remote control software on each of them.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/mrworf/photoframe/issues/92#issuecomment-500804997

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by roboticsguy1988** [comment]
Correct. I only am able to make it over there on weekends, so there was no user interaction. But it very well could have hit the 24 hour time window as well.
