### ISSUE TITLE
zoom to fill but still borders

### ISSUE THREAD

**Issue by diadakan** [mrworf/photoframe#93]
Thanks for this project! I have installed the software. In the configuration i have chosen for "zoom to fill" but there are still black borders around my screen? is it possible to get my photos real full screen? Thanks

Photoframe configuration:
1920*1080, zoom to fill, on and 24 inch monitor.

![IMG_20190614_201334](https://user-images.githubusercontent.com/51834099/59529317-ff62e300-8ee0-11e9-8a3d-b83c91c4a7ce.jpg)

**Comment by jmhammond** [comment]
It might be an issue with `overscan`. Here's a post that walks through some settings to change. 
You'd edit the /boot/config.txt file either directly on the microsd card on your computer or over ssh.

**Comment by diadakan** [comment]
thanks
