### ISSUE TITLE
Problem adding Google Pictures

### ISSUE THREAD

**Issue by mchampio** [mrworf/photoframe#95]
Hi mrworf
I tried to use the device on another network on Jun 30, but it couldn't find any google albums.
Today (Jul 1) on my home network I am trying to add google photos to the list of photo sources

 It allows me to select google photos, but doesn't open the window to allow me to input details of the album
[debug.txt](https://github.com/mrworf/photoframe/files/3343615/debug.txt)

**Comment by mrworf** [comment]
Looking at the log it would seem that the authorization has lapsed. Try removing it and re-adding the Google Photos provider and reauthorize it and see if that works.
On 6/30/2019 6:31:19 PM, mchampio <notifications@github.com> wrote:
Hi mrworf
I tried to use the device on another network on Jun 30, but it couldn't find any google albums.
Today (Jul 1) on my home network I am trying to add google photos to the list of photo sources
It allows me to select google photos, but doesn't open the window to allow me to input details of the album
debug.txt [https://github.com/mrworf/photoframe/files/3343615/debug.txt]

**Comment by mrworf** [comment]
"should" detect this error now (wasn't able to reproduce). Let me know if this is still an issue. Closing for now
